#include<bits/stdc++.h>
using namespace std;
long long a[100000],n,k,v,t,vv;
int cmp(int x,int y){
	return x>y;
}
int main(){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin>>n;
	for(int i=1;i<=n;i++) cin>>a[i];
	if(n<3) cout<<0;
	else{
		if(n==3){
			t=2*max(a[1],max(a[2],a[3]));
			v=a[1]+a[2]+a[3];
			if(v>t) cout<<1;
			else cout<<0;
		}
		else if(n==4){
			t=2*max(a[1],max(a[2],a[3]));
			v=a[1]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[4]));
			v=a[1]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[4],max(a[2],a[3]));
			v=a[4]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],a[3])));
			v=a[1]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			cout<<vv;
		}
		else if(n==5){
			t=2*max(a[1],max(a[2],a[3]));
			v=a[1]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[4]));
			v=a[1]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[5]));
			v=a[1]+a[2]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],a[3]));
			v=a[1]+a[4]+a[3];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],a[5]));
			v=a[1]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],a[5]));
			v=a[1]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[4],max(a[2],a[3]));
			v=a[4]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],a[3]));
			v=a[5]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],a[4]));
			v=a[5]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[3],max(a[4],a[5]));
			v=a[3]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],a[3])));
			v=a[1]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[5],a[3])));
			v=a[1]+a[2]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],max(a[4],a[3])));
			v=a[5]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],a[5])));
			v=a[1]+a[2]+a[5]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],max(a[5],a[3])));
			v=a[1]+a[4]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],max(a[5],a[3]))));
			v=a[1]+a[2]+a[3]+a[4]+a[5];
			if(v>t) vv++;
			cout<<vv;
		}
		else if(n==6){
			t=2*max(a[1],max(a[2],a[3]));
			v=a[1]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[4]));
			v=a[1]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[5]));
			v=a[1]+a[2]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[6]));
			v=a[1]+a[2]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],a[4]));
			v=a[1]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],a[5]));
			v=a[1]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[6],a[3]));
			v=a[1]+a[6]+a[3];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],a[5]));
			v=a[5]+a[4]+a[1];
			if(v>t) vv++;
			t=2*max(a[6],max(a[1],a[4]));
			v=a[6]+a[1]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[6],a[5]));
			v=a[1]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[4],max(a[2],a[3]));
			v=a[4]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[3],max(a[2],a[5]));
			v=a[2]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],a[3]));
			v=a[3]+a[2]+a[6];
			if(v>t) vv++;
			t=2*max(a[4],max(a[2],a[5]));
			v=a[4]+a[2]+a[5];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],a[4]));
			v=a[6]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],a[5]));
			v=a[6]+a[2]+a[5];
			if(v>t) vv++; 
			t=2*max(a[3],max(a[4],a[5]));
			v=a[5]+a[4]+a[3];
			if(v>t) vv++;
			t=2*max(a[3],max(a[4],a[6]));
			v=a[3]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[6],max(a[3],a[5]));
			v=a[6]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[4],max(a[6],a[5]));
			v=a[4]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],a[3])));
			v=a[1]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[5],a[3])));
			v=a[1]+a[2]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],a[3])));
			v=a[1]+a[2]+a[3]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],a[5])));
			v=a[5]+a[2]+a[1]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],max(a[4],a[1])));
			v=a[4]+a[2]+a[1]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],a[5])));
			v=a[1]+a[2]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],max(a[4],a[3])));
			v=a[5]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],max(a[4],a[3])));
			v=a[6]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],max(a[6],a[3])));
			v=a[5]+a[2]+a[3]+a[6];
			if(v>t) vv++;
			t=2*max(a[4],max(a[2],max(a[4],a[5])));
			v=a[5]+a[2]+a[6]+a[4];
			if(v>t) vv++;
			t=2*max(a[3],max(a[5],max(a[4],a[6])));
			v=a[4]+a[3]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],max(a[5],a[3]))));
			v=a[1]+a[2]+a[3]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],max(a[6],a[3]))));
			v=a[1]+a[2]+a[3]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[5],a[3]))));
			v=a[1]+a[2]+a[3]+a[6]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[5],a[4]))));
			v=a[1]+a[2]+a[4]+a[6]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],max(a[6],max(a[5],a[3]))));
			v=a[1]+a[4]+a[3]+a[6]+a[5];
			if(v>t) vv++;
			t=2*max(a[4],max(a[2],max(a[6],max(a[5],a[3]))));
			v=a[4]+a[2]+a[3]+a[6]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[5],max(a[3],a[4])))));
			v=a[1]+a[2]+a[3]+a[6]+a[5]+a[4];
			if(v>t) vv++;
			cout<<vv;
		}
		else if(n==7){
			t=2*max(a[1],max(a[2],a[3]));
			v=a[1]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[4]));
			v=a[1]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[5]));
			v=a[1]+a[2]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[6]));
			v=a[1]+a[2]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],a[7]));
			v=a[1]+a[2]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],a[4]));
			v=a[1]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],a[5]));
			v=a[1]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],a[6]));
			v=a[1]+a[3]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],a[7]));
			v=a[1]+a[3]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],a[5]));
			v=a[1]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],a[6]));
			v=a[1]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],a[7]));
			v=a[1]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[5],a[6]));
			v=a[1]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[5],a[7]));
			v=a[1]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[6],a[7]));
			v=a[1]+a[6]+a[7];
			if(v>t) vv++;
			t=2*max(a[4],max(a[2],a[3]));
			v=a[4]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],a[3]));
			v=a[5]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],a[3]));
			v=a[6]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[7],max(a[2],a[3]));
			v=a[7]+a[2]+a[3];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],a[4]));
			v=a[5]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],a[4]));
			v=a[6]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[7],max(a[2],a[4]));
			v=a[7]+a[2]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],a[5]));
			v=a[6]+a[2]+a[5];
			if(v>t) vv++;
			t=2*max(a[7],max(a[2],a[5]));
			v=a[7]+a[2]+a[5];
			if(v>t) vv++;
			t=2*max(a[7],max(a[2],a[6]));
			v=a[7]+a[2]+a[6];
			if(v>t) vv++;
			t=2*max(a[5],max(a[3],a[4]));
			v=a[5]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[3],a[4]));
			v=a[6]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[7],max(a[3],a[4]));
			v=a[7]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[3],a[5]));
			v=a[6]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[7],max(a[3],a[5]));
			v=a[7]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[7],max(a[3],a[6]));
			v=a[7]+a[3]+a[6];
			if(v>t) vv++;
			t=2*max(a[5],max(a[4],a[6]));
			v=a[5]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[5],max(a[4],a[7]));
			v=a[5]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[6],max(a[4],a[7]));
			v=a[6]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[6],max(a[5],a[7]));
			v=a[6]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],a[3])));
			v=a[1]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[5],a[3])));
			v=a[1]+a[2]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],a[3])));
			v=a[1]+a[2]+a[3]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],a[3])));
			v=a[1]+a[2]+a[3]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[5],a[4])));
			v=a[1]+a[2]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],a[4])));
			v=a[1]+a[2]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],a[4])));
			v=a[1]+a[2]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],a[5])));
			v=a[1]+a[2]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],a[5])));
			v=a[1]+a[2]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],a[6])));
			v=a[1]+a[2]+a[6]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[4],a[5])));
			v=a[1]+a[3]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[4],a[6])));
			v=a[1]+a[3]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[4],a[7])));
			v=a[1]+a[3]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[5],a[6])));
			v=a[1]+a[3]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[5],a[7])));
			v=a[1]+a[3]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[6],a[7])));
			v=a[1]+a[3]+a[6]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],max(a[5],a[6])));
			v=a[1]+a[4]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],max(a[5],a[7])));
			v=a[1]+a[4]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[4],max(a[7],a[6])));
			v=a[1]+a[4]+a[7]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[5],max(a[7],a[6])));
			v=a[1]+a[5]+a[7]+a[6];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],max(a[4],a[3])));
			v=a[5]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],max(a[4],a[3])));
			v=a[6]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[7],max(a[2],max(a[4],a[3])));
			v=a[7]+a[2]+a[3]+a[4];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],max(a[3],a[5])));
			v=a[6]+a[2]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[7],max(a[2],max(a[3],a[5])));
			v=a[7]+a[2]+a[3]+a[5];
			if(v>t) vv++;
			t=2*max(a[7],max(a[2],max(a[3],a[6])));
			v=a[7]+a[2]+a[3]+a[6];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],max(a[4],a[6])));
			v=a[5]+a[2]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[5],max(a[2],max(a[4],a[7])));
			v=a[5]+a[2]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],max(a[4],a[7])));
			v=a[6]+a[2]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[6],max(a[2],max(a[5],a[7])));
			v=a[6]+a[2]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[3],max(a[4],max(a[5],a[6])));
			v=a[3]+a[4]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[3],max(a[4],max(a[5],a[7])));
			v=a[3]+a[4]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[3],max(a[4],max(a[6],a[7])));
			v=a[3]+a[4]+a[6]+a[7];
			if(v>t) vv++;
			t=2*max(a[5],max(a[4],max(a[6],a[7])));
			v=a[5]+a[4]+a[6]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],max(a[5],a[3]))));
			v=a[1]+a[2]+a[3]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],max(a[6],a[3]))));
			v=a[1]+a[2]+a[3]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[4],max(a[7],a[3]))));
			v=a[1]+a[2]+a[3]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[5],a[3]))));
			v=a[1]+a[2]+a[3]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],max(a[5],a[3]))));
			v=a[1]+a[2]+a[3]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[7],a[3]))));
			v=a[1]+a[2]+a[3]+a[7]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[5],max(a[4],a[6]))));
			v=a[1]+a[2]+a[5]+a[6]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[5],max(a[4],a[7]))));
			v=a[1]+a[2]+a[5]+a[7]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[4],a[7]))));
			v=a[1]+a[2]+a[6]+a[7]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[5],a[7]))));
			v=a[1]+a[2]+a[6]+a[7]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[6],max(a[5],a[4]))));
			v=a[1]+a[3]+a[6]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[7],max(a[5],a[4]))));
			v=a[1]+a[3]+a[7]+a[4]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[7],max(a[6],a[4]))));
			v=a[1]+a[3]+a[7]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[3],max(a[7],max(a[6],a[5]))));
			v=a[1]+a[3]+a[7]+a[5]+a[6];
			if(v>t) vv++;
			t=2*max(a[1],max(a[5],max(a[7],max(a[6],a[4]))));
			v=a[1]+a[5]+a[7]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[2],max(a[5],max(a[3],max(a[6],a[4]))));
			v=a[2]+a[5]+a[3]+a[4]+a[6];
			if(v>t) vv++;
			t=2*max(a[2],max(a[5],max(a[3],max(a[7],a[4]))));
			v=a[2]+a[5]+a[3]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[2],max(a[6],max(a[3],max(a[7],a[4]))));
			v=a[2]+a[6]+a[3]+a[4]+a[7];
			if(v>t) vv++;
			t=2*max(a[2],max(a[6],max(a[3],max(a[7],a[5]))));
			v=a[2]+a[6]+a[3]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[2],max(a[6],max(a[4],max(a[7],a[5]))));
			v=a[2]+a[6]+a[4]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[3],max(a[6],max(a[4],max(a[7],a[5]))));
			v=a[3]+a[6]+a[4]+a[5]+a[7];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[6],max(a[5],max(a[3],a[4])))));
			v=a[1]+a[2]+a[3]+a[6]+a[5]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],max(a[5],max(a[3],a[4])))));
			v=a[1]+a[2]+a[3]+a[7]+a[5]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],max(a[6],max(a[3],a[4])))));
			v=a[1]+a[2]+a[3]+a[7]+a[6]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],max(a[6],max(a[3],a[5])))));
			v=a[1]+a[2]+a[3]+a[7]+a[6]+a[5];
			if(v>t) vv++;
			t=2*max(a[1],max(a[2],max(a[7],max(a[6],max(a[5],a[4])))));
			v=a[1]+a[2]+a[5]+a[7]+a[6]+a[4];
			if(v>t) vv++;
			t=2*max(a[1],max(a[5],max(a[7],max(a[6],max(a[3],a[4])))));
			v=a[1]+a[5]+a[3]+a[7]+a[6]+a[4];
			if(v>t) vv++;
			t=2*max(a[2],max(a[5],max(a[7],max(a[6],max(a[3],a[4])))));
			v=a[2]+a[5]+a[3]+a[7]+a[6]+a[4];
			if(v>t) vv++;
			t=2*max(a[2],max(a[5],max(a[7],max(a[6],max(a[3],max(a[4],a[1]))))));
			v=a[2]+a[5]+a[3]+a[7]+a[6]+a[4]+a[1];
			if(v>t) vv++;
			cout<<vv;
		} 
		else cout<<0;
	}
	return 0;
} 
