#include<bits/stdc++.h>
using namespace std;
int n;
int main(){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin>>n;
	if(n<3){
		cout<<"0";
		return 0;
	}
	if(n==3){
		int a,b,c;
		cin>>a>>b>>c;
		if((a+b+c)>max({a,b,c})*2){
			cout<<1;
		}
	}
	else if(n==4){
		int a,b,c,d,sum=0;
		cin>>a>>b>>c>>d;
		if((a+b+c)>max({a,b,c})*2){
			sum++;
		}
		if((a+d+c)>max({a,d,c})*2){
			sum++;
		}
		if((a+b+d)>max({a,b,d})*2){
			sum++;
		}
		if((d+b+c)>max({d,b,c})*2){
			sum++;
		}
		if((a+b+c+d)>max({a,b,c,d})*2){
			sum++;
		}
		cout<<sum;
	}
	else if(n==5){
		int a,b,c,d,e,sum=0;
		cin>>a>>b>>c>>d>>e;
		if((a+b+c)>max({a,b,c})*2){
			sum++;
		}
		if((a+d+c)>max({a,d,c})*2){
			sum++;
		}
		if((a+b+d)>max({a,b,d})*2){
			sum++;
		}
		if((d+b+c)>max({d,b,c})*2){
			sum++;
		}
		if((a+b+e)>max({a,b,e})*2){
			sum++;
		}
		if((a+c+e)>max({a,c,e})*2){
			sum++;
		}
		if((a+d+e)>max({a,d,e})*2){
			sum++;
		}	
		if((b+c+e)>max({b,c,e})*2){
			sum++;
		}
		if((b+d+e)>max({b,d,e})*2){
			sum++;
		}
		if((c+d+e)>max({c,d,e})*2){
			sum++;
		}
		if((a+b+c+d)>max({a,b,c,d})*2){
			sum++;
		}
		if((a+b+c+e)>max({a,b,c,e})*2){
			sum++;
		}
		if((a+b+e+d)>max({a,b,e,d})*2){
			sum++;
		}
		if((a+e+c+d)>max({a,e,c,d})*2){
			sum++;
		}
		if((e+b+c+d)>max({e,b,c,d})*2){
			sum++;
		}
		if((a+b+c+d+e)>max({a,b,c,d,e})*2){
			sum++;
		}
		cout<<sum;
	}
	else if(n>=6){
		int a,b,c,d,e,f,sum=0;
		cin>>a>>b>>c>>d>>e>>f;
		if((a+b+c)>max({a,b,c})*2){
			sum++;
		}
		if((a+d+c)>max({a,d,c})*2){
			sum++;
		}
		if((a+b+d)>max({a,b,d})*2){
			sum++;
		}
		if((d+b+c)>max({d,b,c})*2){
			sum++;
		}
		if((a+b+e)>max({a,b,e})*2){
			sum++;
		}
		if((a+c+e)>max({a,c,e})*2){
			sum++;
		}
		if((a+d+e)>max({a,d,e})*2){
			sum++;
		}	
		if((b+c+e)>max({b,c,e})*2){
			sum++;
		}
		if((b+d+e)>max({b,d,e})*2){
			sum++;
		}
		if((c+d+e)>max({c,d,e})*2){
			sum++;
		}
		if((a+b+f)>max({a,b,f})*2){
			sum++;
		}
		if((a+c+f)>max({a,c,f})*2){
			sum++;
		}
		if((a+d+f)>max({a,d,f})*2){
			sum++;
		}
		if((a+e+f)>max({a,e,f})*2){
			sum++;
		}
		if((b+c+f)>max({b,c,f})*2){
			sum++;
		}
		if((b+d+f)>max({b,d,f})*2){
			sum++;
		}
		if((b+e+f)>max({b,e,f})*2){
			sum++;
		}	
		if((c+d+f)>max({c,d,f})*2){
			sum++;
		}
		if((c+e+f)>max({c,e,f})*2){
			sum++;
		}
		if((d+e+f)>max({d,e,f})*2){
			sum++;
		}
		if((a+b+c+d)>max({a,b,c,d})*2){
			sum++;
		}
		if((a+b+c+e)>max({a,b,c,e})*2){
			sum++;
		}
		if((a+b+d+e)>max({a,b,e,d})*2){
			sum++;
		}
		if((a+c+d+e)>max({a,e,c,d})*2){
			sum++;
		}
		if((a+b+c+f)>max({a,b,c,e})*2){
			sum++;
		}
		if((a+b+d+f)>max({a,b,e,d})*2){
			sum++; 
		}
		if((a+c+d+f)>max({a,e,c,d})*2){
			sum++;
		}
		if((a+c+e+f)>max({e,b,c,d})*2){
			sum++;
		}		
		if((a+d+e+f)>max({e,b,c,d})*2){
			sum++;
		}		
		if((b+c+d+f)>max({b,c,d,f})*2){
			sum++;
		}
		if((b+c+e+f)>max({b,c,e,f})*2){
			sum++;
		}		
		if((b+d+e+f)>max({b,d,e,f})*2){
			sum++;
		}
		if((c+d+e+f)>max({c,d,e,f})*2){
			sum++;
		}
		if((a+b+c+d+e)>max({a,b,c,d,e})*2){
			sum++;
		}
		if((a+b+c+d+f)>max({a,b,c,d,f})*2){
			sum++;
		}
		if((a+b+c+f+e)>max({a,b,c,f,e})*2){
			sum++;
		}
		if((a+b+f+d+e)>max({a,b,f,d,e})*2){
			sum++;
		}
		if((a+f+c+d+e)>max({a,f,c,d,e})*2){
			sum++;
		}
		if((f+b+c+d+e)>max({f,b,c,d,e})*2){
			sum++;
		}
		if((a+b+c+d+e+f)>max({a,b,c,d,e,f})*2){
			sum++;
		}
		cout<<sum;
	}	
	return 0;
} 
