#include<bits/stdc++.h>
using namespace std;
int main(){
    freopen("club.in","r",stdin);
    freopen("club.out","w",stdout);
	int n,n1,n2,bu,s=0,d=0,f=0,g=0,h=0,j=0,k=0,l=0,s1=0,d1=0,f1=0,g1=0,h1=0,j1=0,k1=0,l1=0,s2=0,d2=0,f2=0,g2=0,h2=0,j2=0,k2=0,l2=0;
	cin>>bu;
	cin>>n;
	int a[n],b[n],c[n],m[100000];
	for(int i=0;i<n;i++){
        cin>>a[i]>>b[i]>>c[i];
        if(b[i]>a[i]&&b[i]>c[i]){
            d++;
            j+=b[i];
        }
        if(a[i]>b[i]&&a[i]>c[i]){
            s++;
            h+=a[i];
        }
        if(c[i]>b[i]&&c[i]>a[i]){
            f++;
            k+=c[i];
        }else{
            g++;
            l+=a[i];
            m[i]=a[i];
        }
	}
        if(s<n/2&&d<n/2&&f<n/2){
                if(s+g<n/2&&d+g<n/2&&f+g<n/2){
                if(h>j&&h>k){
                  cout<<h+l;
                }
                if(j>h&&j>k){
                  cout<<j+l;
                  }
                if(k>h&&k>j){
                  cout<<k+l;
                  }
            }
        }
        if(s<n/2){
            if(s+g<n){
                cout<<h+l;
            }
        }
        if(d<n/2){
            if(d+g<n){
                cout<<j+l;
            }
        }
        if(f<n/2){
            if(d+g<n){
                cout<<k+l;
            }
        }
        for(int o=0;o<g+1;o++){
            if(s+o<n/2){
               h+=m[o];
            }
            if(d+o<n/2){
               j+=m[o];
            }
            if(f+o<n/2){
               k+=m[o];
            }
        }
    if(k>=j&&k>=h){
        cout<<k;
    }
    if(h>=j&&h>=j){
        cout<<h;
    }
    if(j>=k&&j>=h){
        cout<<j;
    }


	cin>>n1;
	int a1[n1],b1[n1],c1[n1],m1[100000];
	for(int i=0;i<n1;i++){
        cin>>a1[i]>>b1[i]>>c1[i];
        if(b1[i]>a1[i]&&b1[i]>c1[i]){
            d1++;
            j1+=b1[i];
        }
        if(a1[i]>b1[i]&&a1[i]>c1[i]){
            s1++;
            h1+=a1[i];
        }
        if(c1[i]>b1[i]&&c1[i]>a1[i]){
            f1++;
            k1+=c1[i];
        }else{
            g1++;
            l1+=a1[i];
            m1[i]=a1[i];
        }

	}if(s1<n1/2&&d1<n1/2&&f1<n1/2){
            if(s1+g1<n1/2&&d1+g1<n1/2&&f1+g1<n1/2){
                if(h1>j1&&h1>k1){
                  cout<<h1+l1;
                }
                if(j1>h1&&j1>k1){
                  cout<<j1+l1;
                  }
                if(k>h&&k1>j1){
                  cout<<k1+l1;
                  }
            }
        }
        if(s1<n1/2){
            if(s1+g1<n1){
                cout<<h1+l1;
            }
        }
        if(d1<n1/2){
            if(d1+g1<n1){
                cout<<j1+l1;
            }
        }
        if(f1<n1/2){
            if(d1+g1<n1){
                cout<<k1+l1;
            }
        }
        for(int o=0;o<g1+1;o++){
            if(s1+o<n1/2){
               h1+=m1[o];
            }
            if(d1+o<n1/2){
               j1+=m1[o];
            }
            if(f1+o<n1/2){
               k1+=m1[o];
            }
        }
    if(k1>=j1&&k1>=h1){
        cout<<k;
    }
    if(h1>=j1&&h1>=j1){
        cout<<h;
    }
    if(j1>=k1&&j1>=h1){
        cout<<j1;
    }
	cin>>n2;
	int a2[n2],b2[n2],c2[n2],m2[100000];
	for(int i=0;i<n2;i++){
        cin>>a2[i]>>b2[i]>>c2[i];
        if(b2[i]>a2[i]&&b2[i]>c2[i]){
            d2++;
            j2+=b2[i];
        }
        if(a2[i]>b2[i]&&a2[i]>c2[i]){
            s2++;
            h2+=a2[i];
        }
        if(c2[i]>b2[i]&&c2[i]>a2[i]){
            f2++;
            k2+=c2[i];
        }else{
            g2++;
            l2+=a2[i];
            m2[i]=a2[i];
        }

	}if(s2<n2/2&&d2<n2/2&&f2<n2/2){
            if(s2+g2<n2/2&&d2+g2<n2/2&&f2+g2<n2/2){
                if(h2>j2&&h2>k2){
                  cout<<h2+l2;
                }
                if(j2>h2&&j2>k2){
                  cout<<j2+l2;
                  }
                if(k2>h2&&k2>j2){
                  cout<<k2+l2;
                  }
            }
        }
        if(s2<n2/2){
            if(s2+g2<n2){
                cout<<h2+l2;
            }
        }
        if(d2<n2/2){
            if(d2+g2<n2){
                cout<<j2+l2;
            }
        }
        if(f2<n2/2){
            if(d2+g2<n2){
                cout<<k2+l2;
            }
        }
        for(int o=0;o<g2+1;o++){
            if(s2+o<n2/2){
               h2+=m2[o];
            }
            if(d2+o<n2/2){
               j2+=m2[o];
            }
            if(f2+o<n2/2){
               k2+=m2[o];
            }
        }
    if(k2>=j2&&k2>=h2){
        cout<<k2;
    }
    if(h2>=j2&&h2>=j2){
        cout<<h2;
    }
    if(j2>=k2&&j2>=h2){
        cout<<j2;
    }

	return 0;
	fclose(stdin);
	fclose(stdout);
}
