#include<bits/stdc++.h>
using namespace std;
int t;
long long n,d[100005],a[100005],b[100005],c[100005],t1,t2,t3,maxx=0,sum=0,ans1,ans2,ans3,ans4,mc,da;
int main()
{
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>t;
	for(int i=1;i<=t;i++)
	{
		memset(d,0,sizeof(d));
		cin>>n;
		sum=0;
		t1=0,t2=0,t3=0;
		for(int j=1;j<=n;j++)
		{
			cin>>a[j]>>b[j]>>c[j];
		}
		for(int j=1;j<=n;j++)
		{
			maxx=max(max(a[j],b[j]),c[j]);
			if(maxx==a[j]&&t1<n/2)
			{
				t1++;
				d[j]=1;
				continue;
			}
			if(maxx==b[j]&&t2<n/2)
			{
				t2++;
				d[j]=2;
				continue;
			}
			if(maxx==c[j]&&t3<n/2)
			{
				t3++;
				d[j]=3;
				continue;
			}
				if(maxx==a[j])
				{
					for(int k=j-1;k>=1;k--)
					{
						if(d[k]==1)
						{
								da=max(max(a[j]+b[k],a[j]+c[k]),max(b[j]+a[k],c[j]+a[k]));	
								if(da==a[j]+b[k])	
								{
									d[j]=1;
									d[k]=2;
									t2++;
								}
								if(da==a[j]+c[k])
								{
									d[j]=1;
									d[k]=3;
									t3++;
								}
								if(da==b[j]&&d[j]==0)
								{
									d[j]=2;
									t2++;
								}
								if(da==c[j]&&d[j]==0)
								{
									d[j]=3;
									t3++;
								}	
						}	
					}
				}
				if(maxx==b[j])
				{
					for(int k=j-1;k>=1;k--)
					{
						if(d[k]==2)
						{
								da=max(max(b[j]+a[k],b[j]+c[k]),max(a[j]+b[k],c[j]+b[k]));	
								if(da==b[j]+a[k])	
								{
									d[j]=2;
									d[k]=1;
									t1++;
								}
								if(da==b[j]+c[k])
								{
									d[j]=2;
									d[k]=3;
									t3++;
								}
								if(da==a[j]&&d[j]==0)
								{
									d[j]=1;
									t1++;
								}
								if(da==c[j]&&d[j]==0)
								{
									d[j]=3;
									t3++;
								}	
						}	
					}
				}
				if(maxx==c[j])
				{
					for(int k=j-1;k>=1;k--)
					{
						if(d[k]==3)
						{
								da=max(max(c[j]+a[k],c[j]+b[k]),max(a[j]+c[k],b[j]+c[k]));	
								if(da==c[j]+a[k])	
								{
									d[j]=3;
									d[k]=1;
									t1++;
								}
								if(da==c[j]+b[k])
								{
									d[j]=3;
									d[k]=2;
									t2++;
								}
								if(da==a[j]&&d[j]==0)
								{
									d[j]=1;
									t1++;
								}
								if(da==b[j]&&d[j]==0)
								{
									d[j]=2;
									t2++;
								}	
						}	
					}
				}
			}
		for(int k=1;k<=n;k++)
		{
			if(d[k]==1)
			{
				sum=sum+a[k];
			}
			if(d[k]==2)
			{
				sum=sum+b[k];
			}
			if(d[k]==3)
			{
				sum=sum+c[k];
			}
		}
	cout<<sum<<endl;
	}
	return 0;
 } 
