#include<bits/stdc++.h>
using namespace std;
int n;
int p[5000];
long long res;
int main(){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin>>n;
	for(int i=0;i<n;i++)cin>>p[i];
	//3
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
		if(p[a]+p[b]>p[c])res++;
	//4	
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
		if(p[a]+p[b]+p[c]>p[d])res++;
	//5	
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
		if(p[a]+p[b]+p[c]+p[d]>p[e])res++;
	//6	
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]>p[f])res++;
	//7	
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]>p[g])res++;
	//8
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]>p[h])res++;
	//9
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]>p[i])res++;
	//10
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]>p[j])res++;
	//11
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]>p[k])res++;
	//12
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]>p[l])res++;
	//13
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]>p[m])res++;
	//14
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
	for(int o=m+1;o<n;o++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]+p[m]>p[o])res++;
	//15
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
	for(int o=m+1;o<n;o++)
	for(int q=o+1;q<n;q++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]+p[m]+p[o]>p[q])res++;
	//16
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
	for(int o=m+1;o<n;o++)
	for(int q=o+1;q<n;q++)
	for(int r=q+1;r<n;r++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]+p[m]+p[o]+p[q]>p[r])res++;
	//17
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
	for(int o=m+1;o<n;o++)
	for(int q=o+1;q<n;q++)
	for(int r=q+1;r<n;r++)
	for(int s=r+1;s<n;s++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]+p[m]+p[o]+p[q]+p[r]>p[s])res++;
	//18
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
	for(int o=m+1;o<n;o++)
	for(int q=o+1;q<n;q++)
	for(int r=q+1;r<n;r++)
	for(int s=r+1;s<n;s++)
	for(int t=s+1;t<n;t++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]+p[m]+p[o]+p[q]+p[r]+p[s]>p[t])res++;
	//19
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
	for(int o=m+1;o<n;o++)
	for(int q=o+1;q<n;q++)
	for(int r=q+1;r<n;r++)
	for(int s=r+1;s<n;s++)
	for(int t=s+1;t<n;t++)
	for(int u=t+1;u<n;u++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]+p[m]+p[o]+p[q]+p[r]+p[s]+p[t]>p[u])res++;
	//20
	for(int a=0;a<n;a++)
	for(int b=a+1;b<n;b++)
	for(int c=b+1;c<n;c++)
	for(int d=c+1;d<n;d++)
	for(int e=d+1;e<n;e++)
	for(int f=e+1;f<n;f++)
	for(int g=f+1;g<n;g++)
	for(int h=g+1;h<n;h++)
	for(int i=h+1;i<n;i++)
	for(int j=i+1;j<n;j++)
	for(int k=j+1;k<n;k++)
	for(int l=k+1;l<n;l++)
	for(int m=l+1;m<n;m++)
	for(int o=m+1;o<n;o++)
	for(int q=o+1;q<n;q++)
	for(int r=q+1;r<n;r++)
	for(int s=r+1;s<n;s++)
	for(int t=s+1;t<n;t++)
	for(int u=t+1;u<n;u++)
	for(int v=u+1;v<n;v++)
		if(p[a]+p[b]+p[c]+p[d]+p[e]+p[f]+p[g]+p[h]+p[i]+p[j]+p[k]+p[l]+p[m]+p[o]+p[q]+p[r]+p[s]+p[t]+p[u]>p[v])res++;
	cout<<res;
	return 0;
} 
