#include<iostream>
using namespace std;
int main()
{
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	int i,j,t,z,j1=0,j2=0,j3=0,l;
	cin>>t;
	int n[t+1],m[t+1];
	for(z=1;z<=t;z++){		
		cin>>n[z];
		l=n[t]/2;
		int a[n[z]+1][3+1];
	    for(i=1;i<=n[z];i++)
	    {
		    for(j=1;j<=3;j++)
		    {
		        cin>>a[i][j];
		    }
	    }
	    m[z]=0;
	    for(i=1;i<=n[z];i++)
	    {	    	
	    	if(a[i][1]>=a[i][2])
	    	{
	    		if(a[i][1]>=a[i][3])
	    		{
	    			if(j1<l){					
	    			 j1++;
	    			 m[z]+=a[i][1];}
	    			else					
	    			 if(a[i][3]>=a[i][2]&&j3<l){					 
	    			  j3++;
	    			  m[z]+=a[i][3];}
	    			 else
	    			  if(j2<l){					  
	    				j2++;
	    				m[z]+=a[i][2];}
	    			  else{					  
	    				j3++;
	    				m[z]+=a[i][3];}
				}
				else
				{
					if(j3<l){				
	    			    j3++;
	    			    m[z]+=a[i][3];}
	    			else
	    			    if(a[i][1]>=a[i][2]&&j1<l){						
	    				j1++;
	    				m[z]+=a[i][1];}
	    				else
	    				 if(j2<l){						 
	    				  j2++;
	    				  m[z]+=a[i][2];}
	    				 else{						 
	    				  j1++;
	    				  m[z]+=a[i][1];}
				}
			}
			else
			{
				if(a[z][2]>=a[i][3])
	    		{
	    			if(j2<l){					
	    			 j2++;
	    			 m[z]+=a[i][2];}
	    			else
	    			 if(a[z][3]>=a[i][1]&&j3<l){
	    			    j3++;
					    m[z]+=a[i][3];}	    			  
	    			 else
	    			  if(j1<l){
	    			  	j1++;
	    			  	m[z]+=a[i][1];
					  }	
	    			  else{
	    			  	j3++;
	    				m[z]+=a[i][3];}	    				
				}
				else
				{
					if(j3<l){					
	    			    j3++;
	    			    m[z]+=a[i][3];}
	    			else
	    			    if(a[i][1]>a[i][2]&&j1<l){
	    			    	j1++;
						    m[z]+=a[i][1];}	    			    	    				
	    				else
	    				 if(j2<l){
	    				 	j2++;
						    m[z]+=a[i][2];}	    				  
	    				 else{
	    				 	j1++;
						    m[z]+=a[i][1];}	    				  
	    	    }
			}
		}		
	}
	for(z=1;z<=t;z++) {
		cout<<m[z]<<"\n";}					
   	fclose(stdin);
	fclose(stdout);
	return 0;
 } 