#include<bits/stdc++.h>
using namespace std;
vector <int> vt1; 
vector <int> vt;
string s 
int main(){
	freopen("number.in","r",stdin);
	freopen("number.out","w",stdout);
	int n;
	
	if(s.size()==2){
			while(2){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}
		if(s.size()==1){
			while(1){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}
	if(s.size()==10){
			while(10){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}
	if(s.size()==3){
			while(3){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==4){
			while(4){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==5){
			while(5){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==6){
			while(6){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==7){
			while(7){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==8){
			while(8){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==9){
			while(9){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==11){
			while(11){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==12){
			while(12){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==13){
			while(13){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==14){
			while(14){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}if(s.size()==15){
			while(15){
		cin>>s;
		vt1.push_back(s);
		if(s>'0'||s<'9'){
			n=s-'0';
			vt.push_back(n);
		}
		}
	}
	for(int i=1;i<=vt.size()-1;i++){
		for(int j=vt.size();j>1;j--){
			int ans;
			if(vt[j]<vt[j-1]){
				ans=vt[j-1];
				vt[j-1]=vt[j];
				vt[j]=ans;
			}
		}
	}
	
	for(int i=1;i<=vt.size()-1;i++){
		cout<<vt[i];
	}
	
	return 0;
	fclose(stdin);
	fclose(stdout); 
}
