#include<bits/stdc++.h> 
using namespace std;
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	int m,n,x,y,z,a=0,club1[13000];
	cin>>m;
	club1[1]=0;
	club1[2]=0;
	club1[3]=0;
	for(int i=1;i<=m;i++){
		cin>>n;
		for(int j=1;j<=n;j++){
			cin>>x>>y>>z;
			if(x=y=z){
				club1[1]=club1[1]+1;
				a=a+x;
				if(club1[1]>(n/2)){
					club1[2]=club1[2]+1;
					a=a+y;
					if(club1[2]>(n/2)){
						club1[3]=club1[3]+1;
						a=a+z; 
					}
				}	
			}
			if(x>y>z){
				club1[1]=club1[1]+1;
				a=a+x;
				if(club1[1]>(n/2)){
					club1[2]=club1[2]+1;
					a=a+y;
					if(club1[2]>(n/2)){
						club1[3]=club1[3]+1;
						a=a+z; 
					}
				}	
			}
			if(x>z>y){
				club1[1]=club1[1]+1;
				a=a+x;
				if(club1[1]>(n/2)){
					club1[3]=club1[3]+1;
					a=a+y;
					if(club1[3]>(n/2)){
						club1[2]=club1[2]+1;
						a=a+z; 
					}
				}	
			}
			if(x>(y=z)){
				club1[1]=club1[1]+1;
				a=a+x;
				if(club1[1]>(n/2)){
					club1[2]=club1[2]+1;
					a=a+y;
					if(club1[2]>(n/2)){
						club1[3]=club1[3]+1;
						a=a+z; 
					}
				}	
			}
			if(x=y>z){
				club1[1]=club1[1]+1;
				a=a+x;
				if(club1[1]>(n/2)){
					club1[2]=club1[2]+1;
					a=a+y;
					if(club1[2]>(n/2)){
						club1[3]=club1[3]+1;
						a=a+z; 
					}
				}	
			}
			if(y>z>x){
				club1[2]=club1[2]+1;
				a=a+y;
				if(club1[2]>(n/2)){
					club1[3]=club1[3]+1;
					a=a+z;
					if(club1[3]>(n/2)){
						club1[1]=club1[1]+1;
						a=a+x; 
					}
				}
			}
			if(y>x>z){
				club1[2]=club1[2]+1;
				a=a+y;
				if(club1[2]>(n/2)){
					club1[1]=club1[1]+1;
					a=a+x;
					if(club1[1]>(n/2)){
						club1[3]=club1[3]+1;
						a=a+z; 
					}
				}	
			}
			if(y>(x=z)){
				club1[2]=club1[2]+1;
				a=a+y;
				if(club1[2]>(n/2)){
					club1[1]=club1[1]+1;
					a=a+x;
					if(club1[1]>(n/2)){
						club1[3]=club1[3]+1;
						a=a+z; 
					}
				}	
			}
			if(y=x>z){
				club1[2]=club1[2]+1;
				a=a+y;
				if(club1[2]>(n/2)){
					club1[1]=club1[1]+1;
					a=a+x;
					if(club1[1]>(n/2)){
						club1[3]=club1[3]+1;
						a=a+z; 
					}
				}	
			}
			if(z>x>y){
				club1[3]=club1[3]+1;
				a=a+z;
				if(club1[3]>(n/2)){
					club1[1]=club1[1]+1;
					a=a+x;
					if(club1[1]>(n/2)){
						club1[2]=club1[2]+1;
						a=a+y; 
					}
				}	
			}
			if(z>y>x){
				club1[3]=club1[3]+1;
				a=a+z;
				if(club1[3]>(n/2)){
					club1[2]=club1[2]+1;
					a=a+y;
					if(club1[2]>(n/2)){
						club1[1]=club1[1]+1;
						a=a+x; 
					}
				}	
			}
			if(z>(y=x)){
				club1[3]=club1[3]+1;
				a=a+z;
				if(club1[3]>(n/2)){
					club1[2]=club1[2]+1;
					a=a+y;
					if(club1[2]>(n/2)){
						club1[1]=club1[1]+1;
						a=a+x; 
					}
				}	
			}
			if(z=y>x){
				club1[3]=club1[3]+1;
				a=a+z;
				if(club1[3]>(n/2)){
					club1[2]=club1[2]+1;
					a=a+y;
					if(club1[2]>(n/2)){
						club1[1]=club1[1]+1;
						a=a+x; 
					}
				}	
			}
		}
		cout<<a<<endl;
		a=0;
		club1[1]=0;
		club1[2]=0;
		club1[3]=0; 
	}
	return 0;
}
