#include<bits/stdc++.h>
using namespace std;
int n,m,i,j,k,l,e[200001],s,sum;
char v;
string x,y,f,g,a[200001],b[200001],c[200001],d[200001];
int main()
{
	freopen("replace.in","r",stdin);
	freopen("replace.out","w",stdout);
	scanf("%d%d",&n,&m);
	for(i=1;i<=n;i++)
	{
		while((v=getchar())<97||v>122);
		while(v>=97&&v<=122)
		{
			a[i]+=v;
			v=getchar();
		}
		while((v=getchar())<97||v>122);
		while(v>=97&&v<=122)
		{
			b[i]+=v;
			v=getchar();
		}
		for(j=0;j<a[i].size();j++)
		   if(a[i][j]!=b[i][j])
		     break;
		s=e[i]=j;
		for(j=a[i].size()-1;j>=0;j--)
		   if(a[i][j]!=b[i][j])
		     break;
		sum=j;
		for(j=s;j<=sum;j++)
		   c[i]+=a[i][j];
		for(j=s;j<=sum;j++)
		   d[i]+=b[i][j];
	}
	for(i=1;i<=m;i++)
	{
		x=y=f=g="";
		while((v=getchar())<97||v>122);
		while(v>=97&&v<=122)
		{
			x+=v;
			v=getchar();
		}
		while((v=getchar())<97||v>122);
		while(v>=97&&v<=122)
		{
			y+=v;
			v=getchar();
		}
		if(x.size()!=y.size())
		{
			printf("0\n");
			continue;
		}
		for(j=0;j<x.size();j++)
		   if(x[j]!=y[j])
		     break;
		s=j;
		for(j=x.size()-1;j>=0;j--)
		   if(x[j]!=y[j])
		     break;
		sum=j;
		for(j=s;j<=sum;j++)
		   f+=x[j];
		for(j=s;j<=sum;j++)
		   g+=y[j];
		sum=0;
		for(j=1;j<=n;j++)
		   if(c[j]==f&&d[j]==g&&s>=e[j]&&s-e[j]+a[j].size()<=x.size())
		   {
		   	for(k=s-e[j],l=0;l<a[j].size();k++,l++)
		   	   if(x[k]!=a[j][l]||y[k]!=b[j][l])
		   	     break;
		   	if(l>=a[j].size())
		   	  sum++;
		   }
		printf("%d\n",sum);
	}
	return 0;
}
