#include<bits/stdc++.h>
using namespace std;
string s;
int a,b,c,d,e,f,g,h,j,k,o;
int main(){
	freopen("number.in","r",stdin);
	freopen("number.out","w",stdout);
	cin>>s;
	a=s.size();
	for(int i=0;i<a;i++){
		if(s[i]=='0')o++;
		if(s[i]=='1')b++;
		if(s[i]=='2')c++;
		if(s[i]=='3')d++;
		if(s[i]=='4')e++;
		if(s[i]=='5')f++;
		if(s[i]=='6')g++;
		if(s[i]=='7')h++;
		if(s[i]=='8')j++;
		if(s[i]=='9')k++;
	}
	while(k>0||j>0||h>0||g>0||f>0||e>0||d>0||c>0||b>0||o>0){
		if(k>0){
			cout<<9;
			k--;
			continue; 
		}
		if(j>0){
			cout<<8;
			j--;
			continue; 
		}
		if(h>0){
			cout<<7;
			h--;
			continue; 
		}
		if(g>0){
			cout<<6;
			g--;
			continue; 
		}
		if(f>0){
			cout<<5;
			f--;
			continue; 
		}
		if(e>0){
			cout<<4;
			e--;
			continue; 
		}
		if(d>0){
			cout<<3;
			d--;
			continue; 
		}
		if(c>0){
			cout<<2;
			c--;
			continue; 
		}
		if(b>0){
			cout<<1;
			b--;
			continue; 
		}
		if(o>0){
		    cout<<0;
		    o--;
	    }
	}
	fclose(stdin);
	fclose(stdout);
	return 0;
} 
