#include<bits/stdc++.h>
using namespace std;
int a[1005][1005],b[1005][1005],b1=0,b2=0,b3=0,s=0,smax=0;
int main()
{
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	int n,t,i=0,j=0,la=0,lb=0,h=0,c=1,d=0,m,k,x=0;
	cin>>t;
	while(t--)
	{
		cin>>n;
		for(i=1;i<=n;i++)
		for(j=1;j<=3;j++)
		{
		    cin>>a[i][j];
		    b[i][j]=j;
		}
		for(i=1;i<=n;i++)
		for(j=1;j<=3;j++)
		for(h=1;h<=3;h++)
		if(a[i][j]>a[i][h])
		{
			la=a[i][j];
			a[i][j]=a[i][h];
			a[i][h]=la;
			lb=b[i][j];
			b[i][j]=b[i][h];
			b[i][h]=lb;
		}
		m=pow(3,n);i=1;j=1;h=2;k=1;
		while(m--)
		{
			if(c%2!=0)
			{
			s+=a[i][j];
			if(b[i][j]==1)
		    b1+=b[i][j];
		    if(b[i][j]==2)
		    b2+=b[i][j];
		    if(b[i][j]==3)
		    b3+=b[i][j];
		    if(i<n)
		    i+=2;
		    if(d!=0&&d!=-1)
		    j++;
		    }
		    else
		    {
		    	s+=a[h][k];
		    	if(b[h][k]==1)
		        b1+=b[h][k];
		        if(b[h][k]==2)
		        b2+=b[h][k];
		        if(b[h][k]==3)
		        b3+=b[h][k];
		        if(j<=n)
				h+=2;
		        if(d!=2&&d!=0)
		        k++;
			}
			c++;
			d++;
			if(d%n==0)
			{
			if(smax<s&&b1<=n/2&&b2<=n&&b3<=n/2*3)
			smax=s;
			b1=0;b2=0;b3=0;s=0;i=1;h=2;k=1;d=-1;
		    }
		}
		cout<<smax<<endl;
	    for(i=1;i<=n;i++)
		for(j=1;j<=3;j++)
		{
		    a[i][j]=0;
		    b[i][j]=j;
		}
		b1=0;b2=0;b3=0;s=0;smax=0;c=1;d=0;i=1;j=1;h=2;k=1;
	}
	return 0;
 } 
