#include<bits/stdc++.h>
using namespace std;
int main(){
	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;
		srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;	srand(static_cast<unsigned>time(0))
	int n=rand()%10;
	cout<<n;
} 
