#include<bits/stdc++.h>
using namespace std;
long long n,k,arr1[1000000],arr[1000000],a,b;
int main(){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin>>n;
	for(int i=1;i<=n;i++){
		cin>>arr1[i];
	}
	sort(arr1+1,arr1+n+1);
	for(int i=n;i>=1;i--){
		arr[i]=arr1[n-i+1];
	}
	if(n==2){
		cout<<'0';
		return 0;
	}
	a=arr[1]+arr[2]+arr[3];
	if(n==3){
		if(arr[1]*2<n){
			cout<<'1';
			return 0;
		}else{
		cout<<'0';
		return 0;
		}
	}
	if(n==4){
		if(arr[1]*2<arr[1]+arr[2]+arr[3]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]){
			k++;
		}
		cout<<k;
		return 0;
	}
	if(n==5){
		if(arr[1]*2<arr[1]+arr[2]+arr[3]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[5]+arr[4]+arr[3]+arr[2]+arr[1]){
			k++;
		}
		cout<<k;
		return 0;
	}	
	if(n==6){
		if(arr[1]*2<arr[1]+arr[2]+arr[3]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[5]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[4]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[4]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[5]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[5]+arr[6]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[4]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[5]+arr[6]){
			k++;
		}
		cout<<k;
		return 0;
	}
		if(n==7){
		if(arr[1]*2<arr[1]+arr[2]+arr[3]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[5]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[6]+arr[7]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[7]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[4]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[4]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[4]+arr[7]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[5]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[5]+arr[7]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[6]+arr[7]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[4]+arr[5]){
			k++;
		}	
		if(arr[3]*2<arr[3]+arr[4]+arr[6]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[4]+arr[7]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[5]+arr[6]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[5]+arr[7]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[6]+arr[7]){
			k++;
		}
		if(arr[4]*2<arr[4]+arr[5]+arr[6]){
			k++;
		}
		if(arr[4]*2<arr[4]+arr[5]+arr[7]){
			k++;
		}
		if(arr[4]*2<arr[4]+arr[6]+arr[7]){
			k++;
		}
		if(arr[5]*2<arr[5]+arr[6]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[4]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[5]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[6]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[4]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[5]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[3]+arr[6]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[5]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[4]+arr[6]+arr[7]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[4]+arr[7]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[5]+arr[6]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[5]+arr[7]){
			k++;
		}
		if(arr[2]*2<arr[2]+arr[3]+arr[6]+arr[7]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[4]+arr[5]+arr[6]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[4]+arr[5]+arr[7]){
			k++;
		}
		if(arr[3]*2<arr[3]+arr[4]+arr[6]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[5]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[5]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[6]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[5]+arr[6]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[5]+arr[7]){
			k++;
		}
		if(arr[1]*2<arr[1]+arr[2]+arr[3]+arr[4]+arr[6]+arr[7]){
			k++;
		}
		cout<<k;
		return 0;
	}
	return 0;
}
