#include<bits/stdc++.h>
** DO NOT EDIT THIS FILE.
** If you make changes to this file while any VirtualBox related application
** is running, your changes will be overwritten later, without taking effect.
** Use VBoxManage or the VirtualBox Manager GUI to make changes.
 -->
<VirtualBox xmlns="http://www.virtualbox.org/" version="1.12-windows">
<Global>
<ExtraData>
<ExtraDataItem name="GUI/Details/Elements" value="general,system,preview,display,storage,audio,network,usb,sharedFolders,description"/>
<ExtraDataItem name="GUI/GroupDefinitions/" value="n=GLOBAL,m=b88b538e-55d0-4049-aac9-15fa47f09875"/>
<ExtraDataItem name="GUI/LastItemSelected" value="m=NOI2.0"/>
<ExtraDataItem name="GUI/LastWindowPosition" value="641,256,960,520"/>
<ExtraDataItem name="GUI/SplitterSizes" value="317,642"/>
<ExtraDataItem name="GUI/Tools/LastItemsSelected" value="Welcome,Details"/>
<ExtraDataItem name="GUI/UpdateCheckCount" value="3"/>
<ExtraDataItem name="GUI/UpdateDate" value="1 d, 2025-10-31, stable, 6.1.26"/>
</ExtraData>
<MachineRegistry>
<MachineEntry uuid="{b88b538e-55d0-4049-aac9-15fa47f09875}" src="C:\Users\admin\VirtualBox VMs\NOI2.0\NOI2.0.vbox"/>
</MachineRegistry>
<NetserviceRegistry>
<DHCPServers>
<DHCPServer networkName="HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter" IPAddress="192.168.56.100" networkMask="255.255.255.0" lowerIP="192.168.56.101" upperIP="192.168.56.254" enabled="1"/>
</DHCPServers>
</NetserviceRegistry>
<SystemProperties defaultMachineFolder="C:\Users\admin\VirtualBox VMs" defaultHardDiskFormat="VDI" VRDEAuthLibrary="VBoxAuth" webServiceAuthLibrary="VBoxAuth" LogHistoryCount="3" proxyMode="0" exclusiveHwVirt="false"/>
<USBDeviceFilters/>
</Global>
</VirtualBox>
