#include<bits/stdc++.h>
using namespace std;
const int N=1e5+10;
long long  s,t,n,a[N],b[N],c[N],a1,b1,c1,a2,b2,c2,c3,sum[N],ans,l,k=0,Mzb1,Mzb2,Mzb3,egg,linfan; 
int main()
{
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>t;
	while(t--)
	{
		cin>>n;
		for(int i=1;i<=n;i++)
		{
			cin>>a[i]>>b[i]>>c[i];
			sum[i]=a[i]+b[i]+c[i];
		}
		if(n==2)
		{
			s=max(a[1]+b[2],a[1]+c[2]);
			s=max(s,max(b[1]+a[2],b[1]+c[2]));
			s=max(s,max(c[1]+a[2],c[1]+b[2]));
			cout<<s<<endl;
			continue;
		}
		for(int i=1;i<=n;i++)
		{
			for(int j=1;j<=n;j++)
			{
				ans=k;
				if(sum[j]==0)
				{
					continue;
				}
				k=max(k,sum[j]);
				if(ans!=k)
				{
					l=j;	
				}
			}
			sum[l]=0;
			k=0;
			b1=b[l];
			a1=max(a[l],b[l]);
			if(a1!=b1)
			{
				c1=1;
				b1=a[l];
				a1=max(b1,c[l]);
				if(a1!=b1)
				{
					c1=3;
					c2=1;
					c3=2;
				}
				else
				{
					b1=b[l];
					a1=max(b[l],c[l]);
					if(b1!=a1)
					{
						c2=3;
						c3=2;
					}else
					{
						c2=2;
						c3=3;
					}
				}
			}
			else
			{
				c1=2;
				a1=max(b1,c[l]);
				if(a1!=b1)
				{
					c1=3;
					c2=2;
					c3=1;
				}
				else
				{
					b1=a[l];
					a1=max(a[l],c[l]);
					if(b1!=a1)
					{
						c2=3;
						c3=1;
					}else
					{
						c2=1;
						c3=3;
					}
				}
			}
			if(Mzb1<n/2&&c1==1)
			{
				egg+=a[l];
				Mzb1++;
				linfan++;
			}
			else
			if(Mzb2<n/2&&c1==2)
			{
				egg+=b[l];
				Mzb2++;
				linfan++; 
			}
			else
			if(Mzb3<n/2&&c1==3)
			{
				egg+=c[l];
				Mzb3++; 
				linfan++; 
			}
			if(Mzb1<n/2&&c2==1&&linfan<=0)
			{
				egg+=a[l];
				Mzb1++;
				linfan++;
			}
			else
			if(Mzb2<n/2&&c2==2&&linfan<=0)
			{
				egg+=b[l];
				Mzb2++;
				linfan++;
			}
			else
			if(Mzb3<n/2&&c2==3&&linfan<=0)
			{
				egg+=c[l];
				Mzb3++;
				linfan++;
			}
			if(Mzb1<n/2&&c3==1&&linfan<=0)
			{
				egg+=a[l];
				Mzb1++;
				linfan++;
			}
			else
			if(Mzb2<n/2&&c3==2&&linfan<=0)
			{
				egg+=b[l];
				Mzb2++;
				linfan++;
			}
			else
			if(Mzb3<n/2&&c3==3&&linfan<=0)
			{
				egg+=c[l];
				Mzb3++;
				linfan++;
			}
			linfan=0;
		}
		cout<<egg<<endl;
		egg=0;
		k=0;
		linfan=0;Mzb1=Mzb2=Mzb3=0;
	}
	return 0;
}//Ren5Jie4Di4Ling5%
