#include<bits/stdc++.h>
using namespace std;
long long t,n,a[100005][3],s,ss,b[100005];
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>t;
	for(int l=1;l<=t;l++){
		cin>>n;
		if(n<=300){
			for(int i=1;i<=n;i++){
				cin>>a[i][0]>>a[i][1]>>a[i][2];
			}
			int a1=0,a2=0,a3=0;
			for(int i=1;i<=n;i++){
				if(a[i][0]>a[i][1]){
					if(a[i][0]>a[i][2]){
						if(a1<n/2){
							a1++;
							s+=a[i][0];
						}
						else{
							if(a[i][2]>a[i][1]){
								a3++;
								s+=a[i][2];
							}
							else{
								a2++;
								s+=a[i][1];
							}
						}
					}
					if(a[i][0]<a[i][2]){
						if(a3<n/2){
							a3++;
							s+=a[i][2];
						}
						else{
							if(a[i][0]>a[i][1]){
								a1++;
								s+=a[i][0];
							}
							else{
								a2++;
								s+=a[i][1];
							}
						}
					}
				}
				else{
					if(a[i][1]>a[i][2]){
						if(a2<n/2){
							a2++;
							s+=a[i][1];
						}
						else{
							if(a[i][2]>a[i][0]){
								a3++;
								s+=a[i][2];
							}
							else{
								a1++;
								s+=a[i][0];
							}
						}
					}
					if(a[i][1]<a[i][2]){
						if(a3<n/2){
							a3++;
							s+=a[i][2];
						}
						else{
							if(a[i][0]>a[i][1]){
								a1++;
								s+=a[i][0];
							}
							else{
								a2++;
								s+=a[i][1];
							}
						}
					}
				}
			}
			a1=0;
			a2=0;
			a3=0;
			for(int i=n;i>=1;i--){
				if(a[i][0]>a[i][1]){
					if(a[i][0]>a[i][2]){
						if(a1<n/2){
							a1++;
							ss+=a[i][0];
						}
						else{
							if(a[i][2]>a[i][1]){
								a3++;
								ss+=a[i][2];
							}
							else{
								a2++;
								ss+=a[i][1];
							}
						}
					}
					if(a[i][0]<a[i][2]){
						if(a3<n/2){
							a3++;
							ss+=a[i][2];
						}
						else{
							if(a[i][0]>a[i][1]){
								a1++;
								ss+=a[i][0];
							}
							else{
								a2++;
								ss+=a[i][1];
							}
						}
					}
				}
				else{
					if(a[i][1]>a[i][2]){
						if(a2<n/2){
							a2++;
							ss+=a[i][1];
						}
						else{
							if(a[i][2]>a[i][0]){
								a3++;
								ss+=a[i][2];
							}
							else{
								a1++;
								ss+=a[i][0];
							}
						}
					}
					if(a[i][1]<a[i][2]){
						if(a3<n/2){
							a3++;
							ss+=a[i][2];
						}
						else{
							if(a[i][0]>a[i][1]){
								a1++;
								ss+=a[i][0];
							}
							else{
								a2++;
								ss+=a[i][1];
							}
						}
					}
				}
			}
			cout<<max(ss,s)<<endl;
			s=0;ss=0;
		}
		else{
			for(int i=1;i<=n;i++){
				cin>>b[i]>>ss>>ss;
			}
			sort(b+1,b+n+1);
			for(int i=n;i>n/2;i--){
				s+=b[i];
			}
		}	
	}
	return 0;
}
