#include<iostream>
using namespace std;
int main(){
	freopen("rode.in","r",stdin);
	freopen("rode.out","w",stdout);
	cout<<0;
	//rp++//rp++
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++
	//rp++//rp++
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++ 
	//rp++//rp++
	return 0;
}

