#include<bits/stdc++.h>
using namespace std;
int main(){
	//I like CCF I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF Æ­ÄãµÄ ÎûÎûFUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF //FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	int n;
	cin>>n;
	int k;
	int a[100005];
	for(int i=1;i<=n;i++){
		cin>>a[i];
	}
	cout<<(n-2+1)*(n-2)/2;
	fclose(stdin);
	fclose(stdout);
	return 0;
}


















































//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF

//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
