#include<iostream>
#include<algorthem>
using namespace std;
int main(){
	hkhfdkjhlkfdshksfdhkfdhkjdfhkjhfkjdhjgdfh;
	djshkljdshjksldfhlkjfdhglkdjfhgkjghflkdshglkh;
	dsjfhglkhlkashlkhglkdfshlkjfdhgklgfhklgfhkdfjhgkdlhgdkljshgkldjhgdlkjhgkdjfhgjkgfhdlkhgflkdjfhgkldhgdlkghfkdlhgdlkjsghdlkghkjhjgflkdhdsklhkfhgkdjfghkghdkfghfkjdhkfdljhkljhhkdsajfhlkjdshkdjfhakfdshksjdhfkldsfhlkdsfhkfdshfdskhfskhfkhfdkhfdllhldslkjdsfhflkfhdlkshflkshfdlksjhfklshfklsjdfhklhfksljhfdalkjshfdsalkjfdhlkashfdksaljdhflksjhflkshfdklhfklhfdsalkjhfdjkhlksafhkfdlhjdfkshfdkjdfhlkjfdahdkjlhfsalkjhflkhfdshfskljfhkjfdhkjdlfhdslkhflkjhfdlkjhfdlkjhfdjhalkfdshlskfdjklfhfdlkhafkjhfdlkdhfskdaj;
	l;dsafjl;sdj;ljdsfl;jdafsdskds;fjhdsjlkd;fjds;lkjfdalk;jadfsl;kjfd;sadflkjfds;jkfdkj;dsfkjds;kld;sfjakl;jfkld;sajfklfjdlkfjlkafdjslkadjlkdsfjlk;dfjldskjldskjldskjfalkjfslkjslkdajals;dj;lsdajd;lskjdsl;jflds;akjdfls;kjdsalk;js;
	return 0;
}
