//GD-J02018 -> GD-S01854
//rp++
//i still didnt get an chinese shu ru fa....

#include<bits/stdc++.h>
using namespace std;
/*struct Segtree{
	int l,r;
	int num;
	
}tree[114514];
int query(int x,int l,int r){
	if(l <= x.l && r >= x.r ){
		return x.num ;
	}
	
}*/
struct per{
	int a,b,c;
	
}a[100005];
int n,t;
int al,bl,cl,cn,ans;
void dfs(int x){
	if(x > n){
		ans = max(ans,cn);
	}
	
	else{
		if(al){
			al -= 1;
			cn += a[x].a;
			dfs(x+1);
			cn -= a[x].a;
			al += 1;
		}
		if(bl){
			bl -= 1;
			cn += a[x].b;
			dfs(x+1);
			cn -= a[x].b;
			bl += 1;
		}
		if(cl){
			cl -= 1;
			cn += a[x].c;
			dfs(x+1);
			cn -= a[x].c;
			cl += 1;
		}
		
	}
	return;
}
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>t;
	for(int i = 1;i <= t;i ++){
		cin>>n;
		for(int i = 1;i <= n;i ++){
			cin>>a[i].a>>a[i].b>>a[i].c;
			
		}
		al = n/2;bl = n/2;cl = n/2;
		dfs(1);
		cout<<ans<<endl;
	}
	
}
/*
	why is this so hard?????
	its much harder than last year's duel that can be steal 100pts
	is im more vegetable or the people making Ts are more nasty?
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYW/       WHYW YWHYWHY HYWH          WHY HY    HYWHYWHYWHYWH       WHYWH       WHYW       YWHYWHYWHY   W   HYWHYW     WHYWHY   W   HYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHY  YWHYWHYWHYW YWHYWHY HYWH WHYWHYWHYWHY H  HYWHYWHYWHYWHYWH WHYWHYWHYWH WHYWHYWHYW YWHYWHYWHYWHYWH WHY HYW YWHY HYWHY HYWH WHY HYW YWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYW        WHYW YWHYWHY HYWH WHYWHYWHYWHY  YWHYWHYWHYWHYWHYWH WHYWHYWHYWH WHYWHYWHYW       YWHYWHYWH WHY HYW YWHY HYWHY HYWH WHY HYW YWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYW YWHYWHYWHYW YWHYWHY HYWH WHYWHYWHYWHY H  HYWHYWHYWHYWHYWH WHYWHYWHYWH WHYWHYWHYW YWHYWHYWHYWHYWH WHY HYW YWHY HYWHY HYWH WHY HYW YWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYW YWHYWHYWHYW YWHYWHY HYWH WHYWHYWHYWHY HY  YWHYWHYWHYWHYWH WHYWHYWHYWH WHYWHYWHYW YWHYWHYWHYWHYWH WHY HYW YWHY HYWHY HYWH WHY HYW YWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYW YWHYWHYWHYWH       WHYWH         YWHY HYWH  YWHYWHYWHYWHY       HYWHY       HYWH WHYWHYWHYWHYWHY HYWHYWH WHYWH     HYWHY HYWHYWH WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYH
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	WHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHYWHY
	i already chu er and still cant get past it
	i guest this is a green 
	if it wasnt and i still can get it over ,i can AFO(
	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa qi si wo le!!!!!!!!!!!!!!!!!!!
	struct Segtree{
	遗憾离场，来年再见
	（我下次一定要仔细搞图论，主要整的线段树和dp不考）
	CCF 密码 
		
*/

