#include<bits/stdc++.h>
using namespace std;
int nn,ans=0;
int aaa[50005],bbb[50005];
int js(int bi,int zs){
	int num=zs,sum=1;
	for(int h=1;h<=bi;h++){
		sum*=num;
		num--;
	}
	return sum;
}
int main(void){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin>>nn;
	for(int i=1;i<=nn;i++){
		cin>>aaa[i];
	}
	sort(aaa+1,aaa+1+nn);
	for(int i=1;i<=nn;i++){
		bbb[i]=bbb[i-1]+aaa[i];
	}
	/*
	for(int i=1;i<=nn;i++){
		cout<<bbb[i]<<" ";
	}
	int sc=0,maxn=0;
	for(int b=3;b<=nn;b++){
		for(int i=b;i<=nn-b+1;i++){
			sc=i-b;
			
		}
	}
	*/
	if(nn<3){
		cout<<0;
		return 0;
	}
	if(nn==3){
		if(bbb[3]>aaa[3]*2){
			cout<<1;
			return 0;
		}else{
			cout<<0;
			return 0;
		}
	}
	if(nn==4){
		if(bbb[4]-aaa[1]>aaa[4]*2){
			ans++;
		}
		if(bbb[4]-aaa[2]>aaa[4]*2){
			ans++;
		}
		if(bbb[4]-aaa[3]>aaa[4]*2){
			ans++;
		}
		if(bbb[4]-aaa[4]>aaa[3]*2){
			ans++;
		}
		if(bbb[4]>aaa[4]*2){
			ans++;
		}
		cout<<ans;
	}
	if(nn==5){
		if(bbb[5]-aaa[1]-aaa[2]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[1]-aaa[3]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[1]-aaa[4]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[1]-aaa[5]>aaa[4]*2){
			ans++;
		}
		if(bbb[5]-aaa[2]-aaa[3]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[2]-aaa[4]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[2]-aaa[5]>aaa[4]*2){
			ans++;
		}
		if(bbb[5]-aaa[3]-aaa[4]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[3]-aaa[5]>aaa[4]*2){
			ans++;
		}
		if(bbb[5]-aaa[4]-aaa[5]>aaa[3]*2){
			ans++;
		}
		if(bbb[5]-aaa[1]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[2]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[3]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[4]>aaa[5]*2){
			ans++;
		}
		if(bbb[5]-aaa[5]>aaa[4]*2){
			ans++;
		}
		if(bbb[5]>aaa[5]*2){
			ans++;
		}
		cout<<ans;
	}
	if(nn==6){
		if(bbb[6]-aaa[1]-aaa[2]-aaa[3]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[2]-aaa[4]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[2]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[2]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[3]-aaa[4]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[3]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[3]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[4]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[4]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[5]-aaa[6]>aaa[4]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[3]-aaa[4]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[3]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[3]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[4]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[4]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[5]-aaa[6]>aaa[4]*2){
			ans++;
		}
		if(bbb[6]-aaa[3]-aaa[4]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[3]-aaa[4]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[3]-aaa[5]-aaa[6]>aaa[4]*2){
			ans++;
		}
		if(bbb[6]-aaa[4]-aaa[5]-aaa[6]>aaa[3]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[2]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[3]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[4]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[3]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[4]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[3]-aaa[4]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[3]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[3]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[4]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[4]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]-aaa[5]-aaa[6]>aaa[4]*2){
			ans++;
		}
		if(bbb[6]-aaa[1]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[2]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[3]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[4]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[5]>aaa[6]*2){
			ans++;
		}
		if(bbb[6]-aaa[6]>aaa[5]*2){
			ans++;
		}
		if(bbb[6]>aaa[6]*2){
			ans++;
		}
		cout<<ans;
	}
	if(nn==7){
		if(bbb[7]-aaa[1]-aaa[2]-aaa[3]-aaa[4]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[3]-aaa[5]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[3]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[3]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[4]-aaa[5]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[4]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[4]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[2]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[3]-aaa[4]-aaa[5]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[3]-aaa[4]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[3]-aaa[4]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[3]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[3]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[3]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[4]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[4]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[1]-aaa[5]-aaa[6]-aaa[7]>aaa[4]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[3]-aaa[4]-aaa[5]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[3]-aaa[4]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[3]-aaa[4]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[3]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[3]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[3]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[4]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[4]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[4]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		} 
		if(bbb[7]-aaa[2]-aaa[5]-aaa[6]-aaa[7]>aaa[4]*2){
			ans++;
		} 
		if(bbb[7]-aaa[3]-aaa[4]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		} 
		if(bbb[7]-aaa[3]-aaa[4]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		} 
		if(bbb[7]-aaa[3]-aaa[4]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		} 
		if(bbb[7]-aaa[3]-aaa[5]-aaa[6]-aaa[7]>aaa[4]*2){
			ans++;
		} 
		if(bbb[7]-aaa[4]-aaa[5]-aaa[6]-aaa[7]>aaa[3]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[2]-aaa[3]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[2]-aaa[4]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[2]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[2]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[2]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[3]-aaa[4]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[3]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[3]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[3]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[4]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[4]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[4]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[3]-aaa[4]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[3]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[3]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[3]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[4]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[4]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[4]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[4]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[4]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[4]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		}
		if(bbb[7]-aaa[4]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[4]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[4]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		}
		if(bbb[7]-aaa[5]-aaa[6]-aaa[7]>aaa[4]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[2]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[3]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[4]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[3]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[4]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[4]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[4]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[4]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[4]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[5]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[5]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]-aaa[6]-aaa[7]>aaa[5]*2){
			ans++;
		}
		if(bbb[7]-aaa[1]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[2]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[3]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[4]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[5]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[6]>aaa[7]*2){
			ans++;
		}
		if(bbb[7]-aaa[7]>aaa[6]*2){
			ans++;
		}
		if(bbb[7]>aaa[7]*2){
			ans++;
		}
		cout<<ans;
	}
	return 0;
} 
