#include<iostream>
#include<algorithm>
using namespace std;
int n;
long long sum;
int a[5005];
int main(){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	scanf("%d",&n);
	for(int i=1;i<=n;i++)
		scanf("%d",&a[i]);
	sort(a+1,a+n+1);
	if(n<=20){
		if(n>=3)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			if(a[i]+a[j]>a[k]) sum++;
		if(n>=4)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			if(a[i]+a[j]+a[k]>a[l]) sum++;
		if(n>=5)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			if(a[i]+a[j]+a[k]+a[l]>a[m]) sum++;
		if(n>=6)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]>a[b]) sum++;
		if(n>=7)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]>a[c]) sum++;
		if(n>=8)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]>a[d]) sum++;
		if(n>=9)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]>a[e]) sum++;
		if(n>=10)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]>a[f]) sum++;
		if(n>=11)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]>a[g]) sum++;
		if(n>=12)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]>a[h]) sum++;
		if(n>=13)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]>a[o]) sum++;
		if(n>=14)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			for(int p=o+1;p<=n;p++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]+a[o]>a[p]) sum++;
		if(n>=15)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			for(int p=o+1;p<=n;p++)
			for(int q=p+1;q<=n;q++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]+a[o]+a[p]>a[q]) sum++;
		if(n>=16)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			for(int p=o+1;p<=n;p++)
			for(int q=p+1;q<=n;q++)
			for(int r=q+1;r<=n;r++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]+a[o]+a[p]+a[q]>a[r]) sum++;
		if(n>=17)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			for(int p=o+1;p<=n;p++)
			for(int q=p+1;q<=n;q++)
			for(int r=q+1;r<=n;r++)
			for(int s=r+1;s<=n;s++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]+a[o]+a[p]+a[q]+a[r]>a[s]) sum++;
		if(n>=18)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			for(int p=o+1;p<=n;p++)
			for(int q=p+1;q<=n;q++)
			for(int r=q+1;r<=n;r++)
			for(int s=r+1;s<=n;s++)
			for(int t=s+1;t<=n;t++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]+a[o]+a[p]+a[q]+a[r]+a[s]>a[t]) sum++;
		if(n>=19)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			for(int p=o+1;p<=n;p++)
			for(int q=p+1;q<=n;q++)
			for(int r=q+1;r<=n;r++)
			for(int s=r+1;s<=n;s++)
			for(int t=s+1;t<=n;t++)
			for(int u=t+1;u<=n;u++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]>a[u]) sum++;
		if(n>=20)
			for(int i=1;i<=n;i++)
			for(int j=i+1;j<=n;j++)
			for(int k=j+1;k<=n;k++)
			for(int l=k+1;l<=n;l++)
			for(int m=l+1;m<=n;m++)
			for(int b=m+1;b<=n;b++)
			for(int c=b+1;c<=n;c++)
			for(int d=c+1;d<=n;d++)
			for(int e=d+1;e<=n;e++)
			for(int f=e+1;f<=n;f++)
			for(int g=f+1;g<=n;g++)
			for(int h=g+1;h<=n;h++)
			for(int o=h+1;o<=n;o++)
			for(int p=o+1;p<=n;p++)
			for(int q=p+1;q<=n;q++)
			for(int r=q+1;r<=n;r++)
			for(int s=r+1;s<=n;s++)
			for(int t=s+1;t<=n;t++)
			for(int u=t+1;u<=n;u++)
			for(int v=u+1;v<=n;v++)
			if(a[i]+a[j]+a[k]+a[l]+a[m]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]>a[v]) sum++;
		printf("%lld",sum);
	}else{
		printf("0");
	}
	return 0;
}
