#include<bits/stdc++.h>
using namespace std;
struct node{
	int num,ceng;
}a[100005],b[100005],c[100005];
int t;
int vis[100005];
bool cmp1(node x,node y){
	if(x.num==y.num) x.ceng<y.ceng;
	return x.num>y.num;
}
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
    cin>>t;
    while(t--){
    	int n;
    	cin>>n;
    	int m=n/2;
		for(int i=1;i<=n;i++){
			cin>>a[i].num>>b[i].num>>c[i].num;
			a[i].ceng=i,b[i].ceng=i,c[i].ceng=i;
		}
		if(n==2){
			int yl1=a[1].num+b[2].num;
			int yl2=a[1].num+c[2].num;
			int yl3=b[1].num+a[2].num;
			int yl4=b[1].num+c[2].num;
			int yl5=c[1].num+a[2].num;
			int yl6=c[1].num+b[2].num;
			cout<<max(yl1,(max(yl2,max(yl3,max(yl4,max(yl5,yl6))))));
			continue;
		}
		sort(a+1,a+n+1,cmp1);
		sort(b+1,b+n+1,cmp1);
		sort(c+1,c+n+1,cmp1);
		int ans=0;
		int am=0,bm=0,cm=0;
		for(int i=1;i<=n;i++){
			int ach=a[i].num-a[i+1].num;
			int bch=b[i].num-b[i+1].num;
			int cch=c[i].num-c[i+1].num;
			if(ach>=bch&&ach>=cch){//ach最大
				if(vis[a[i].ceng]==1||am>=m){
					if(bch>cch){
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					if(bch==cch&&b[i].num>=c[i].num){
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					if(bch==cch&&c[i].num>b[i].num){
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
					else{
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
				}
				else{
					am++;
					ans+=a[i].num;
					vis[a[i].ceng]=1;
					if(bch>cch){
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					if(bch==cch&&b[i].num>=c[i].num){
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					if(bch==cch&&c[i].num>b[i].num){
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
					else{
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
				}
			}
			else if(bch>=ach&&bch>=cch){//bch最大
				if(vis[b[i].ceng]==1||bm>=m){
					if(ach>=cch){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					else if(ach==cch&&a[i].num>=c[i].num){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					else if(ach==cch&&c[i].num>a[i].num){
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
					}
					else{
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
					}
				}
				else{
					bm++;
					ans+=b[i].num;
					vis[b[i].ceng]=1;
					if(ach>=cch){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					else if(ach==cch&&a[i].num>=c[i].num){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[c[i].ceng]!=1&&cm<m){
								cm++;
								vis[c[i].ceng]=1;
								ans+=c[i].num;
							}
						}
					}
					else if(ach==cch&&c[i].num>a[i].num){
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
					}
					else{
						if(vis[c[i].ceng]==1||cm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
						else{
							cm++;
							ans+=c[i].num;
							vis[c[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								vis[a[i].ceng]=1;
								ans+=a[i].num;
							}
						}
					}
				}
			}
			else{//cch最大
				if(vis[c[i].ceng]==1||cm>=m){
					if(ach>=bch){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
					else if(ach==bch&&a[i].num>=b[i].num){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
					else if(ach==bch&&b[i].num>a[i].num){
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
					}
					else{
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
					}
				}
				else{
					cm++;
					vis[c[i].ceng]=1;
					ans+=c[i].num;
					if(ach>=bch){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
					else if(ach==bch&&a[i].num>=b[i].num){
						if(vis[a[i].ceng]==1||am>=m){
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
						else{
							am++;
							ans+=a[i].num;
							vis[a[i].ceng]=1;
							if(vis[b[i].ceng]!=1&&bm<m){
								bm++;
								vis[b[i].ceng]=1;
								ans+=b[i].num;
							}
						}
					}
					else if(ach==bch&&b[i].num>a[i].num){
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
					}
					else{
						if(vis[b[i].ceng]==1||bm>=m){
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
						else{
							bm++;
							ans+=b[i].num;
							vis[b[i].ceng]=1;
							if(vis[a[i].ceng]!=1&&am<m){
								am++;
								ans+=a[i].num;
								vis[a[i].ceng]=1;
							}
						}
					}
				}
			}

		}
		cout<<ans<<endl;
	}
    fclose(stdin);
    fclose(stdout);
	return 0;
}
