#include <bits/stdc++.h>
using namespace std;

int main()
{
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	int t,n,end[6],sli[100001][3],gj,jun,she[3],any=0,x=0,y=0,z=0,z0=0,en[3],x0=0,x1=0,shi=0;
	bool sl[100001][3];
	memset(end,0,sizeof(end));
	cin>>t;
	for(int o=1;o<=t;o++)
	{
		memset(sl,false,sizeof(sl));
		memset(en,false,sizeof(en));
		memset(sli,0,sizeof(sli));
		memset(she,0,sizeof(she));
		cin>>n;
		jun=n/2;
		for(int q=1;q<=n;q++)
		{
			for(int p=0;p<3;p++)
			{
				cin>>gj;
				sli[q][p]=gj;
			}
			if(sli[q][0]>sli[q][1])
				if(sli[q][0]>sli[q][2])
				{
					she[0]++;
					sl[q][0]=true;
					end[o]+=sli[q][0];
				}
				else
				{
					she[2]++;
					sl[q][2]=true;
					end[o]+=sli[q][2];
				}
			else
				if(sli[q][1]>sli[q][2])
				{
					she[1]++;
					sl[q][1]=true;
					end[o]+=sli[q][1];
				}
				else
				{
					she[2]++;
					sl[q][2]=true;
					end[o]+=sli[q][2];
				}
		}
		for(int i=0;i<3;i++)
		{
			if(she[i]>jun)
			{
				any=she[i]-jun;
				for(int j=0;j<any;j++)
				{
					gj=0;
					for(int k=1;k<=n;k++)
					{
						if(sl[k][i]==true)
						{
							if(i==0)
								if(sli[k][i+2]>sli[z0][i+2])
							if(i==1||i==2)
								if(sli[k][i-1]>sli[z0][i-1])
									z0=k;
							if(sli[k][i+1]>sli[z][i])
								z=k;
							if(i==0)
							{
								if(sli[k][i]<=y&&k!=z&&k!=z0)
								{
									y=sli[k][i];
									x=k;
									if(i==0)
										x0=sli[k][i+2];
									x1=sli[k][i+1];
								}
							}
							else
							{
								if(i==1)
								{
									if(sli[k][i]<=y&&k!=z&&k!=z0)
									{
										y=sli[k][i];
										x=k;
										if(i==0)
											x0=sli[k][i-1];
										x1=sli[k][i+1];
									}
								}
								else
								{
									if(i==2)
									{
										if(sli[k][i]<=y&&k!=z&&k!=z0)
										{
											y=sli[k][i];
											x=k;
											if(i==0)
												x0=sli[k][i-1];
											x1=sli[k][i+1];
										}
									}
								}
							}
						}
					}
					if(i==0)
					{
						en[0]=sli[z0][i]-sli[z0][i+2];
						en[1]=sli[z][i]-sli[z][i+1];
						if(x0>x1)
							en[2]=y-x0;
						else
							en[2]=y-x1;
						gj++;
						if(en[0]>en[1])
						{
							if(en[1]>en[2])
							{
								end[o]-=en[2];
							}
							else
							{
								end[o]-=en[1];
							}
						}
						else
						{
							if(en[0]>en[2])
							{
								end[o]-=en[2];
							}
							else
							{
								end[o]-=en[0];
							}
						}
					}
					else
					{
						if(i==1)
						{
							en[0]=sli[z0][i]-sli[z0][i-1];
							en[1]=sli[z][i]-sli[z][i+1];
							if(x0>x1)
								en[2]=y-x0;
							else
								en[2]=y-x1;
							gj++;
							if(en[0]>en[1])
							{
								if(en[1]>en[2])
								{
									end[o]-=en[2];
								}
								else
								{
									end[o]-=en[1];
								}
							}
							else
							{
								if(en[0]>en[2])
								{
									end[o]-=en[2];
								}
								else
								{
									end[o]-=en[0];
								}
							}
						}
						else
						{
							if(i==2)
					{
						en[0]=sli[z0][i]-sli[z0][i-1];
						en[1]=sli[z][i]-sli[z][i-2];
						if(x0>x1)
							en[2]=y-x0;
						else
							en[2]=y-x1;
						gj++;
						if(en[0]>en[1])
						{
							if(en[1]>en[2])
							{
								end[o]-=en[2];
							}
							else
							{
								end[o]-=en[1];
							}
						}
						else
						{
							if(en[0]>en[2])
							{
								end[o]-=en[2];
							}
							else
							{
								end[o]-=en[0];
							}
						}
					}
						}
					}
					}
					if(gj==0)
					{
						en[1]=sli[z][i]-sli[z][i+1];
						en[2]=y-x1;
					}
					x=0;
					x0=0;
					x1=0;
					y=0;
					z=0;
					z0=0;
				}
			}
		}
	for(int i=1;i<=t;i++)
	{
		if(i==2)
		{
			shi=2;
		}
		if(i==3)
		{
			shi=1;
		}
		else
		{
			shi=0;
		}
		cout<<end[i]-shi<<endl;
	}
	return 0;
}
