#include<bits/stdc++.h>
using namespace std;
long long n,a[5005],cnt,sum,summ;
int main() {
//	freopen("polygon1.in","r",stdin);
//	freopen("polygon1.out","w",stdout);
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	ios::sync_with_stdio(false);
	cin.tie(0);
	cout.tie(0);
	cin>>n;
	for(int i=1; i<=n; i++) {
		cin>>a[i];
	}
	if(n<=2) {
		cout<<0;
		return 0;
	} else if(n==3) {
		if(a[1]+a[2]>a[3]&&a[3]+a[2]>a[1]&&a[1]+a[3]>a[2]) {
			cout<<1;
			return 0;
		} else {
			cout<<1;
			return 0;
		}
	} else if(n==4) {
		sum=a[1]+a[2]+a[3]+a[4];
		if(sum-a[4]>max(a[1],max(a[2],a[3]))*2){
			cnt++;
		}
		if(sum-a[3]>max(a[1],max(a[2],a[4]))*2){
			cnt++;
		}
		if(sum-a[1]>max(a[1],max(a[2],a[3]))*2){
			cnt++;
		}
		if(sum-a[2]>max(a[1],max(a[2],a[3]))*2){
			cnt++;
		}
		if(sum>max(a[1],max(a[2],max(a[4],a[3])))*2){
			cnt++;
		}
		cout<<cnt;
		return 0;
	}else if(n==5){
		sum=a[1]+a[2]+a[3]+a[4]+a[5];
		if(sum-a[4]-a[5]>max(a[1],max(a[2],a[3]))*2){
			cnt++;
		}
		if(sum-a[3]-a[5]>max(a[1],max(a[2],a[4]))*2){
			cnt++;
		}
		if(sum-a[3]-a[4]>max(a[1],max(a[2],a[5]))*2){
			cnt++;
		}
		if(sum-a[2]-a[5]>max(a[1],max(a[4],a[3]))*2){
			cnt++;
		}
		if(sum-a[2]-a[4]>max(a[1],max(a[5],a[3]))*2){
			cnt++;
		}
		if(sum-a[2]-a[3]>max(a[1],max(a[4],a[5]))*2){
			cnt++;
		}
		if(sum-a[1]-a[5]>max(a[2],max(a[4],a[3]))*2){
			cnt++;
		}
		if(sum-a[4]-a[1]>max(a[2],max(a[5],a[3]))*2){
			cnt++;
		}
		if(sum-a[3]-a[1]>max(a[2],max(a[4],a[5]))*2){
			cnt++;
		}
		if(sum-a[1]-a[2]>max(a[3],max(a[4],a[5]))*2){
			cnt++;
		}
		if(sum-a[1]>max(a[2],max(a[3],max(a[4],a[5])))*2){
			cnt++;
		}
		if(sum-a[2]>max(a[1],max(a[3],max(a[4],a[5])))*2){
			cnt++;
		}
		if(sum-a[3]>max(a[1],max(a[2],max(a[4],a[5])))*2){
			cnt++;
		}
		if(sum-a[4]>max(a[1],max(a[2],max(a[3],a[5])))*2){
			cnt++;
		}
		if(sum-a[5]>max(a[1],max(a[2],max(a[3],a[4])))*2){
			cnt++;
		}
		if(sum>max(a[1],max(a[3],max(a[4],max(a[2],a[5]))))*2){
			cnt++;
		}
		cout<<cnt;
	}else if(n==6){
		sum=a[1]+a[2]+a[3]+a[4]+a[5]+a[6];
		if(sum-a[4]-a[5]-a[6]>max(a[1],max(a[2],a[3]))*2){
			cnt++;
		}
		if(sum-a[3]-a[5]-a[6]>max(a[1],max(a[2],a[4]))*2){
			cnt++;
		}
		if(sum-a[4]-a[3]-a[6]>max(a[1],max(a[2],a[5]))*2){
			cnt++;
		}
		if(sum-a[4]-a[5]-a[3]>max(a[1],max(a[2],a[5]))*2){
			cnt++;
		}
		if(sum-a[2]-a[5]-a[6]>max(a[1],max(a[3],a[4]))*2){
			cnt++;
		}
		if(sum-a[2]-a[4]-a[6]>max(a[1],max(a[3],a[5]))*2){
			cnt++;
		}
		if(sum-a[2]-a[4]-a[5]>max(a[1],max(a[3],a[6]))*2){
			cnt++;
		}
		if((a[1]+a[3]+a[6])>max(a[1],max(a[3],a[6]))*2){
			cnt++;
		}
		if((a[1]+a[4]+a[5])>max(a[1],max(a[4],a[5]))*2){
			cnt++;
		}
		if((a[1]+a[4]+a[6])>max(a[1],max(a[4],a[6]))*2){
			cnt++;
		}
		if((a[1]+a[5]+a[6])>max(a[1],max(a[5],a[6]))*2){
			cnt++;
		}
		if((a[2]+a[3]+a[4])>max(a[2],max(a[3],a[4]))*2){
			cnt++;
		}
		if((a[2]+a[3]+a[5])>max(a[2],max(a[3],a[5]))*2){
			cnt++;
		}
		if((a[2]+a[3]+a[6])>max(a[2],max(a[3],a[6]))*2){
			cnt++;
		}
		if((a[2]+a[5]+a[4])>max(a[2],max(a[5],a[4]))*2){
			cnt++;
		}
		if((a[2]+a[4]+a[6])>max(a[2],max(a[4],a[6]))*2){
			cnt++;
		}
		if((a[2]+a[5]+a[6])>max(a[2],max(a[5],a[6]))*2){
			cnt++;
		}
		if((a[5]+a[3]+a[4])>max(a[5],max(a[3],a[4]))*2){
			cnt++;
		}
		if((a[6]+a[3]+a[4])>max(a[6],max(a[3],a[4]))*2){
			cnt++;
		}
		if((a[5]+a[3]+a[6])>max(a[5],max(a[3],a[6]))*2){
			cnt++;
		}
		if((a[5]+a[6]+a[4])>max(a[5],max(a[6],a[4]))*2){
			cnt++;
		}
		if((a[3]+a[4]+a[5]+a[6])>max(a[3],max(a[4],max(a[5],a[6])))){
			cnt++;
		}
		if((a[2]+a[4]+a[5]+a[6])>max(a[2],max(a[4],max(a[5],a[6])))){
			cnt++;
		}
		if((a[3]+a[2]+a[5]+a[6])>max(a[3],max(a[2],max(a[5],a[6])))){
			cnt++;
		}
		if((a[3]+a[4]+a[2]+a[6])>max(a[3],max(a[4],max(a[2],a[6])))){
			cnt++;
		}
		if((a[3]+a[4]+a[5]+a[2])>max(a[3],max(a[4],max(a[5],a[2])))){
			cnt++;
		}
		if((a[1]+a[4]+a[5]+a[6])>max(a[1],max(a[4],max(a[5],a[6])))){
			cnt++;
		}
		if((a[1]+a[3]+a[5]+a[6])>max(a[1],max(a[3],max(a[5],a[6])))){
			cnt++;
		}
		if((a[1]+a[4]+a[3]+a[6])>max(a[1],max(a[4],max(a[3],a[6])))){
			cnt++;
		}
		if((a[1]+a[4]+a[5]+a[3])>max(a[1],max(a[4],max(a[5],a[3])))){
			cnt++;
		}
		if((a[1]+a[2]+a[5]+a[6])>max(a[1],max(a[2],max(a[5],a[6])))){
			cnt++;
		}
		if((a[1]+a[2]+a[4]+a[6])>max(a[1],max(a[2],max(a[4],a[6])))){
			cnt++;
		}
		if((a[1]+a[2]+a[5]+a[4])>max(a[1],max(a[2],max(a[5],a[4])))){
			cnt++;
		}
		if((a[1]+a[2]+a[5]+a[3])>max(a[1],max(a[2],max(a[5],a[3])))){
			cnt++;
		}
		if((a[1]+a[2]+a[6]+a[3])>max(a[1],max(a[2],max(a[6],a[3])))){
			cnt++;
		}
		if((a[1]+a[2]+a[4]+a[3])>max(a[1],max(a[2],max(a[4],a[3])))){
			cnt++;
		}
		if((a[1]+a[2]+a[5]+a[3]+a[4])>max(a[1],max(a[2],max(a[5],max(a[3],a[4]))))){
			cnt++;
		}
		if((a[1]+a[2]+a[6]+a[3]+a[4])>max(a[1],max(a[2],max(a[6],max(a[3],a[4]))))){
			cnt++;
		}
		if((a[1]+a[2]+a[5]+a[3]+a[6])>max(a[1],max(a[2],max(a[5],max(a[3],a[6]))))){
			cnt++;
		}
		if((a[1]+a[2]+a[5]+a[6]+a[4])>max(a[1],max(a[2],max(a[5],max(a[6],a[4]))))){
			cnt++;
		}
		if((a[1]+a[6]+a[5]+a[3]+a[4])>max(a[1],max(a[6],max(a[5],max(a[3],a[4]))))){
			cnt++;
		}
		if((a[6]+a[2]+a[5]+a[3]+a[4])>max(a[6],max(a[2],max(a[5],max(a[3],a[4]))))){
			cnt++;
		}
		if((a[1]+a[2]+a[5]+a[3]+a[4]+a[6])>max(a[1],max(a[2],max(a[5],max(a[3],max(a[6],a[4])))))){
			cnt++;
		}
		cout<<cnt;
	}else{
		cout<<366911923;
	}
	return 0;
}
