#include<bits/stdc++.h>
using namespace std;
long long x,y[5005],sums;
int main(){
	ios::sync_with_stdio(0),cin.tie(0),cout.tie(0);
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin>>x;
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)if(a!=b&&b!=c&&y[a]+y[b]>y[c]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)if(a!=b&&b!=c&&c!=d&&y[a]+y[b]+y[c]>y[d]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)if(a!=b&&b!=c&&c!=d&&d!=e&&y[a]+y[b]+y[c]+y[d]>y[e]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&y[a]+y[b]+y[c]+y[d]+y[e]>y[f]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]>y[g]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]>y[h]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]>y[i]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]>y[j]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]>y[k]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]>y[l]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]>y[m]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)for(int n=m;n<=x;n++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&m!=n&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]+y[m]>y[n]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)for(int n=m;n<=x;n++)for(int o=n;o<=x;o++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&m!=n&&n!=o&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]+y[m]+y[n]>y[o]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)for(int n=m;n<=x;n++)for(int o=n;o<=x;o++)for(int p=o;p<=x;p++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&m!=n&&n!=o&&o!=p&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]+y[m]+y[n]+y[o]>y[p]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)for(int n=m;n<=x;n++)for(int o=n;o<=x;o++)for(int p=o;p<=x;p++)for(int q=p;q<=x;q++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&m!=n&&n!=o&&o!=p&&p!=q&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]+y[m]+y[n]+y[o]+y[p]>y[q]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)for(int n=m;n<=x;n++)for(int o=n;o<=x;o++)for(int p=o;p<=x;p++)for(int q=p;q<=x;q++)for(int r=q;r<=x;r++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&m!=n&&n!=o&&o!=p&&p!=q&&q!=r&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]+y[m]+y[n]+y[o]+y[p]+y[q]>y[r]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)for(int n=m;n<=x;n++)for(int o=n;o<=x;o++)for(int p=o;p<=x;p++)for(int q=p;q<=x;q++)for(int r=q;r<=x;r++)for(int s=r;s<=x;s++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&m!=n&&n!=o&&o!=p&&p!=q&&q!=r&&r!=s&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]+y[m]+y[n]+y[o]+y[p]+y[q]+y[r]>y[s]){sums++;sums%=998244353;}
	for(int a=1;a<=x;a++)for(int b=a;b<=x;b++)for(int c=b;c<=x;c++)for(int d=c;d<=x;d++)for(int e=d;e<=x;e++)for(int f=e;f<=x;f++)for(int g=f;g<=x;g++)for(int h=g;h<=x;h++)for(int i=h;i<=x;i++)for(int j=i;j<=x;j++)for(int k=j;k<=x;k++)for(int l=k;l<=x;l++)for(int m=l;m<=x;m++)for(int n=m;n<=x;n++)for(int o=n;o<=x;o++)for(int p=o;p<=x;p++)for(int q=p;q<=x;q++)for(int r=q;r<=x;r++)for(int s=r;s<=x;s++)for(int t=s;t<=x;t++)if(a!=b&&b!=c&&c!=d&&d!=e&&e!=f&&f!=g&&g!=h&&h!=i&&i!=j&&j!=k&&k!=l&&l!=m&&m!=n&&n!=o&&o!=p&&p!=q&&q!=r&&r!=s&&s!=t&&y[a]+y[b]+y[c]+y[d]+y[e]+y[f]+y[g]+y[h]+y[i]+y[j]+y[k]+y[l]+y[m]+y[n]+y[o]+y[p]+y[q]+y[r]+y[s]>y[t]){sums++;sums%=998244353;}
	cout<<sums;
	return 0;
}