#include<bits/stdc++.h>
using namespace std;
const int N = 1e6+100;
struct Node{
	int u,v,w;
}roads[N];
int countrisides_to_cities[22][11000];
int spendly_dollars_to_build_countrisides[22];
signed main(){
	freopen("road.in","r",stdin);
	freopen("road.out","w",stdout);
	
	
	//need to use smallest tree;
	//but I forget how to write;
	//so I can write it full;
	int n,m,k; cin >> n >> m >> k;
	for(int i = 1; i <= m; i++){
		cin >> roads[i].u >> roads[i].v >> roads[i].w;
	}
	for(int i = 1; i <= k; i++){
		cin >> spendly_dollars_to_build_countrisides[i];
		for(int j = 1; j <= n; j++){
			cin >> countrisides_to_cities[i][j];
		}
	}
	cout << 0;
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}
