#include<bits/stdc++.h>
using namespace std;
int main(){
	int n;
	//I like CCF I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF  I like CCF Æ­ÄãµÄ ÎûÎûFUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF //FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
	freopen("xor.in","r",stdin);
	freopen("xor.out","w",stdout);
	cin>>n;
	int k;
	long long int a[100005];
	for(int i=1;i<=n;i++){
		cin>>a[i];
	}
	cout<<n/2;
	fclose(stdin);
	fclose(stdout);
	return 0; 
}


















































//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF

//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
//FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF FUCK CCF
