#include<bits/stdc++.h>
using namespace std;
int main(){
	freopen("number.in","r",stdin);
	freopen("number.out","w",stdout);
	int s,a,b,c,d,e,f,n,m;
	cin>>s;
	if(s<100){
   		a=s%10;
		s=s/10;
		if(a>s){
			n=a*10+s;
		}
		if(s>a){
			n=s*10+a;
		}
		if(s==a){
			n=s*10+a;
		}
		cout<<n;
	}else 
	if(s<1000){
		d=s%100;
		c=d;
		d=d%10;//个 
		e=c/10;//十 
		s=s/100;//百 
		if(s>e&&s>d&&e>d) {//百》十》个 
			m=s*100+e*10+d;
			cout<<m; 
		}
		if(s>e&&s>d&&d>e) {//百》个》十 
			m=s*100+d*10+e; 
			cout<<m;
		}
		if(e>d&&e>s&&d>s){//十>个>百 
			m=e*100+d*10+s;
			cout<<m;
		}
		if(e>d&&e>s&&s>d){//十》百》个 
			m=e*100+s*10+d;
			cout<<m;
		}
		if(d>e&&d>s&&e>s) {//个》十》百 
			m=d*100+e*10+s; 
			cout<<m;
		}
		if(d>e&&d>s&&s>e) {//个》百》十 
			m=d*100+s*10+e; 
			cout<<m;
		}
	}else
	if(s<10000){
		a=s%1000;
		f=a;
		a=a%100;
		e=a;
		a=a%10;//个 
		b=e/10;//十 
		c=f/100;//百
		d=s/1000;//千 
		if(d>c&&d>b&&d>a&&c>b&&c>a&&b>a){//千》百》十》个 
			cout<<s;
		}
		if(d>c&&d>b&&d>a&&c>b&&c>a&&a>b){//千》百》个》十 
			n=d*1000+c*100+a*10+b;
			cout<<n;
		}
		if(d>c&&d>b&&d>a&&b>c&&b>a&&c>a){
			n=d*1000+b*100+c*10+a;
			cout<<n;
		}
		if(d>c&&d>b&&d>a&&b>c&&b>a&&a>c){
			n=d*1000+b*100+a*10+c;
			cout<<n;
		}
		if(d>c&&d>b&&d>a&&a>b&&a>c&&b>c){
			n=d*1000+a*100+b*10+c;
			cout<<n;
		}
		if(d>c&&d>b&&d>a&&a>b&&a>c&&c>b){
			n=d*1000+a*100+c*10+b;
			cout<<n;
		}
		if(c>a&&c>b&&c>d&&d>a&&d>b&&b>a){//
			n=c*1000+d*100+b*10+a;
			cout<<n;
		}
		if(c>a&&c>b&&c>d&&d>a&&d>b&&a>b){
			n=c*1000+d*100+a*10+b;
			cout<<n;
		}
		if(c>a&&c>b&&c>d&&b>a&&b>d&&d>a){
			n=c*1000+b*100+d*10+a;
			cout<<n;
		}
		if(c>a&&c>b&&c>d&&b>a&&b>c&&a>d){
			n=c*1000+b*100+a*10+d;
			cout<<n;
		}
		if(c>a&&c>d&&c>d&&a>b&&a>d&&b>d){
			n=c*1000+a*100+b*10+d;
			cout<<n;
		}
		if(c>a&&c>d&&c>d&&a>b&&a>d&&d>b){
			n=c*1000+a*100+d*10+b;
			cout<<n;
		}
		if(b>a&&b>c&&b>d&&a>d&&a>c&&c>d){//
			n=b*1000+a*100+c*10+d;
			cout<<n;
		}
		if(b>a&&b>c&&b>d&&a>d&&a>c&&d>c){
			n=b*1000+a*100+d*10+c;
			cout<<n;
		}
		if(b>a&&b>c&&b>d&&c>d&&c>a&&a>d){
			n=b*1000+c*100+a*10+d;
			cout<<n;
		}
		if(b>a&&b>c&&b>d&&c>b&&c>a&&d>a){
			n=b*1000+c*100+d*10+a;
			cout<<n;
		}
		if(b>a&&b>c&&b>d&&d>a&&d>c&&a>c){
			n=b*1000+d*100+a*10+c;
			cout<<n;
		}
		if(b>a&&b>c&&b>d&&d>a&&d>c&&c>a){
			n=b*1000+d*100+c*10+a;
			cout<<n;
		}
	}
	
 return 0;
}

