#include <bits/stdc++.h>
using namespace std;

long long n, mod = 998244353, ans = 0;
long long a[5010];
int main()
{
	freopen("polygon.in", "r", stdin);
	freopen("polygon.out", "w", stdout);
	
	scanf("%d", &n);
	for (long long i = 0; i < n; i++)
	{
		scanf("%d", &a[i]);
	}
	
	sort(a, a + n);
	
	for (long long i = 0; i < n - 2; i++)
		for (long long j = i + 1; j < n - 1; j++)
			for (long long k = j + 1; k < n; k++)
				if (a[i] + a[j] + a[k] > a[k] * 2)
					ans++;
	
	for (long long i = 0; i < n - 3; i++)
		for (long long j = i + 1; j < n - 2; j++)
			for (long long k = j + 1; k < n - 1; k++)
				for (long long m = k + 1; m < n; m++)
					if (a[i] + a[j] + a[k] + a[m] > a[m] * 2)
						ans++;
	
	for (long long i = 0; i < n - 4; i++)
		for (long long j = i + 1; j < n - 3; j++)
			for (long long k = j + 1; k < n - 2; k++)
				for (long long m = k + 1; m < n - 1; m++)
					for (long long l = m + 1; l < n; l++)
						if (a[i] + a[j] + a[k] + a[m] + a[l] > a[l] * 2)
							ans++;
	
	for (long long i = 0; i < n - 5; i++)
		for (long long j = i + 1; j < n - 4; j++)
			for (long long k = j + 1; k < n - 3; k++)
				for (long long m = k + 1; m < n - 2; m++)
					for (long long l = m + 1; l < n - 1; l++)
						for (long long p = l + 1; p < n; p++)
							if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p]> a[p] * 2)
								ans++;

	
	for (long long i = 0; i < n - 6; i++)
		for (long long j = i + 1; j < n - 5; j++)
			for (long long k = j + 1; k < n - 4; k++)
				for (long long m = k + 1; m < n - 3; m++)
					for (long long l = m + 1; l < n - 2; l++)
						for (long long p = l + 1; p < n - 1; p++)
							for (long long q = p + 1; q < n; q++)
								if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q]> a[q] * 2)
									ans++;
								
	for (long long i = 0; i < n - 7; i++)
		for (long long j = i + 1; j < n - 6; j++)
			for (long long k = j + 1; k < n - 5; k++)
				for (long long m = k + 1; m < n - 4; m++)
					for (long long l = m + 1; l < n - 3; l++)
						for (long long p = l + 1; p < n - 2; p++)
							for (long long q = p + 1; q < n - 1; q++)
								for (long long u = q + 1; u < n; u++)
									if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u]> a[u] * 2)
										ans++;
	
	for (long long i = 0; i < n - 8; i++)
		for (long long j = i + 1; j < n - 7; j++)
			for (long long k = j + 1; k < n - 6; k++)
				for (long long m = k + 1; m < n - 5; m++)
					for (long long l = m + 1; l < n - 4; l++)
						for (long long p = l + 1; p < n - 3; p++)
							for (long long q = p + 1; q < n - 2; q++)
								for (long long u = q + 1; u < n - 1; u++)
									for (long long y = u + 1; y < n; y++)
										if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] > a[y] * 2)
											ans++;
	
	for (long long x = 0; x < n - 9; x++)
		for (long long i = x + 1; i < n - 8; i++)
			for (long long j = i + 1; j < n - 7; j++)
				for (long long k = j + 1; k < n - 6; k++)
					for (long long m = k + 1; m < n - 5; m++)
						for (long long l = m + 1; l < n - 4; l++)
							for (long long p = l + 1; p < n - 3; p++)
								for (long long q = p + 1; q < n - 2; q++)
									for (long long u = q + 1; u < n - 1; u++)
										for (long long y = u + 1; y < n; y++)
											if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] > a[y] * 2)
												ans++;
	for (long long z = 0; z < n - 10; z++)	
		for (long long x = z + 1; x < n - 9; x++)
			for (long long i = x + 1; i < n - 8; i++)
				for (long long j = i + 1; j < n - 7; j++)
					for (long long k = j + 1; k < n - 6; k++)
						for (long long m = k + 1; m < n - 5; m++)
							for (long long l = m + 1; l < n - 4; l++)
								for (long long p = l + 1; p < n - 3; p++)
									for (long long q = p + 1; q < n - 2; q++)
										for (long long u = q + 1; u < n - 1; u++)
											for (long long y = u + 1; y < n; y++)
												if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] > a[y] * 2)
													ans++;
	for (long long w = 0; w < n - 11; w++)
		for (long long z = w + 1; z < n - 10; z++)	
			for (long long x = z + 1; x < n - 9; x++)
				for (long long i = x + 1; i < n - 8; i++)
					for (long long j = i + 1; j < n - 7; j++)
						for (long long k = j + 1; k < n - 6; k++)
							for (long long m = k + 1; m < n - 5; m++)
								for (long long l = m + 1; l < n - 4; l++)
									for (long long p = l + 1; p < n - 3; p++)
										for (long long q = p + 1; q < n - 2; q++)
											for (long long u = q + 1; u < n - 1; u++)
												for (long long y = u + 1; y < n; y++)
													if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] > a[y] * 2)
														ans++;
	
	for (long long e = 0; e < n - 12; e++)													
		for (long long w = e + 1; w < n - 11; w++)
			for (long long z = w + 1; z < n - 10; z++)	
				for (long long x = z + 1; x < n - 9; x++)
					for (long long i = x + 1; i < n - 8; i++)
						for (long long j = i + 1; j < n - 7; j++)
							for (long long k = j + 1; k < n - 6; k++)
								for (long long m = k + 1; m < n - 5; m++)
									for (long long l = m + 1; l < n - 4; l++)
										for (long long p = l + 1; p < n - 3; p++)
											for (long long q = p + 1; q < n - 2; q++)
												for (long long u = q + 1; u < n - 1; u++)
													for (long long y = u + 1; y < n; y++)
														if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] > a[y] * 2)
															ans++;
	for (long long o = 0; o < n - 13; o++)														
		for (long long e = o + 1; e < n - 12; e++)													
			for (long long w = e + 1; w < n - 11; w++)
				for (long long z = w + 1; z < n - 10; z++)	
					for (long long x = z + 1; x < n - 9; x++)
						for (long long i = x + 1; i < n - 8; i++)
							for (long long j = i + 1; j < n - 7; j++)
								for (long long k = j + 1; k < n - 6; k++)
									for (long long m = k + 1; m < n - 5; m++)
										for (long long l = m + 1; l < n - 4; l++)
											for (long long p = l + 1; p < n - 3; p++)
												for (long long q = p + 1; q < n - 2; q++)
													for (long long u = q + 1; u < n - 1; u++)
														for (long long y = u + 1; y < n; y++)
															if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] + a[o] > a[y] * 2)
																ans++;
	for (long long r = 0; r < n - 14; r++)
		for (long long o = r + 1; o < n - 13; o++)														
			for (long long e = o + 1; e < n - 12; e++)													
				for (long long w = e + 1; w < n - 11; w++)
					for (long long z = w + 1; z < n - 10; z++)	
						for (long long x = z + 1; x < n - 9; x++)
							for (long long i = x + 1; i < n - 8; i++)
								for (long long j = i + 1; j < n - 7; j++)
									for (long long k = j + 1; k < n - 6; k++)
										for (long long m = k + 1; m < n - 5; m++)
											for (long long l = m + 1; l < n - 4; l++)
												for (long long p = l + 1; p < n - 3; p++)
													for (long long q = p + 1; q < n - 2; q++)
														for (long long u = q + 1; u < n - 1; u++)
															for (long long y = u + 1; y < n; y++)
																if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] + a[o] + a[r] > a[y] * 2)
																	ans++;
	
	for (long long s = 0; s < n - 15; s++)												
		for (long long r = s + 1; r < n - 14; r++)
			for (long long o = r + 1; o < n - 13; o++)														
				for (long long e = o + 1; e < n - 12; e++)													
					for (long long w = e + 1; w < n - 11; w++)
						for (long long z = w + 1; z < n - 10; z++)	
							for (long long x = z + 1; x < n - 9; x++)
								for (long long i = x + 1; i < n - 8; i++)
									for (long long j = i + 1; j < n - 7; j++)
										for (long long k = j + 1; k < n - 6; k++)
											for (long long m = k + 1; m < n - 5; m++)
												for (long long l = m + 1; l < n - 4; l++)
													for (long long p = l + 1; p < n - 3; p++)
														for (long long q = p + 1; q < n - 2; q++)
															for (long long u = q + 1; u < n - 1; u++)
																for (long long y = u + 1; y < n; y++)
																	if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] + a[o] + a[r] + a[s] > a[y] * 2)
																		ans++;
	
	for (long long b = 0; b < n - 16; b++)									
		for (long long s = b + 1; s < n - 15; s++)												
			for (long long r = s + 1; r < n - 14; r++)
				for (long long o = r + 1; o < n - 13; o++)														
					for (long long e = o + 1; e < n - 12; e++)													
						for (long long w = e + 1; w < n - 11; w++)
							for (long long z = w + 1; z < n - 10; z++)	
								for (long long x = z + 1; x < n - 9; x++)
									for (long long i = x + 1; i < n - 8; i++)
										for (long long j = i + 1; j < n - 7; j++)
											for (long long k = j + 1; k < n - 6; k++)
												for (long long m = k + 1; m < n - 5; m++)
													for (long long l = m + 1; l < n - 4; l++)
														for (long long p = l + 1; p < n - 3; p++)
															for (long long q = p + 1; q < n - 2; q++)
																for (long long u = q + 1; u < n - 1; u++)
																	for (long long y = u + 1; y < n; y++)
																		if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] + a[o] + a[r] + a[s] + a[b]> a[y] * 2)
																			ans++;
	for (long long v = 0; v < n - 17; v++)																		
		for (long long b = v + 1; b < n - 16; b++)									
			for (long long s = b + 1; s < n - 15; s++)												
				for (long long r = s + 1; r < n - 14; r++)
					for (long long o = r + 1; o < n - 13; o++)														
						for (long long e = o + 1; e < n - 12; e++)													
							for (long long w = e + 1; w < n - 11; w++)
								for (long long z = w + 1; z < n - 10; z++)	
									for (long long x = z + 1; x < n - 9; x++)
										for (long long i = x + 1; i < n - 8; i++)
											for (long long j = i + 1; j < n - 7; j++)
												for (long long k = j + 1; k < n - 6; k++)
													for (long long m = k + 1; m < n - 5; m++)
														for (long long l = m + 1; l < n - 4; l++)
															for (long long p = l + 1; p < n - 3; p++)
																for (long long q = p + 1; q < n - 2; q++)
																	for (long long u = q + 1; u < n - 1; u++)
																		for (long long y = u + 1; y < n; y++)
																			if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] + a[o] + a[r] + a[s] + a[b] + a[v] > a[y] * 2)
																				ans++;
	for (long long c = 0; c < n - 18; c++)
		for (long long v = c + 1; v < n - 17; v++)																		
			for (long long b = v + 1; b < n - 16; b++)									
				for (long long s = b + 1; s < n - 15; s++)												
					for (long long r = s + 1; r < n - 14; r++)
						for (long long o = r + 1; o < n - 13; o++)														
							for (long long e = o + 1; e < n - 12; e++)													
								for (long long w = e + 1; w < n - 11; w++)
									for (long long z = w + 1; z < n - 10; z++)	
										for (long long x = z + 1; x < n - 9; x++)
											for (long long i = x + 1; i < n - 8; i++)
												for (long long j = i + 1; j < n - 7; j++)
													for (long long k = j + 1; k < n - 6; k++)
														for (long long m = k + 1; m < n - 5; m++)
															for (long long l = m + 1; l < n - 4; l++)
																for (long long p = l + 1; p < n - 3; p++)
																	for (long long q = p + 1; q < n - 2; q++)
																		for (long long u = q + 1; u < n - 1; u++)
																			for (long long y = u + 1; y < n; y++)
																				if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] + a[o] + a[r] + a[s] + a[b] + a[v] + a[c] > a[y] * 2)
																					ans++;	
	for (long long g = 0; g < n - 19; g++)
		for (long long c = g + 1; c < n - 18; c++)
			for (long long v = c + 1; v < n - 17; v++)																		
				for (long long b = v + 1; b < n - 16; b++)									
					for (long long s = b + 1; s < n - 15; s++)												
						for (long long r = s + 1; r < n - 14; r++)
							for (long long o = r + 1; o < n - 13; o++)														
								for (long long e = o + 1; e < n - 12; e++)													
									for (long long w = e + 1; w < n - 11; w++)
										for (long long z = w + 1; z < n - 10; z++)	
											for (long long x = z + 1; x < n - 9; x++)
												for (long long i = x + 1; i < n - 8; i++)
													for (long long j = i + 1; j < n - 7; j++)
														for (long long k = j + 1; k < n - 6; k++)
															for (long long m = k + 1; m < n - 5; m++)
																for (long long l = m + 1; l < n - 4; l++)
																	for (long long p = l + 1; p < n - 3; p++)
																		for (long long q = p + 1; q < n - 2; q++)
																			for (long long u = q + 1; u < n - 1; u++)
																				for (long long y = u + 1; y < n; y++)
																					if (a[i] + a[j] + a[k] + a[m] + a[l] + a[p] + a[q] + a[u] + a[y] + a[x] + a[z] + a[w] + a[e] + a[o] + a[r] + a[s] + a[b] + a[g] + a[v] + a[c] > a[y] * 2)
																						ans++;																																		
	ans %= mod;
	printf("%d", ans);
	
	fclose(stdin);
	fclose(stdout);
	return 0;
}
