#include<bits/stdc++.h>
#define For(i,a,n) for(int i=a;i<=n;i++)
using namespace std;
int a[5005];
int main(){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	int n;
	int ans=0;
	cin>>n;
	if(n>20){
		cout<<366911923;
		return 0;
	}
	int f=1;
	For(i,1,n){
		cin>>a[i];
		if(a[i]!=1)f=0;
	}
	if(f==1){
		cout<<1;
		return 0   ;
	}
	//special   
	sort(a+1,a+1+n);
	if(n>=3){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					if(a[i]+a[j]>a[k]){
						ans++;
					}
				}
			}
		}
	}//3
	if(n>=4){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						if(a[i]+a[j]+a[k]>a[l]){
							ans++;
						}
					}
				}
			}
		}
	}//4
	if(n>=5){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							if(a[i]+a[j]+a[k]+a[l]>a[o])ans++;
						}
					}
				}
			}
		}	
	}//5
	if(n>=6){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								if(a[i]+a[j]+a[k]+a[l]+a[o]>a[p])ans++;
							}		
						}
					}
				}
			}
		}		
	}//6
	if(n>=7){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]>a[q])ans++;
								}
							}	
						}
					}
				}
			}
		}		
	}//7
	if(n>=8){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]>a[d])ans++;
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//8
	if(n>=9){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]>a[e])ans++;
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//9
	if(n>=10){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]>a[u])ans++;
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//10
	if(n>=11){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]>a[w])ans++;
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//11
	if(n>=12){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]>a[r])ans++;
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//12
	if(n>=13){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														For(t,r+1,n){
															if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]+a[r]>a[t])ans++;
														}
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//13
	if(n>=14){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														For(t,r+1,n){
															For(y,t+1,n){
																if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]+a[r]>a[t])ans++;
															}
														}
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//14
	if(n>=15){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														For(t,r+1,n){
															For(y,t+1,n){
																For(s,y+1,n){
																	if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]+a[r]+a[t]>a[s])ans++;
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//15
	if(n>=16){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														For(t,r+1,n){
															For(y,t+1,n){
																For(s,y+1,n){
																	For(g,s+1,n){
																		if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]+a[r]+a[t]+a[s]>a[g])ans++;
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//16
	if(n>=17){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														For(t,r+1,n){
															For(y,t+1,n){
																For(s,y+1,n){
																	For(g,s+1,n){
																		For(h,g+1,n){
																			if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]+a[r]+a[t]+a[s]+a[g]>a[h])ans++;
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//17
	if(n>=18){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														For(t,r+1,n){
															For(y,t+1,n){
																For(s,y+1,n){
																	For(g,s+1,n){
																		For(h,g+1,n){
																			For(z,h+1,n){
																				if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]+a[r]+a[t]+a[s]+a[g]+a[h]>a[z])ans++;
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//18
	if(n>=19){
		For(i,1,n){
			For(j,i+1,n){
				For(k,j+1,n){
					For(l,k+1,n){
						For(o,l+1,n){
							For(p,o+1,n){
								For(q,p+1,n){
									For(d,q+1,n){
										For(e,d+1,n){
											For(u,e+1,n){
												For(w,u+1,n){
													For(r,w+1,n){
														For(t,r+1,n){
															For(y,t+1,n){
																For(s,y+1,n){
																	For(g,s+1,n){
																		For(h,g+1,n){
																			For(z,h+1,n){
																				For(b,z+1,n){
																					if(a[i]+a[j]+a[k]+a[l]+a[o]+a[p]+a[q]+a[d]+a[e]+a[u]+a[w]+a[r]+a[t]+a[s]+a[g]+a[h]+a[z]>a[b])ans++;
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}	
						}
					}
				}
			}
		}		
	}//19
	if(n==20){
		int num=0;
		For(i,1,19){
			num+=a[i];
		}
		if(num>a[20])
		ans++;
	}
	cout<<ans;                                                                                                                                                                                                       
	return 0;
}
