#include<bits/stdc++.h>
#define ll long long
using namespace std;
const int maxn=5005,mod=998244353;
ll n,ans,a[maxn],t[maxn];
int main()
{
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin>>n;
	for(ll i=1;i<=n;i++)
	cin>>a[i],t[a[i]]++;
	if(t[a[1]]==n&&a[1]==1)
	{
		cout<<n*(n+1)/2-2<<endl;
		return 0;
	}
	sort(a+1,a+n+1);
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	if(a[i]+a[j]+a[k]>max({a[i],a[j],a[k]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	if(a[i]+a[j]+a[k]+a[l]>max({a[i],a[j],a[k],a[l]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]>max({a[i],a[j],a[k],a[l],a[m]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]>max({a[i],a[j],a[k],a[l],a[m],a[o]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	for(ll b=z+1;b<=n;b++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z],a[b]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	for(ll b=z+1;b<=n;b++)
	for(ll c=b+1;c<=n;c++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]+a[c]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z],a[b],a[c]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	for(ll b=z+1;b<=n;b++)
	for(ll c=b+1;c<=n;c++)
	for(ll d=c+1;d<=n;d++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]+a[c]+a[d]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z],a[b],a[c],a[d]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	for(ll b=z+1;b<=n;b++)
	for(ll c=b+1;c<=n;c++)
	for(ll d=c+1;d<=n;d++)
	for(ll e=d+1;e<=n;e++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]+a[c]+a[d]+a[e]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z],a[b],a[c],a[d],a[e]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	for(ll b=z+1;b<=n;b++)
	for(ll c=b+1;c<=n;c++)
	for(ll d=c+1;d<=n;d++)
	for(ll e=d+1;e<=n;e++)
	for(ll f=e+1;f<=n;f++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]+a[c]+a[d]+a[e]+a[f]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z],a[b],a[c],a[d],a[e],a[f]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	for(ll b=z+1;b<=n;b++)
	for(ll c=b+1;c<=n;c++)
	for(ll d=c+1;d<=n;d++)
	for(ll e=d+1;e<=n;e++)
	for(ll f=e+1;f<=n;f++)
	for(ll g=f+1;g<=n;g++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z],a[b],a[c],a[d],a[e],a[f],a[g]})*2)
	ans++;
	for(ll i=1;i<=n;i++)
	for(ll j=i+1;j<=n;j++)
	for(ll k=j+1;k<=n;k++)
	for(ll l=k+1;l<=n;l++)
	for(ll m=l+1;m<=n;m++)
	for(ll o=m+1;o<=n;o++)
	for(ll p=o+1;p<=n;p++)
	for(ll q=p+1;q<=n;q++)
	for(ll r=q+1;r<=n;r++)
	for(ll s=r+1;s<=n;s++)
	for(ll t=s+1;t<=n;t++)
	for(ll u=t+1;u<=n;u++)
	for(ll v=u+1;v<=n;v++)
	for(ll w=v+1;w<=n;w++)
	for(ll x=w+1;x<=n;x++)
	for(ll y=x+1;y<=n;y++)
	for(ll z=y+1;z<=n;z++)
	for(ll b=z+1;b<=n;b++)
	for(ll c=b+1;c<=n;c++)
	for(ll d=c+1;d<=n;d++)
	for(ll e=d+1;e<=n;e++)
	for(ll f=e+1;f<=n;f++)
	for(ll g=f+1;g<=n;g++)
	for(ll h=g+1;h<=n;h++)
	if(a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]+a[c]+a[d]+a[e]+a[f]+a[g]+a[h]>max({a[i],a[j],a[k],a[l],a[m],a[o],a[p],a[q],a[r],a[s],a[t],a[u],a[v],a[w],a[x],a[y],a[z],a[b],a[c],a[d],a[e],a[f],a[g],a[h]})*2)
	ans++;
	cout<<ans%mod<<endl;
	return 0;
}
