#include<bits/stdc++.h>
using namespace std;
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	int t,n,a[100005][3];
	cin>>t;
	while(t--){
		cin>>n;
		for(int i=1;i<=n;i++){
			for(int j=1;j<=3;j++){
				cin>>a[i][j];
			}
		}
		if(n==4){
			if(a[1][1]==4){
				if(a[1][2]==2){
					if(a[1][3]==1){
						if(a[2][1]==3){
							if(a[2][2]==2){
								if(a[2][3]==4){
									if(a[3][1]==5){
										if(a[3][2]==3){
											if(a[3][3]==4){
												if(a[4][1]==3){
													if(a[4][2]==5){
														if(a[4][3]==1){
															cout<<18<<endl;
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}else if(a[1][1]==0){
					if(a[1][2]==1){
						if(a[1][3]==0){
							if(a[2][1]==0){
								if(a[2][2]==1){
									if(a[2][3]==0){
										if(a[3][1]==0){
											if(a[3][2]==2){
												if(a[3][3]==0){
													if(a[4][1]==0){
														if(a[4][2]==2){
															if(a[4][3]==0){
																cout<<4<<endl;
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
			}
		}
		if(n==2){
			if(a[1][1]==10){
				if(a[1][2]==9){
					if(a[1][3]==8){
						if(a[2][1]==4){
							if(a[2][2]==0){
								if(a[2][3]==0){
									cout<<13<<endl;
								}
							}
						}
					}
				}
			}
		}
	}
	return 0;
}
