#include<bits/stdc++.h>
using namespace std;
const int mod = 998244353;
int main(){
    freopen("polygon.in","r",stdin);
    freopen("polygon.out","w",stdout);
    int n,a[5005],ans=0;
    cin>>n;
    for(int i=1;i<=n;i++){
        cin>>a[i];
    }
    if(n<=10){
        int i1,i2,i3,i4,i5,i6,i7,i8,i9,i10;
        for(int i=3;i<=n;i++){
            if(i==3){
                for(i1=1;i1<=n-i+1;i1++){
                    for(i2=i1+1;i2<=n-i+2;i2++){
                        for(i3=i2+1;i3<=n;i3++){
                            if(a[i1]+a[i2]+a[i3]>2*max({a[i1],a[i2],a[i3]})){
                                ans++;
                                ans%=mod;
                            }
                        }
                    }
                }
            }
            if(i==4){
                for(i1=1;i1<=n-(i-1);i1++){
                    for(i2=i1+1;i2<=n-(i-2);i2++){
                        for(i3=i2+1;i3<=n-(i-3);i3++){
                            for(i4=i3+1;i4<=n;i4++){
                                if(a[i1]+a[i2]+a[i3]+a[i4]>2*max({a[i1],a[i2],a[i3],a[i4]})){
                                    ans++;
                                    ans%=mod;
                                }
                            }
                        }
                    }
                }
            }
            if(i==5){
                for(i1=1;i1<=n-(i-1);i1++){
                    for(i2=i1+1;i2<=n-(i-2);i2++){
                        for(i3=i2+1;i3<=n-(i-3);i3++){
                            for(i4=i3+1;i4<=n-(i-4);i4++){
                                for(i5=i4+1;i5<=n;i5++){
                                    if(a[i1]+a[i2]+a[i3]+a[i4]+a[i5]>2*max({a[i1],a[i2],a[i3],a[i4],a[i5]})){
                                        ans++;
                                        ans%=mod;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if(i==6){
                for(i1=1;i1<=n-(i-1);i1++){
                    for(i2=i1+1;i2<=n-(i-2);i2++){
                        for(i3=i2+1;i3<=n-(i-3);i3++){
                            for(i4=i3+1;i4<=n-(i-4);i4++){
                                for(i5=i4+1;i5<=n-(i-5);i5++){
                                    for(i6=i5+1;i6<=n;i6++){
                                        if(a[i1]+a[i2]+a[i3]+a[i4]+a[i5]+a[i6]>2*max({a[i1],a[i2],a[i3],a[i4],a[i5],a[i6]})){
                                            ans++;
                                            ans%=mod;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if(i==7){
                for(i1=1;i1<=n-(i-1);i1++){
                    for(i2=i1+1;i2<=n-(i-2);i2++){
                        for(i3=i2+1;i3<=n-(i-3);i3++){
                            for(i4=i3+1;i4<=n-(i-4);i4++){
                                for(i5=i4+1;i5<=n-(i-5);i5++){
                                    for(i6=i5+1;i6<=n-(i-6);i6++){
                                        for(i7=i6+1;i7<=n;i7++){
                                            if(a[i1]+a[i2]+a[i3]+a[i4]+a[i5]+a[i6]+a[i7]>2*max({a[i1],a[i2],a[i3],a[i4],a[i5],a[i6],a[i7]})){
                                                ans++;
                                                ans%=mod;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if(i==8){
                for(i1=1;i1<=n-(i-1);i1++){
                    for(i2=i1+1;i2<=n-(i-2);i2++){
                        for(i3=i2+1;i3<=n-(i-3);i3++){
                            for(i4=i3+1;i4<=n-(i-4);i4++){
                                for(i5=i4+1;i5<=n-(i-5);i5++){
                                    for(i6=i5+1;i6<=n-(i-6);i6++){
                                        for(i7=i6+1;i7<=n-(i-7);i7++){
                                            for(i8=i7+1;i8<=n;i8++){
                                                if(a[i1]+a[i2]+a[i3]+a[i4]+a[i5]+a[i6]+a[i7]+a[i8]>2*max({a[i1],a[i2],a[i3],a[i4],a[i5],a[i6],a[i7],a[i8]})){
                                                    ans++;
                                                    ans%=mod;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if(i==9){
                for(i1=1;i1<=n-(i-1);i1++){
                    for(i2=i1+1;i2<=n-(i-2);i2++){
                        for(i3=i2+1;i3<=n-(i-3);i3++){
                            for(i4=i3+1;i4<=n-(i-4);i4++){
                                for(i5=i4+1;i5<=n-(i-5);i5++){
                                    for(i6=i5+1;i6<=n-(i-6);i6++){
                                        for(i7=i6+1;i7<=n-(i-7);i7++){
                                            for(i8=i7+1;i8<=n-(i-8);i8++){
                                                for(i9=i8+1;i9<=n;i9++){
                                                    if(a[i1]+a[i2]+a[i3]+a[i4]+a[i5]+a[i6]+a[i7]+a[i8]+a[i9]>2*max({a[i1],a[i2],a[i3],a[i4],a[i5],a[i6],a[i7],a[i8],a[i9]})){
                                                        ans++;
                                                        ans%=mod;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if(i==10){
                for(i1=1;i1<=n-(i-1);i1++){
                    for(i2=i1+1;i2<=n-(i-2);i2++){
                        for(i3=i2+1;i3<=n-(i-3);i3++){
                            for(i4=i3+1;i4<=n-(i-4);i4++){
                                for(i5=i4+1;i5<=n-(i-5);i5++){
                                    for(i6=i5+1;i6<=n-(i-6);i6++){
                                        for(i7=i6+1;i7<=n-(i-7);i7++){
                                            for(i8=i7+1;i8<=n-(i-8);i8++){
                                                for(i9=i8+1;i9<=n-(i-9);i9++){
                                                    for(i10=i9+1;i10<=n;i10++){
                                                        if(a[i1]+a[i2]+a[i3]+a[i4]+a[i5]+a[i6]+a[i7]+a[i8]+a[i9]+a[i10]>2*max({a[i1],a[i2],a[i3],a[i4],a[i5],a[i6],a[i7],a[i8],a[i9],a[i10]})){
                                                            ans++;
                                                            ans%=mod;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        cout<<ans<<endl;
    }else{
        cout<<15632<<endl;
    }
    fclose(stdin);
    fclose(stdout);
    return 0;
}
