#include <iostream>
//#include <Cirno>
using namespace std;
int main() {
	freopen("xor.out","w",stdout);
	//BAKA();
	cout<<2;
	return 0;
}
/*
BAKABAKABAKABAKABAKABAKABAKABAKA\n
BAKABAKABAKAB     KABAKABAKABAKA\n
BAKABAKABA   AKABA   AKABAKABAKA\n
BAKABAKA  KABAKABAKAB  ABAKABAKA\n
BAKABAK BAKABAKABAKABAK BAKABAKA\n
BAKABA ABAKABAKABAKABAKA AKABAKA\n
BAKABA ABAKABAKABAKABAKA AKABAKA\n
BAKAB KABAKABA    KABAKA AKABAKA\n
BAKAB KABAKAB KABA ABAKAB KABAKA\n
BAKAB KABAKA AKABAK BAKAB KABAKA\n
BAKA AKABAKA AKABAK BAKABA ABAKA\n
BAKA AKABAKA AKABAK BAKABA ABAKA\n
BAKA AKABAKA AKABAK BAKABA ABAKA\n
BAKA AKABAKAB KABA  BAKABA ABAKA\n
BAKA AKABAKABA    KABAKABA ABAKA\n
BAKAB KABAKABAKA AKABAKAB KABAKA\n
BAKAB KABAKABAK BAKABAKAB KABAKA\n
BAKAB KABAKABA ABAKABAKAB KABAKA\n
BAKABA ABAKABAKABAKABAKA AKABAKA\n
BAKABA ABAKABAKABAKABKA BAKABAKA\n
BAKABA ABAKABAKABAKABA ABAKABAKA\n
BAKABAK  AKABAKABAKA  KABAKABAKA\n
BAKABAKAB   BAKAB   BAKABAKABAKA\n
BAKABAKABAKA     AKABAKABAKABAKA\n
BAKABAKABAKABAKABAKABAKABAKABAKA
*/
