#include<cstdio>
#include<algorithm>
using namespace std;
int t,n;
struct ss{
	int m1,m2,m3,maxn,club;
}a[100005];
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	scanf("%d",&t);
	while(t--){
		scanf("%d",&n);
		for(int i=1;i<=n;i++){
			scanf("%d%d%d",&a[i].m1,&a[i].m2,&a[i].m3);
			a[i].maxn=max(max(a[i].m1,a[i].m2),a[i].m3);
			if(a[i].maxn==a[i].m1){
				a[i].club=1;
			}
			else if(a[i].maxn==a[i].m2){
				a[i].club=2;
			}
			else{
				a[i].club=3;
			}
		}
		int x=0,y=0,z=0,sss,i,j,k;
		for(sss=1,i=1,j=1,k=1;sss<=n;sss++){
			if(a[sss].club==1){
				if(i<=n/2){
					x+=a[sss].maxn;
					i++;
				}else{
					a[sss].maxn=max(a[sss].m2,a[sss].m3);
					if(a[sss].maxn==a[sss].m2){
						if(j<=n/2){
							a[sss].club=2;
						}else{
							a[sss].club=3;
							a[sss].maxn=a[sss].m3;
						}
					}else{
						if(k<=n/2){
							a[sss].club=3;
						}else{
							a[sss].club=2;
							a[sss].maxn=a[sss].m2;
						}
					}
				}
			}
			if(a[sss].club==2){
				if(j<=n/2){
					y+=a[sss].maxn;
					j++;
				}else{
					a[sss].maxn=max(a[sss].m1,a[sss].m3);
					if(a[sss].maxn==a[sss].m1){
						if(j<=n/2){
							a[sss].club=1;
						}else{
							a[sss].club=3;
							a[sss].maxn=a[sss].m3;
						}
					}else{
						if(k<=n/2){
							a[sss].club=3;
						}else{
							a[sss].club=1;
							a[sss].maxn=a[sss].m1;
						}
					}
				}
			}
			if(a[sss].club==3){
				if(k<=n/2){
					z+=a[sss].maxn;
					k++;
				}else{
					a[sss].maxn=max(a[sss].m1,a[sss].m2);
					if(a[sss].maxn==a[sss].m1){
						if(j<=n/2){
							a[sss].club=1;
						}else{
							a[sss].club=2;
							a[sss].maxn=a[sss].m2;
						}
					}else{
						if(k<=n/2){
							a[sss].club=2;
						}else{
							a[sss].club=1;
							a[sss].maxn=a[sss].m1;
						}
					}
				}
			}
			if(a[sss].club==1){
				if(i<=n/2){
					x+=a[sss].maxn;
					i++;
				}else{
					a[sss].maxn=max(a[sss].m2,a[sss].m3);
					if(a[sss].maxn==a[sss].m2){
						if(j<=n/2){
							a[sss].club=2;
						}else{
							a[sss].club=3;
							a[sss].maxn=a[sss].m3;
						}
					}else{
						if(k<=n/2){
							a[sss].club=3;
						}else{
							a[sss].club=2;
							a[sss].maxn=a[sss].m2;
						}
					}
				}
			}
			if(a[sss].club==2){
				if(j<=n/2){
					y+=a[sss].maxn;
					j++;
				}else{
					a[sss].maxn=max(a[sss].m1,a[sss].m3);
					if(a[sss].maxn==a[sss].m1){
						if(j<=n/2){
							a[sss].club=1;
						}else{
							a[sss].club=3;
							a[sss].maxn=a[sss].m3;
						}
					}else{
						if(k<=n/2){
							a[sss].club=3;
						}else{
							a[sss].club=1;
							a[sss].maxn=a[sss].m1;
						}
					}
				}
			}
		}
		int ans=x+y+z;
		printf("%d",ans);
	}
	return 0;
}
