#include<bits/stdc++.h>
using namespace std;
bool p,f;
long long ann;
int aa[100010],bb[100010],cc[100010];
long long m[10];//she tuan ren shu
long long su,an,x,y,xo,yo;//da an
long long dp1,dp2,dp3;
long long dp[100010];
struct s{
    int a,b,c;
}d[100010];
int t,n;
bool cmp1(s xx,s yy){
    return xx.a>yy.a;
}
bool cmp2(s xx,s yy){
    return xx.b>yy.b;
}
bool cmp3(s xx,s yy){
    return xx.c>yy.c;
}
int main(){
    freopen("club.in","r",stdin);
    freopen("club.out","w",stdout);
    cin>>t;
    while(t--){
        ann=0;
        memset(aa,0,sizeof(aa));
        memset(bb,0,sizeof(bb));
        memset(cc,0,sizeof(cc));
        cin>>n;
        for(int i=1;i<=n;i++){
            cin>>d[i].a>>d[i].b>>d[i].c;
                if(d[i].b!=0||d[i].c!=0){
                    f=1;
                }
        }
        if(f==0){
            for(int i=1;i<=n;i++){
                aa[i]=d[i].a;
            }
            sort(aa+1,aa+n+1);
            for(int i=n;i>n/2;i--){
                ann+=aa[i];
            }
            cout<<ann<<'\n'<<ann;
        }
        else{
            sort(d+1,d+n+1,cmp1);
            dp[1]=d[1].a;
            for(int i=2;i<=n;i++){
                xo=yo=p=0;
                dp[i]=dp[i-1];
                if(d[i].a>d[i].b){
                    if(d[i].a>d[i].c){
                        x=d[i].a;
                        xo=1;
                        p=1;
                    }else{
                        x=d[i].c;
                        xo=3;
                        y=d[i].a;
                        yo=1;
                    }
                    if(p==1){
                        if(d[i].b>d[i].c){
                            y=d[i].b;
                            yo=2;
                        }else{
                            y=d[i].c;
                            yo=3;
                        }
                    }
                }else{
                    if(d[i].b>d[i].c){
                        x=d[i].b;
                        xo=2;
                        p=1;
                    }else{
                        x=d[i].c;
                        xo=3;
                        y=d[i].b;
                        yo=2;
                    }
                    if(p==1){
                        if(d[i].a>d[i].c){
                            y=d[i].a;
                            yo=1;
                        }else{
                            y=d[i].c;
                            yo=3;
                        }
                    }
                }
                if(m[1]==n/2){
                    if(x==d[i].a){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                if(m[2]==n/2){
                    if(x==d[i].b){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                if(m[3]==n/2){
                    if(x==d[i].c){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                dp[i]+=x;
                m[xo]++;
            }
            dp1=dp[n];
            sort(d+1,d+n+1,cmp2);
            dp[1]=d[1].b;
            m[1]=m[2]=m[3]=0;
            for(int i=2;i<=n;i++){
                xo=yo=p=0;
                dp[i]=dp[i-1];
                if(d[i].a>d[i].b){
                    if(d[i].a>d[i].c){
                        x=d[i].a;
                        xo=1;
                        p=1;
                    }else{
                        x=d[i].c;
                        xo=3;
                        y=d[i].a;
                        yo=1;
                    }
                    if(p==1){
                        if(d[i].b>d[i].c){
                            y=d[i].b;
                            yo=2;
                        }else{
                            y=d[i].c;
                            yo=3;
                        }
                    }
                }else{
                    if(d[i].b>d[i].c){
                        x=d[i].b;
                        xo=2;
                        p=1;
                    }else{
                        x=d[i].c;
                        xo=3;
                        y=d[i].b;
                        yo=2;
                    }
                    if(p==1){
                        if(d[i].a>d[i].c){
                            y=d[i].a;
                            yo=1;
                        }else{
                            y=d[i].c;
                            yo=3;
                        }
                    }
                }
                if(m[1]==n/2){
                    if(x==d[i].a){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                if(m[2]==n/2){
                    if(x==d[i].b){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                if(m[3]==n/2){
                    if(x==d[i].c){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                dp[i]+=x;
                m[xo]++;
            }
            dp2=dp[n];
            sort(d+1,d+n+1,cmp3);
            dp[1]=d[1].c;
            m[1]=m[2]=m[3]=0;
            for(int i=2;i<=n;i++){
                xo=yo=p=0;
                dp[i]=dp[i-1];
                if(d[i].a>d[i].b){
                    if(d[i].a>d[i].c){
                        x=d[i].a;
                        xo=1;
                        p=1;
                    }else{
                        x=d[i].c;
                        xo=3;
                        y=d[i].a;
                        yo=1;
                    }
                    if(p==1){
                        if(d[i].b>d[i].c){
                            y=d[i].b;
                            yo=2;
                        }else{
                            y=d[i].c;
                            yo=3;
                        }
                    }
                }else{
                    if(d[i].b>d[i].c){
                        x=d[i].b;
                        xo=2;
                        p=1;
                    }else{
                        x=d[i].c;
                        xo=3;
                        y=d[i].b;
                        yo=2;
                    }
                    if(p==1){
                        if(d[i].a>d[i].c){
                            y=d[i].a;
                            yo=1;
                        }else{
                            y=d[i].c;
                            yo=3;
                        }
                    }
                }
                if(m[1]==n/2){
                    if(x==d[i].a){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                if(m[2]==n/2){
                    if(x==d[i].b){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                if(m[3]==n/2){
                    if(x==d[i].c){
                        dp[i]+=y;
                        m[yo]++;
                        continue;
                    }else{
                        dp[i]+=x;
                        m[xo]++;
                        continue;
                    }
                }
                dp[i]+=x;
                m[xo]++;
            }
            dp3=dp[n];
            cout<<max(dp1,max(dp2,dp3))<<'\n';
        }
    }
    return 0;
}
