#include<bits/stdc++.h>
using namespace std;

string s;
int a[20],b[1010],x;

int main()
{
    freopen("number.in","r",stdin);
    freopen("number.out","w",stdout);
    cin>>s;
    for(int i=0;i<s.size();i++)
    {
        if(s[i]=='1')
        {
            a[1]++;
        }
        if(s[i]=='2')
        {
            a[2]++;
        }
        if(s[i]=='3')
        {
            a[3]++;
        }
        if(s[i]=='4')
        {
            a[4]++;
        }
        if(s[i]=='5')
        {
            a[5]++;
        }
        if(s[i]=='6')
        {
            a[6]++;
        }
        if(s[i]=='7')
        {
            a[7]++;
        }
        if(s[i]=='8')
        {
            a[8]++;
        }
        if(s[i]=='9')
        {
            a[9]++;
        }
        if(s[i]=='0')
        {
            a[0]++;
        }
    }
    for(int i=1;i<=1000;i++)
    {
        if(a[9]>0)
        {
            b[i]=9;
            a[9]--;
        }
        else
        {
            if(a[8]>0)
            {
                b[i]=8;
                a[8]--;
            }
            else
            {
                if(a[7]>0)
                {
                    b[i]=7;
                    a[7]--;
                }
                else
                {
                    if(a[6]>0)
                    {
                        b[i]=6;
                        a[6]--;
                    }
                    else
                    {
                        if(a[5]>0)
                        {
                            b[i]=5;
                            a[5]--;
                        }
                        else
                        {
                            if(a[4]>0)
                            {
                                b[i]=4;
                                a[4]--;
                            }
                            else
                            {
                                if(a[3]>0)
                                {
                                    b[i]=3;
                                    a[3]--;
                                }
                                else
                                {
                                    if(a[2]>0)
                                    {
                                        b[i]=2;
                                        a[2]--;
                                    }
                                    else
                                    {
                                        if(a[1]>0)
                                        {
                                            b[i]=1;
                                            a[1]--;
                                        }
                                        else
                                        {
                                            if(a[0]>0)
                                            {
                                                b[i]=0;
                                                a[0]--;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        x++;
        if(a[0]==0 && a[1]==0 && a[2]==0 && a[3]==0 && a[4]==0 && a[5]==0 && a[6]==0 && a[7]==0 && a[8]==0 && a[9]==0)
        {
            break;
        }
    }
    for(int i=1;i<=x;i++)
    {
        cout<<b[i];
    }

    fclose(stdin);
    fclose(stdout);
    return 0;
}
