#include<bits/stdc++.h>
#define int long long
using namespace std;
int n,Q;
string s[200005][3],t[3];
signed main()
{
//	freopen("replace.in","r",stdin);
//	freopen("replace.out","w",stdout);

	freopen("replace.in","r",stdin);
	freopen("replace.out","w",stdout);
	ios::sync_with_stdio(0);
	cin.tie(0);
	cout.tie(0);
	cin>>n>>Q;
	for(int i=1;i<=n;i++){
		cin>>s[i][1]>>s[i][2];
	}
	while(Q--){
		cin>>t[1]>>t[2];
		cout<<0<<"\n";
	}
	return 0;
}
//qupingjiwangtingzhibucongye,chanchanzhibimingye,xiequzhihaigongye,fangzhengzhiburongye,guyouchouyousiyizuolisao
//lisaozhe,youliyouye.futianzhe,renzhishinye.fumuzhe,renzhibenye.renqiongzefanben,gulaokujuanji,weichangbuhutianye;jitongcanda,weichangbuhufumuye.
//qupingzhengdaozhixing,jiezhongjinzhiyishiqijun,chanrenjianzhi,keweiqiongyi.xinerjianyi,zhongewrbeibang,nengwuyuanhu?qupingzhizuolisao,gaiziyuanshengye.
//guofenghaoseerbuyin,xiaoyayuanfeierbuluan,ruolisaozhe,keweijianzhiyi.shangchengdiku,xiadaoqihuan,zhongshutangwu,yicishishi.
//mingdaodezhiguanchong,zhiluanzhitiaoguan,mibubuxian.qiwenyue,qiciwei,qizhijie,qixinglian.qichengwenxiaoerqizhijida,juleiererjianyiyuan.qizhijie,guqichengwufang;qixinglian,gusierburong.
//zishuzhuonaowunizhizhong,yicuyouchenaizhiwai,bihuoshizhizigou,xiaorannieerbuzizheye.tuicizhiye,suiyuriyuezhengguankeye.

//hanjiayanchenzaidongbei,hanjiangcijiapocanzei.nanerbenzizhonghengxing,tianzifeichangciyanse.chuangjinfaguxiayuguan,jingpeiweiyijieshijian.xiaofeiyushufeihanhai,shanyuliehuozhaolangshan.
//shanchuanxiaotiaojibiantu,hujipinglingzafengyu.zhanshijunqianbansisheng,meirenzhangxiayougewu.damoqiongqiusaicaofei,guchengluoridoubingxi.shendangeryuchangqingdi,lijinguanshanweijiewei.
//tieyiyuanshuxinqinjiu,yuzhuyingtibielihou.shaofuchennanyuduanchang,zhengrenjibeikonghuishou.biantingpiaoyaonakedu,jueyucangmangwusuoyou.shaqisanshizuozhenyun,hanshengyiyechuandiaodou.
//xiangkanbairenxuefenfen,sijieconglaiqiguxun?junbujianshachangzhengzhanku,zhijinyouyilijiangjun.

//jinsewuduanwushixian,yixianyizhusihuanian.zhuangshengxiaomengmihudie,wangdichunxintuodujuan.canghaiyuemingzhuyoulei,lantianrinuanyushengyan.ciqingkedaichengzhuiyi,zhishidangshiyiwangran.

//chunjiangchaoshuilianhaiping,haishangmingyuegongchaosheng.yanyansuiboqianwanli,hechuchunjiangwuyueming?jianliuwanzhuanraofangdian,yuezhaohualinjiesixian.kongliliushuangbujuefei,tingshangbaishakanbujian.
//jiangtianyisequxianchen,jiaojiaokongzhongguyuelun.jiangpanherenchujianyue?jiangyuehenianchuzhaoren?renshengdaidaiwuqiongyi,jiangyueniannianwangxiangsi.buzhijiangyuedaiheren,danjianchangjiangsongliushui.
//baiyunyipianquyouyou,qingfengbushangbushengchou.sheijiajinyepianzhouzi,hechuxiangsimingyuelou?kelianloushangyuepaihuai,yingzhaolirenzhuangjingtai.yuhulianzhongjianbuqu,daoyizhenshangfuhuanlai.
//cishixiangwangbuxiangwen,yuanzhuyuehualiuzhaojun.hongyanchangfeiguangbudu,yulongqianyueshuichengwen.zuoyexiantanmengluohua,kelianchunbanbuhuanjia.jiangshuiliuchunquyujin,jiangtanluoyuefuxixia.
//xieyueshenshencanghaiwu,jieshixiaoxiangwuxianlu.buzhichengyuejirengui,luoyueyaoqingmanjiangshu.

//zaosuinazhishishijian,zhongyuanbeiwangqirushan.louchuanyuexueguazhoudu,tiemaqiufengdasanguan.saishangchangchengkongzixu,jingshongshuaibinyixianban.chushiyibiaozhenmingshi,qianzaisheikanbozhongjian?

//wusishutongzhanggaoqiu,kongshanningyuntuibuliu.jiang'etizhusunvchou,lipingzhongguotankonghou.kunshanyusuifenghuangjiao,furongqiluxianglanxiao.shiermenqianronglengguang,ershisansidongzihuang.
//nvwalianshibutianchu,shipotianjingdouqiuyu.mengrushenshaojiaoshenyu,laoyutiaoboshoujiaowu.wuzhibumianyiguishu,lujiaoxiefeishihantu.

//wenchangyingheshirushou,fujiangrongzhu?weibirenjianwuhaohan,sheiyukuanxiechidu?shikanqudangnianhanwu.qiyouguchenggongfushou,yebugancengyulishanmu.tanxiaoqi,lianghelu.
//shaoshiqituocenglianju,tanerjindengloulanjing,shijipinwu.wenshuobeifengchuimianji,bianshangchongtilvwu.junmodaotoubianxuyu.ziguyixiannengzhinan,youjintangbiankewuzhangxu?kuaitoubi,motizhu.

//dongfengyefanghuaqianshu,gengchuiluo,xingruyu.baomadiaochexiangmanlu.fengxiaoshengdong,yuhuguanzhuan,yiyeyulongwu.
//eerxueliuhuangjinlv,xiaoyuyingyinganxiangqu.zhonglixuntaqianbaidu,muranhuishou,narenquezai,denghuolanshanchu.

//?????,?????.xibeiwangcahngan,kelianwushushan.qingshanzhebuzhu,bijingdongliuqu.jianwangzhengchouyu,shanshenwenzhegu.

//junbujianhuanghezhishuitianshanglai,benliudaohaibufuhui.junbujiangaotangmingjingbeibafa,zhaoruqingsimuchengxue.renshengdeyixujinhuan,moshijinzuikongduiyue.tianshengwocaibiyouyong,qianjinsanjinhuanfulai.pengyangzainiuqieweile,huixuyiyinsanbaibei.
//cenfuzi,danqiusheng,qiangjinjiu,beimoting.yujungeyiqu,qingjunweiwoqingerting.zhongguzhuanyubuzugui,danyuanchangzuibuyuanxing.gulaishengxianjiejimo,weiyouyinzheliuqiming.chenwangxishiyanpingle,douqiushiqianzihuanxue.zhurenheweiyanshaoqian,jingxuguquduiyunzhuo.wuhuama,qianjinqiu,huerjiangchuhuanmeijiu,yuertongxiaowanguchou.

//haiketanyingzhou,yantaoweimangxinnanqiu.yuerenyutianmu,yunxiamingmiehuokedu.tianmuliantianxiangtianheng,shibawuyueyanchicheng.tiantaisiwanbaqianzhang,duiciyudaodongnanqing.
//woyuyinzhimengwuyue,yiyefeidujinghuyue.huyuezhaowoying,songwozhishanxi.xiegongsuchujinshangzai,lushuidangyangqingyuanti.jiaozhuxiegongji,shendengqingyunti.banbijianhairi,kongzhongwentianji.
//qianyanwanzhuanlubuding,mihuayishihuyiming.xiongpaolongyinyinyanquan,lishenlinxijingchengdian.yunqingqingxiyuyu,shuidandanxishengyan.liequepili,qiuluanpengcui.dongtianshifei,hongranzhongkai.
//qingminghaodangbujiandi,riyuezhaoyaojinyintai.niweiyisifengweima,yunzhijunxifenfenerlaixia.hugusexiluanhuiche,xianzhirenxilieruma.huhunjiyipodong,huangjingqierchangjie.weijiaoshizhizhenxi,shixianglaizhiyanxia.
//shijianxingleyiruci,gulaiwanshidongliushui.biejunquxiheshihuan?qiefangbailuqingyajian,xuxingjiqifangmingshan.annengcuimeizheyaoshiquangui,shiwobudekaixinyan?

//xunyangjiangtouyesongke,fengyedihuaqiusese.zhurenxiamakezaichuan,jujiuyuyinwuguanxian.zuibuchenghuancanjiangbie,bieshimangmangjiangjinyue.
//huwenshuishangpipasheng,zhurenwangguikebufa.xunshenganwentanzheshei,pipashengtingyuyuchi.yichuanxiangjinyaoxiangjian,tianjiuhuidengchongkaiyan.qianhuwanhuanshichulai,youbaopipabanzhemian.zhuanzhouboxiansanliangsheng,weishengqudiaoxianyouqing.xianxianyanyishengshengsi,sisupingshengbudezhi.dimeixinshouxuxutan,shuojinxinzhognwuxianshi.
//qinglongmannianmofutiao,chuweinichanghouliuyao.daxiancaocaorujiyu,xiaoxianqieqierusiyu.caocaoqieqiecuozatan,dazhuxiaozhuluoyupan.jianguanyingyuhuadihua,youyequanliubingjianan.bingquanlengsexianningjue,ningjuebutongshengzanxie.bieyouyouchouanhensheng,cishiwushengshengyousheng.quzhongshoubodangxinhua,sixianyishengruliebo.dongchuanxifangqiaowuyan,weijianjiangxinqiuyuebai.
//chenyinfangbochaxianzhong,zhengdunyichangqilianrong.ziyanbenshijingchengnv,jiazaihamalingxiazhu.shisanxuedepipacheng,mingshujiaofangdiyibu.qubacengjiaoshancaifu,zhuangchengmeibeiqiuniangdu.wulingnianshaozhengchantou,yiquhongxiaobuzhishu.jinnianhuanxiaofumingnian,qiuyuechunfengdengxiandu.dizoucongjunayisi,muquzhaolaiyansegu.menqianlengluoanmaxi,laodajiazuoshangrenfu.shangrenzhongliqingbieli,qianyuefuliangmaichaqu.qulaijiangkoushoukongchuan,raochuanyuemingjiangshuihan.yeshenhumengshaonianshi,mengtizhuangleihonglangan.
//wowenpipayitanxi,youwenciyuchongjiji.tongshitianyalunluoren,xiangfenghebicengxiangshi?wocongquniancidijing,zhejuwobingxunyangcheng.xunyangdipiwuyinyue,zhongsuibuwensizhusheng.zhujinpenjiangdidishi,huanglukuzhuraozhaisheng.qijiandanmuwenhewu?dujuantixueyuanaiming.qiwushangeyucundi?ouyazhaozhananweiting.jinritingjunpipayu,rutingxianyueerzanming.mocigengzuotanyiqu,weijunfanzuopipaxing.
//ganwociyanliangjiuli,quezuocuxianxianzhuanji.qiqibusixiangqiansheng,manzuochongwenjieyanqi.zuozhongqixiasheizuiduo?jiangzhousimaqingshanshi.

