#include<bits/stdc++.h>
using namespace std;
typedef long long ll;
typedef pair<int,int> pii;
#define fi first
#define se second
#define pb push_back
#define add(u,v,w) tu[(u)].pb({(v),(w)})
#define forr(x,y) for(int i=x;i<=y;i++)
#define endl '\n'
const int inf=0x3f3f3f3f;
const ll infll=0x3f3f3f3f3f3f3f3f;
int main(){
	freopen("replace.in","r",stdin);
	freopen("replace.out","w",stdout);
	ios::sync_with_stdio(0),cin.tie(0),cout.tie(0);
	while(1); 
	return 0;
} 
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
//CCF is good
