#include<bits/stdc++.h>
using namespace std;
long long T,n,a,b,c,cnt,f;
long long d[100010],q[100010],p[100010],x[100010],y[100010],z[100010],h[100010],s[100010];
bool cmp(long long a,long long b){
	return a>b;
}
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	ios::sync_with_stdio(0);
	cin.tie(0);
	cout.tie(0);
	cin>>T;
	while(T--){
		memset(d,0,sizeof(d));
		memset(q,0,sizeof(q));
		memset(p,0,sizeof(p));
		memset(x,0,sizeof(x));
		memset(y,0,sizeof(y));
		memset(z,0,sizeof(z));
		memset(h,0,sizeof(h));
		memset(s,0,sizeof(s));
		cnt=0;
		cin>>n;
		for(long long i=1;i<=n;i++){
			cin>>a>>b>>c;
			d[i]=max(max(a,b),c);
			if(d[i]==a){
				q[i]=max(b,c);
				p[i]=min(b,c);
				s[d[i]]=1;
				s[q[i]]=1;
				s[p[i]]=1;
			}
			else{
				if(d[i]==b){
					q[i]=max(a,c);
					p[i]=min(a,c);
					s[d[i]]=2;
					s[q[i]]=2;
				    s[p[i]]=2;
				}
				else{
					q[i]=max(a,b);
					p[i]=min(a,b);
					s[d[i]]=3;
					s[q[i]]=3;
				    s[p[i]]=3;
				}
			}
		}
		for(long long i=1;i<=n;i++){
			//cout<<'@'<<d[i]<<endl;
			if(s[d[i]]==1){
				f=1;
			}
			else{
				if(s[d[i]]==2){
					f=2;
				}
				else{
					f=3;
				}
			}
			//cout<<'^'<<h[f]<<' '<<f<<endl;
			if(h[f]<n/2){
				if(f==1){
					x[++h[f]]=d[i];
					sort(x+1,x+h[f]+1,cmp);
				}
				else{
					if(f==2){
						y[++h[f]]=d[i];
						sort(y+1,y+h[f]+1,cmp);
					}
					else{
						z[++h[f]]=d[i];
						sort(z+1,z+h[f]+1,cmp);
					}
				}
				//cout<<"&&&&"<<d[i]<<' '<<cnt<<endl;
				cnt+=d[i];
			}
			else{
				if(f==1){
					if(x[h[f]]<d[i]){
						if(h[q[s[x[h[f]]]]]<n/2){
							if(q[s[x[h[f]]]]==1){
								x[++h[q[s[x[h[f]]]]]]=d[i];
								sort(x+1,x+h[q[s[x[h[f]]]]]+1,cmp);
							}
							else{
								if(q[s[x[h[f]]]]==2){
									y[++h[q[s[x[h[f]]]]]]=d[i];
									sort(y+1,y+h[q[s[x[h[f]]]]]+1,cmp);
								}
								else{
									z[++h[q[s[x[h[f]]]]]]=d[i];
									sort(z+1,z+h[q[s[x[h[f]]]]]+1,cmp);
								}
							}
							cnt+=q[i];
						}
						else{
							if(p[s[x[h[f]]]]==1){
								x[++h[p[s[x[h[f]]]]]]=d[i];
								sort(x+1,x+h[p[s[x[h[f]]]]]+1,cmp);
							}
							else{
								if(p[s[x[h[f]]]]==2){
									y[++h[p[s[x[h[f]]]]]]=d[i];
									sort(y+1,y+h[p[s[x[h[f]]]]]+1,cmp);
								}
								else{
									z[++h[p[s[x[h[f]]]]]]=d[i];
									sort(z+1,z+h[p[s[x[h[f]]]]]+1,cmp);
								}
							}
							cnt+=p[i];
						}
						cnt-=x[h[f]];
						//cout<<"**"<<x[h[f]]<<endl;
						x[h[f]]=d[i];
						cnt+=d[i];
						sort(x+1,x+h[f]+1,cmp);
					}
					//cout<<'('<<cnt<<endl;
				}
				else{
					if(f==2){
						if(y[h[f]]<d[i]){
							if(h[q[s[y[h[f]]]]]<n/2){
								if(q[s[y[h[f]]]]==1){
									x[++h[q[s[y[h[f]]]]]]=d[i];
									sort(x+1,x+h[q[s[y[h[f]]]]]+1,cmp);
								}
								else{
									if(q[s[y[h[f]]]]==2){
										y[++h[q[s[y[h[f]]]]]]=d[i];
										sort(y+1,y+h[q[s[y[h[f]]]]]+1,cmp);
									}
									else{
										z[++h[q[s[y[h[f]]]]]]=d[i];
										sort(z+1,z+h[q[s[y[h[f]]]]]+1,cmp);
									}
								}
								cnt+=q[i];
							}
							else{
								if(p[s[y[h[f]]]]==1){
									x[++h[p[s[y[h[f]]]]]]=d[i];
									sort(x+1,x+h[p[s[y[h[f]]]]]+1,cmp);
								}
								else{
									if(p[s[y[h[f]]]]==2){
										y[++h[p[s[y[h[f]]]]]]=d[i];
										sort(y+1,y+h[p[s[y[h[f]]]]]+1,cmp);
									}
									else{
										z[++h[p[s[y[h[f]]]]]]=d[i];
										sort(z+1,z+h[p[s[y[h[f]]]]]+1,cmp);
									}
								}
								cnt+=p[i];
							}
							cnt-=y[h[f]];
							//cout<<"**"<<y[h[f]]<<endl;
							y[h[f]]=d[i];
							cnt+=d[i];
							sort(y+1,y+h[f]+1,cmp);
						}
						//cout<<'('<<cnt<<endl;
					}
					else{
						if(z[h[f]]<d[i]){
							if(h[q[s[z[h[f]]]]]<n/2){
								if(q[s[z[h[f]]]]==1){
									x[++h[q[s[z[h[f]]]]]]=d[i];
									sort(x+1,x+h[q[s[z[h[f]]]]]+1,cmp);
								}
								else{
									if(q[s[z[h[f]]]]==2){
										y[++h[q[s[z[h[f]]]]]]=d[i];
										sort(y+1,y+h[q[s[z[h[f]]]]]+1,cmp);
									}
									else{
										z[++h[q[s[z[h[f]]]]]]=d[i];
										sort(z+1,z+h[q[s[z[h[f]]]]]+1,cmp);
									}
								}
								cnt+=q[i];
							}
							else{
								if(p[s[z[h[f]]]]==1){
									x[++h[p[s[z[h[f]]]]]]=d[i];
									sort(x+1,x+h[p[s[z[h[f]]]]]+1,cmp);
								}
								else{
									if(p[s[z[h[f]]]]==2){
										y[++h[p[s[z[h[f]]]]]]=d[i];
										sort(y+1,y+h[p[s[z[h[f]]]]]+1,cmp);
									}
									else{
										z[++h[p[s[z[h[f]]]]]]=d[i];
										sort(z+1,z+h[p[s[z[h[f]]]]]+1,cmp);
									}
								}
								cnt+=p[i];
							}
							cnt-=z[h[f]];
							//cout<<"**"<<z[h[f]]<<endl;
							z[h[f]]=d[i];
							cnt+=d[i];
							sort(z+1,z+h[f]+1,cmp);
						}
						//cout<<'('<<cnt<<endl;
					}
				}
				//cout<<'$'<<cnt<<endl;
			}
		}
		cout<<cnt<<endl;
	}
}
