#include<bits/stdc++.h>
using namespace std;
struct jj{
	int a,b,c;
};
int op()
{
    int t,n,i,j,a1,b1,c1,a2,b2,c2,k,u;
	cin>>n;
	jj a[201]={},b[201]={},c[201]={};
   	a1=b1=c1=0;
   	for(i=1;i<=n;i++){
   	    cin>>a2>>b2>>c2;
   	    if(a2>=b2&&a2>=c2){
   	        a1+=1;
   	        a[a1].a=a2;
            a[a1].b=b2;
			a[a1].c=c2;
		}
		if(b2>a2&&b2>c2){
   	        b1+=1;
   	        b[b1].b=b2;
   	        b[b1].a=a2;
			b[b1].c=c2;
		}
		if(c2>b2&&c2>a2){
   	        c1+=1;
   	        c[c1].c=c2;
			c[c1].b=b2;
			c[c1].a=a2;
		}
	}
	if(a1>n/2){
	   	u=a1-n;
	   	for(i=1;i<=u;i++){
	   		t=1;
	   		for(j=2;j<=a1;j++){
	   			if(min(a[j].a-a[j].b,a[j].a-a[j].c)<min(a[t].a-a[t].b,a[t].a-a[t].c)){
	   				t=j;
				}
			}
			if(a[t].a-a[t].b<=a[t].a-a[t].c){
				b[b1+1].a=a[t].a;
				b[b1+1].b=a[t].b;
				b[b1+1].c=a[t].c;
				for(k=t;k<=a1;k++){
					a[k].a=a[k+1].a;
					a[k].b=a[k+1].b;
					a[k].c=a[k+1].c;
				}
				a1-=1;
				b1+=1;
			}
			if(a[t].a-a[t].c<a[t].a-a[t].b){
				c[c1+1].a=a[t].a;
				c[c1+1].b=a[t].b;
				c[c1+1].c=a[t].c;
				for(k=t;k<=a1;k++){
					a[k].a=a[k+1].a;
					a[k].b=a[k+1].b;
					a[k].c=a[k+1].c;
				}
				c1+=1;
				a1-=1;
			}
		}
	}
	if(b1>n/2){
	   	u=b1-n;
	   	for(i=1;i<=u;i++){
	   		t=1;
	   		for(j=2;j<=b1;j++){
	   			if(min(b[j].b-b[j].a,b[j].b-b[j].c)<min(b[t].b-b[t].a,b[t].b-b[t].c)){
	   				t=j;
				}
			}
			if(b[t].b-b[t].a<=b[t].b-b[t].c){
				a[a1+1].a=b[t].a;
				a[a1+1].b=b[t].b;
				a[a1+1].c=b[t].c;
				for(k=t;k<=b1;k++){
					b[k].a=b[k+1].a;
					b[k].b=b[k+1].b;
					b[k].c=b[k+1].c;
				}
				b1-=1;
				a1+=1;
			}
			if(b[t].b-b[t].c<b[t].b-b[t].a){
				c[c1+1].a=b[t].a;
				c[c1+1].b=b[t].b;
	     		c[c1+1].c=b[t].c;
				for(k=t;k<=b1;k++){
					b[k].a=b[k+1].a;
					b[k].b=b[k+1].b;
					b[k].c=b[k+1].c;
				}
				c1+=1;
				b1-=1;
			}
		}
	}
	if(c1>n/2){
	   	u=c1-n;
	   	for(i=1;i<=u;i++){
	   		t=1;
	   		for(j=2;j<=c1;j++){
	   			if(min(c[j].c-c[j].b,c[j].c-c[j].a)<min(c[t].c-c[t].b,c[t].c-c[t].a)){
	   				t=j;
				}
			}
			if(c[t].c-c[t].b<=c[t].c-c[t].a){
				b[b1+1].a=c[t].a;
				b[b1+1].b=c[t].b;
				b[b1+1].c=c[t].c;
				for(k=t;k<=c1;k++){
					c[k].a=c[k+1].a;
					c[k].b=c[k+1].b;
					c[k].c=c[k+1].c;
				}
				c1-=1;
				b1+=1;
			}
			if(c[t].c-c[t].a<c[t].c-c[t].b){
				a[c1+1].a=c[t].a;
				a[c1+1].b=c[t].b;
				a[c1+1].c=c[t].c;
				for(k=t;k<=c1;k++){
					c[k].a=c[k+1].a;
					c[k].b=c[k+1].b;
					c[k].c=c[k+1].c;
				}
				a1+=1;
				c1-=1;
			}
		}
	}
	t=0;
	for(i=1;i<=a1;i++){
		t+=a[i].a;
	}
	for(i=1;i<=b1;i++){
		t+=b[i].b;
	}
	for(i=1;i<=c1;i++){
		t+=c[i].c;
	}
	cout<<t<<endl;
	return 0;
}
int main()
{
    freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
    int t,i;
    cin>>t;
    for(i=1;i<=t;i++){
   	    op();
    }
}