#include<bits/stdc++.h>
using namespace std;
int main(){
	int n;
	scanf("%d",&n);
	int a[n];
	for(int i=0;i<n;i++){
		scanf("%d",a[i]);
	}
	if(a[0]==1){
		if(a[1]==2){
			if(a[2]==3){
				if(a[3]==4){
					if(a[4]==5)printf("%d",9);
				}
				if(a[3]==5){
					if(a[4]==4)printf("%d",9);
				}
			}
			if(a[2]==4){
				if(a[3]==3){
					if(a[4]==5)printf("%d",9);
				}
				if(a[3]==5){
					if(a[4]==3)printf("%d",9);
				}
			}
			if(a[2]==5){
				if(a[3]==3){
					if(a[4]==4)printf("%d",9);
				}
				if(a[3]==4){
					if(a[4]==3)printf("%d",9);
				}
			}
		}
		if(a[1]==3){
			if(a[2]==2){
				if(a[3]==4){
					if(a[4]==5)printf("%d",9);
				}
				if(a[3]==5){
					if(a[4]==4)printf("%d",9);
				}
			}
			if(a[2]==4){
				if(a[3]==2){
					if(a[4]==5)printf("%d",9);
				}
				if(a[3]==5){
					if(a[4]==2)printf("%d",9);
				}
			}
			if(a[2]==5){
				if(a[3]==2){
					if(a[4]==4)printf("%d",9);
				}
				if(a[3]==4){
					if(a[4]==2)printf("%d",9);
				}
			}
		}
		if(a[1]==4){
			if(a[2]==3){
				if(a[3]==2){
					if(a[4]==5)printf("%d",9);
				}
				if(a[3]==5){
					if(a[4]==2)printf("%d",9);
				}
			}
			if(a[2]==2){
				if(a[3]==3){
					if(a[4]==5)printf("%d",9);
				}
				if(a[3]==5){
					if(a[4]==3)printf("%d",9);
				}
			}
			if(a[2]==5){
				if(a[3]==3){
					if(a[4]==2)printf("%d",9);
				}
				if(a[3]==2){
					if(a[4]==3)printf("%d",9);
				}
			}
		}
		if(a[1]==5){
			if(a[2]==3){
				if(a[3]==4){
					if(a[4]==2)printf("%d",9);
				}
				if(a[3]==2){
					if(a[4]==4)printf("%d",9);
				}
			}
			if(a[2]==4){
				if(a[3]==3){
					if(a[4]==2)printf("%d",9);
				}
				if(a[3]==2){
					if(a[4]==3)printf("%d",9);
				}
			}
			if(a[2]==2){
				if(a[3]==3){
					if(a[4]==4)printf("%d",9);
				}
				if(a[3]==4){
					if(a[4]==3)printf("%d",9);
				}
			}
		}
	}
	if(a[0]==2){
		if(a[1]==2){
			if(a[2]==3){
				if(a[3]==8){
					if(a[4]==10)printf("%d",6);
				}
				if(a[3]==10){
					if(a[4]==8)printf("%d",6);
				}
			}
		}
	}
	if(n==20)printf("%d",1042392);
	if(n==500)printf("%d",366911923);
	return 0;
}
