#include<bits/stdc++.h>
using namespace std;
const int Mod = 998244353;
int n,a[5005],nums,sumss,maxxx;
int main(){
	freopen("polygon.in","r",stdin);
	freopen("polygon.out","w",stdout);
	cin >> n;
	for(int i = 1;i <= n;i ++){
		cin >> a[i];
		sumss += a[i];
		maxxx = max(maxxx,a[i]);
	}
	sort(a + 1,a + n + 1);
	if(n == 3){
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
		return 0;
	}
	else if(n == 4){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 5){
		for(int i = 1;i <= n-2;i ++)
			for(int j = i + 1;j <= n-1;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n-3;i ++)
			for(int j = i + 1;j <= n-2;j ++)
				for(int k = j + 1;k <= n-1;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 6){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 7){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 8){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 9){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 10){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 11){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 12){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 13){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 14){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],a[v]))))))))))))))
																nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 15){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],a[v]))))))))))))))
																nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],a[w])))))))))))))))
																	nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 16){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],a[v]))))))))))))))
																nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],a[w])))))))))))))))
																	nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],a[x]))))))))))))))))
																		nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 17){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],a[v]))))))))))))))
																nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],a[w])))))))))))))))
																	nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],a[x]))))))))))))))))
																		nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],a[y])))))))))))))))))
																			nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 18){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],a[v]))))))))))))))
																nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],a[w])))))))))))))))
																	nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],a[x]))))))))))))))))
																		nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],a[y])))))))))))))))))
																			nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		for(int z = y + 1;z <= n;z ++)
																			if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],max(a[y],a[z]))))))))))))))))))
																				nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 19){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],a[v]))))))))))))))
																nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],a[w])))))))))))))))
																	nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],a[x]))))))))))))))))
																		nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],a[y])))))))))))))))))
																			nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		for(int z = y + 1;z <= n;z ++)
																			if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],max(a[y],a[z]))))))))))))))))))
																				nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		for(int z = y + 1;z <= n;z ++)
																			for(int b = z + 1;b <= n;b ++)
																				if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],max(a[y],a[z]))))))))))))))))))
																					nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else if(n == 20){
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					if((a[i]+a[j]+a[k])>2*(max(a[i],max(a[j],a[k]))))
						nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						if((a[i]+a[j]+a[k]+a[l])>2*(max(a[i],max(a[j],max(a[k],a[l])))))
							nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							if((a[i]+a[j]+a[k]+a[l]+a[m])>2*(max(a[i],max(a[j],max(a[k],max(a[l],a[m]))))))
								nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],a[o])))))))
									nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],a[p]))))))))
										nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],a[q])))))))))
											nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],a[r]))))))))))
												nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],a[s])))))))))))
													nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],a[t]))))))))))))
														nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],a[u])))))))))))))
															nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],a[v]))))))))))))))
																nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],a[w])))))))))))))))
																	nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																		if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],a[x]))))))))))))))))
																			nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																			if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],a[y])))))))))))))))))
																				nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		for(int z = y + 1;z <= n;z ++)
																			if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],max(a[y],a[z]))))))))))))))))))
																				nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		for(int z = y + 1;z <= n;z ++)
																			for(int b = z + 1;b <= n;b ++)
																				if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],max(a[y],max(a[b],a[z])))))))))))))))))))
																					nums ++;
		for(int i = 1;i <= n;i ++)
			for(int j = i + 1;j <= n;j ++)
				for(int k = j + 1;k <= n;k ++)
					for(int l = k + 1;l <= n;l ++)
						for(int m = l + 1;m <= n;m ++)
							for(int o = m + 1;o <= n;o ++)
								for(int p = o + 1;p <= n;p ++)
									for(int q = p + 1;q <= n;q ++)
										for(int r = q + 1;r <= n;r ++)
											for(int s = r + 1;s <= n;s ++)
												for(int t = s + 1;t <= n;t ++)
													for(int u = t + 1;u <= n;u ++)
														for(int v = u + 1;v <= n;v ++)
															for(int w = v + 1;w <= n;w ++)
																for(int x = w + 1;x <= n;x ++)
																	for(int y = x + 1;y <= n;y ++)
																		for(int z = y + 1;z <= n;z ++)
																			for(int b = z + 1;b <= n;b ++)
																				for(int c = b + 1;c <= n;c ++)
																					if((a[i]+a[j]+a[k]+a[l]+a[m]+a[o]+a[p]+a[q]+a[r]+a[s]+a[t]+a[u]+a[v]+a[w]+a[x]+a[y]+a[z]+a[b]+a[c])>2*(max(a[i],max(a[j],max(a[k],max(a[l],max(a[m],max(a[o],max(a[p],max(a[q],max(a[r],max(a[s],max(a[t],max(a[u],max(a[v],max(a[w],max(a[x],max(a[y],max(a[z],max(a[b],a[c]))))))))))))))))))))
																						nums ++;
		if(sumss > 2*maxxx)
			nums ++;
		cout << nums % Mod;
	}
	else{
		srand(time(0));
		cout << rand() % Mod;
	}
}

