#include<bits/stdc++.h>
using namespace std;
long long int a[100005],b[100005],c[10005];
int a2[100005],a3[100005],a4[10005];
int b2[100005],b3[100005],b4[10005];
int c2[100005],c3[100005],c4[10005];
int main()
{
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	int t,n,i,j,a1=0,b1=0,c1=0,s=0,k,x,min=-1;
	cin>>t;
	for(i=1;i<=t;i++)
	{
		cin>>n;
		x=n/2;
		for(i=1;i<=n;i++)
		{
			cin>>a[i]>>b[i]>>c[i];
		}
		for(i=1;i<=n;i++)
		{
			if(a[i]>b[i]&&a[i]>c[i])
			{
				a1++;
				a2[i]=a[i];
				a3[i]=b[i];
				a4[i]=c[i];
				s=s+a[i];
			}
			if(b[i]>a[i]&&b[i]>c[i])
			{
				b1++;
				b2[i]=a[i];
				b3[i]=b[i];
				b4[i]=c[i];
				s=s+b[i];
			}
			if(c[i]>a[i]&&c[i]>b[i])
			{
				c1++;
				c2[i]=a[i];
				c3[i]=b[i];
				c4[i]=c[i];
				s=s+c[i];
			}
		}
		if(a1>x)
		{
			min=a2[1];
			while(x>0)
			{
				for(i=1;i<=n;i++)
				{
					if(a2[i]<min)
					{	
						x--;
						s=s-a2[i];
						if(a3[i]<a4[i])
						{
							s=s+a4[i];
						}
						else
						{
							s=s+a3[i];
						}
						a2[i]=10000;
						min=a2[i];
					}
				}
			}
		}
		if(b1>x)
		{
			min=10000;
			while(x>0)
			{
				for(i=1;i<=n;i++)
				{
					if(b3[i]<=min)
					{	
						min=b3[i];
						x--;
						s=s-b3[i];
						if(b2[i]<b4[i])
						{
							s=s+b4[i];
						}
						else
						{
							s=s+b2[i];
						}
						b3[i]=10000;
					}
				}
			}
		}
		if(c1>x)
		{
			min=c4[1];
			while(x>0)
			{
				for(i=1;i<=n;i++)
				{
					if(c4[i]<=min)
					{	
						min=c4[i];
						x--;
						s=s-c4[i];
						if(c2[i]<c3[i])
						{
							s=s+c3[i];
						}
						else
						{
							s=s+c3[i];
						}
						c4[i]=10000;
					}
				}
			}
		}
		cout<<s<<endl;
	}
 } 
