#include<bits/stdc++.h>
using namespace std;
int t,n,sum,cnt1,cnt2,cnt3,a[100005],b[100005],c[100005];
int cl(int n)
{
    for(int i=1;i<=n;i++)
    {
        int minna=0x3f3f3f3f,minnb=0x3f3f3f3f,minnc=0x3f3f3f3f;
        if(cnt1<n/2)
        {
            if(a[i]>b[i]&&a[i]>c[i])
            {
                sum+=a[i];
                cnt1++;
                minna=min(minna,a[i]);
            }
            else
            if(a[i]==b[i]&&a[i]>c[i])
            {
                if(cnt1<=cnt2)
                {
                sum+=a[i];
                cnt1++;
                minna=min(minna,a[i]);
                }
                else
                {
                sum+=b[i];
                cnt2++;
                minnb=min(minnb,b[i]);
                }
            }
            else
            {
              if(cnt1<=cnt3)
                {
                sum+=a[i];
                cnt1++;
                minna=min(minna,a[i]);
                }
                else
                {
                sum+=c[i];
                cnt3++;
                minnc=min(minnc,c[i]);
                }
            }
        }
        if(cnt2<n/2)
        {
            if(sum+b[i]>sum+a[i]&&sum+b[i]>sum+c[i])
            {
                sum+=b[i];
                cnt2++;
                minnb=min(minnb,b[i]);
            }
            if(a[i]==b[i]&&b[i]>c[i])
            {
                if(cnt1<=cnt2)
                {
                sum+=a[i];
                cnt1++;
                minna=min(minna,a[i]);
                }
                else
                {
                sum+=b[i];
                cnt2++;
                minnb=min(minnb,b[i]);
                }
            }
            else
            {
              if(cnt2<=cnt3)
                {
                sum+=b[i];
                cnt2++;
                minnb=min(minnb,b[i]);
                }
                else
                {
                sum+=c[i];
                cnt3++;
                minnc=min(minnc,c[i]);
                }
            }
        }
        if(cnt3<n/2)
        {
            if(sum+c[i]>sum+b[i]&&sum+c[i]>sum+a[i])
            {
                sum+=c[i];
                cnt3++;
                minnc=min(minnc,c[i]);
            }
            if(c[i]==a[i]&&c[i]>b[i])
            {
                if(cnt1<=cnt3)
                {
                sum+=a[i];
                cnt1++;
                minna=min(minna,a[i]);
                }
                else
                {
                sum+=c[i];
                cnt3++;
                minnc=min(minnc,c[i]);
                }
            }
            else
            {
              if(cnt2<=cnt3)
                {
                sum+=b[i];
                cnt2++;
                minnb=min(minnb,b[i]);
                }
                else
                {
                sum+=c[i];
                cnt3++;
                minnc=min(minnc,c[i]);
                }
            }
        }
        else
        if(cnt1==n/2)
        {
            if(sum+a[i]>sum+b[i]&&sum+a[i]>sum+c[i]&&a[i]>minna)
        {
            sum-=minna;
            sum+=a[i];
            minna=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minna=min(minna,a[j]);
            }
        }
        if(b[i]==a[i]&&a[i]>c[i])
            {
                if(cnt1<=cnt2)
                {
                sum-=minna;
            sum+=a[i];
            minna=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minna=min(minna,a[j]);
            }
                }
                else
                {
                sum-=minnb;
            sum+=b[i];
            minnb=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnb=min(minnb,b[j]);
            }
                }
            }
            else
            {
              if(cnt1<=cnt2)
                {
                sum-=minna;
            sum+=a[i];
            minna=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minna=min(minna,a[j]);
            }
                }
                else
                {
                sum-=minnc;
            sum+=c[i];
            minnc=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnc=min(minnc,c[j]);
            }
                }
            }
        }
        if(cnt2==n/2)
        {
        if(sum+b[i]>sum+a[i]&&sum+b[i]>sum+c[i]&&b[i]>minnb)
        {
            sum-=minnb;
            sum+=b[i];
            minnb=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnb=min(minnb,b[j]);
            }
        }
        if(b[i]==a[i]&&b[i]>c[i])
            {
                if(cnt1<=cnt2)
                {
                sum-=minna;
            sum+=a[i];
            minna=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minna=min(minna,a[j]);
            }
                }
                else
                {
                sum-=minnb;
            sum+=b[i];
            minnb=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnb=min(minnb,b[j]);
            }
                }
            }
            else
            {
              if(cnt3<=cnt2)
                {
                sum-=minnc;
            sum+=c[i];
            minnc=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnc=min(minnc,c[j]);
            }
                else
                {
                sum-=minnb;
            sum+=b[i];
            minnb=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnb=min(minnb,b[j]);
            }
                }
                }
            }
        }

        if(cnt3==n/2)
        {
         if(sum+c[i]>sum+b[i]&&sum+c[i]>sum+a[i]&&c[i]>minnc)
        {
            sum-=minnc;
            sum+=c[i];
            minnc=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnc=min(minnc,c[j]);
            }
           if(c[i]==a[i]&&b[i]<c[i])
            {
                if(cnt1<=cnt3)
                {
                sum-=minna;
            sum+=a[i];
            minna=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minna=min(minna,a[j]);
            }
                }
                else
                {
                sum-=minnc;
            sum+=c[i];
            minnc=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnc=min(minnc,c[j]);
            }
                }
            }
            else
            {
              if(cnt3<=cnt2)
                {
                sum-=minnc;
            sum+=c[i];
            minnc=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnc=min(minnc,c[j]);
            }
                else
                {
                sum-=minnb;
            sum+=b[i];
            minnb=0x3f3f3f3f;
            for(int j=1;j<=i;j++)
            {
                minnb=min(minnb,b[j]);
            }
                }
                }
            }
        }

        }

    }
    return sum;
}
int main()
{
    freopen("club.in","r",stdin);
    freopen("club.out","w",stdout);
    cin>>t;
    while(t--)
    {
        n=sum=cnt1=cnt2=cnt3=0;
        a[100005]={0};
        b[100005]={0};
        c[100005]={0};
        cin>>n;
        for(int i=1;i<=n;i++)
        {
            cin>>a[i]>>b[i]>>c[i];
        }
        cout<<cl(n)<<endl;
    }
    return 0;
}
