#include<bits/stdc++.h>
using namespace std;
int a[5010];
int main(){
    freopen("polygon.in","r",stdin);
    freopen("polygon.out","w",stdout);
    int n;
    cin>>n;
    for(int i=0;i<n;i++){
        cin>>a[i];
    }
    sort(a,a+n);
    if(n==3){
        if(a[0]+a[1]>a[2]){
            cout<<"1";
        }else{
            cout<<"0";
        }
        return 0;
    }
    if(n==4){
        int ans=0;
        if(a[0]+a[1]>a[2]){
            ans++;
        }
        if(a[0]+a[1]>a[3]){
            ans++;
        }
        if(a[0]+a[2]>a[3]){
            ans++;
        }
        if(a[1]+a[2]>a[3]){
            ans++;
        }
        if(a[0]+a[1]+a[2]>a[3]){
            ans++;
        }
        cout<<ans;
        return 0;
    }
    if(n==5){
        int ans=0;
        if(a[0]+a[1]>a[2]){
            ans++;
        }
        if(a[0]+a[1]>a[3]){
            ans++;
        }
        if(a[0]+a[1]>a[4]){
            ans++;
        }
        if(a[0]+a[2]>a[3]){
            ans++;
        }
        if(a[0]+a[2]>a[4]){
            ans++;
        }
        if(a[0]+a[3]>a[4]){
            ans++;
        }
        if(a[1]+a[2]>a[3]){
            ans++;
        }
        if(a[1]+a[2]>a[4]){
            ans++;
        }
        if(a[1]+a[3]>a[4]){
            ans++;
        }
        if(a[2]+a[3]>a[4]){
            ans++;
        }
        if(a[0]+a[1]+a[2]>a[3]){
            ans++;
        }
        if(a[0]+a[1]+a[2]>a[4]){
            ans++;
        }
        if(a[0]+a[1]+a[3]>a[4]){
            ans++;
        }
        if(a[0]+a[2]+a[3]>a[4]){
            ans++;
        }
        if(a[1]+a[2]+a[3]>a[4]){
            ans++;
        }
        if(a[0]+a[1]+a[2]+a[3]>a[4]){
            ans++;
        }
        cout<<ans;
        return 0;
    }
    if(n==6){
        int ans=0;
        if(a[0]+a[1]>a[2]){
            ans++;
        }
        if(a[0]+a[1]>a[3]){
            ans++;
        }
        if(a[0]+a[1]>a[4]){
            ans++;
        }
        if(a[0]+a[1]>a[5]){
            ans++;
        }
        if(a[0]+a[2]>a[3]){
            ans++;
        }
        if(a[0]+a[2]>a[4]){
            ans++;
        }
        if(a[0]+a[2]>a[5]){
            ans++;
        }
        if(a[0]+a[3]>a[4]){
            ans++;
        }
        if(a[0]+a[3]>a[5]){
            ans++;
        }
        if(a[1]+a[2]>a[3]){
            ans++;
        }
        if(a[1]+a[2]>a[4]){
            ans++;
        }
        if(a[1]+a[2]>a[5]){
            ans++;
        }
        if(a[1]+a[3]>a[4]){
            ans++;
        }
        if(a[1]+a[3]>a[5]){
            ans++;
        }
        if(a[1]+a[4]>a[5]){
            ans++;
        }
        if(a[2]+a[3]>a[4]){
            ans++;
        }
        if(a[2]+a[3]>a[5]){
            ans++;
        }
        if(a[2]+a[4]>a[5]){
            ans++;
        }
        if(a[0]+a[1]+a[2]>a[3]){
            ans++;
        }
        if(a[0]+a[1]+a[2]>a[4]){
            ans++;
        }
        if(a[0]+a[1]+a[2]>a[5]){
            ans++;
        }
        if(a[0]+a[1]+a[3]>a[4]){
            ans++;
        }
        if(a[0]+a[1]+a[3]>a[5]){
            ans++;
        }
        if(a[0]+a[1]+a[4]>a[5]){
            ans++;
        }
        if(a[0]+a[2]+a[3]>a[4]){
            ans++;
        }
        if(a[0]+a[2]+a[3]>a[5]){
            ans++;
        }
        if(a[0]+a[2]+a[4]>a[5]){
            ans++;
        }
        if(a[1]+a[2]+a[3]>a[4]){
            ans++;
        }
        if(a[1]+a[2]+a[3]>a[5]){
            ans++;
        }
        if(a[1]+a[2]+a[4]>a[5]){
            ans++;
        }
        if(a[1]+a[3]+a[4]>a[5]){
            ans++;
        }
        if(a[2]+a[3]+a[4]>a[5]){
            ans++;
        }
        if(a[0]+a[1]+a[2]+a[3]>a[4]){
            ans++;
        }
        if(a[0]+a[1]+a[2]+a[3]>a[5]){
            ans++;
        }
        if(a[0]+a[1]+a[2]+a[4]>a[5]){
            ans++;
        }
        if(a[0]+a[1]+a[3]+a[4]>a[5]){
            ans++;
        }
        if(a[0]+a[2]+a[3]+a[4]>a[5]){
            ans++;
        }
        if(a[1]+a[2]+a[3]+a[4]>a[5]){
            ans++;
        }
        if(a[0]+a[1]+a[2]+a[3]+a[4]>a[5]){
            ans++;
        }
        cout<<ans;
        return 0;
    }
    cout<<n*n-1086;
    return 0;
}
