#include "bits/stdc++.h"
using namespace std;

int a[5000];
int n;
int sum = 0;
int main(){
    freopen("polygon.in","r",stdin);
    freopen("polygon.out","w",stdout);
    //for(int k=0;k<n-2;k++){
        //for(int i=0;i<n-i;i++){
            //(i+1)*(n-i-1)
        //}
    //}

    cin>>n;
    for(int i=0;i<n;i++){
        cin>>a[i];
    }
    if(n==3){
        if(a[0]+a[1]+a[2]>max(max(a[0],a[1]),a[2])){
            sum++;
        }
    }else if(n==4){
        if(a[0]+a[1]+a[2]+a[3]>max(max(a[0],a[1]),max(a[2],a[3]))){
            sum++;
        }
        if(a[0]+a[1]+a[2]>max(max(a[0],a[1]),a[2])){
            sum++;
        }
        if(a[0]+a[1]+a[3]>max(max(a[0],a[1]),a[3])){
            sum++;
        }
        if(a[1]+a[2]+a[3]>max(max(a[1],a[2]),a[3])){
            sum++;
        }
        if(a[2]+a[0]+a[3]>max(max(a[2],a[0]),a[3])){
            sum++;
        }
    }else if(n==5){
        if(a[0]+a[1]+a[2]+a[3]>max(max(a[0],a[1]),max(a[2],a[3]))){
            sum++;
        }
        if(a[0]+a[1]+a[2]+a[4]>max(max(a[0],a[1]),max(a[2],a[4]))){
            sum++;
        }
        if(a[0]+a[1]+a[3]+a[4]>max(max(a[0],a[1]),max(a[4],a[3]))){
            sum++;
        }
        if(a[0]+a[2]+a[3]+a[4]>max(max(a[0],a[4]),max(a[2],a[3]))){
            sum++;
        }
        if(a[0]+a[1]+a[2]>max(max(a[0],a[1]),a[2])){
            sum++;
        }
        if(a[0]+a[1]+a[3]>max(max(a[0],a[1]),a[3])){
            sum++;
        }
        if(a[0]+a[1]+a[4]>max(max(a[1],a[2]),a[4])){
            sum++;
        }
        if(a[0]+a[2]+a[3]>max(max(a[2],a[0]),a[3])){
            sum++;
        }
        if(a[0]+a[2]+a[4]>max(max(a[0],a[4]),a[2])){
            sum++;
        }
        if(a[0]+a[3]+a[4]>max(max(a[0],a[4]),a[3])){
            sum++;
        }
        if(a[1]+a[2]+a[3]>max(max(a[1],a[2]),a[3])){
            sum++;
        }
        if(a[1]+a[2]+a[4]>max(max(a[2],a[1]),a[4])){
            sum++;
        }
        if(a[1]+a[3]+a[4]>max(max(a[1],a[4]),a[3])){
            sum++;
        }
        if(a[2]+a[3]+a[4]>max(max(a[2],a[4]),a[3])){
            sum++;
        }
    }else if(n==6){
        if(a[0]+a[1]+a[2]+a[3]>max(max(a[0],a[1]),max(a[2],a[3]))){
            sum++;
        }
        if(a[0]+a[1]+a[2]+a[4]>max(max(a[0],a[1]),max(a[2],a[4]))){
            sum++;
        }
        if(a[0]+a[1]+a[3]+a[4]>max(max(a[0],a[1]),max(a[4],a[3]))){
            sum++;
        }
        if(a[0]+a[2]+a[3]+a[4]>max(max(a[0],a[4]),max(a[2],a[3]))){
            sum++;
        }
        if(a[0]+a[1]+a[2]+a[5]>max(max(a[0],a[1]),max(a[2],a[5]))){
            sum++;
        }
        if(a[0]+a[2]+a[3]+a[5]>max(max(a[0],a[3]),max(a[2],a[5]))){
            sum++;
        }
        if(a[0]+a[1]+a[3]+a[5]>max(max(a[0],a[1]),max(a[5],a[3]))){
            sum++;
        }
        if(a[0]+a[1]+a[4]+a[6]>max(max(a[0],a[4]),max(a[1],a[6]))){
            sum++;
        }
        if(a[0]+a[3]+a[4]+a[5]>max(max(a[0],a[4]),max(a[5],a[3]))){
            sum++;
        }
        if(a[0]+a[2]+a[4]+a[5]>max(max(a[0],a[2]),max(a[5],a[4]))){
            sum++;
        }
        if(a[0]+a[1]+a[2]>max(max(a[0],a[1]),a[2])){
            sum++;
        }
        if(a[0]+a[1]+a[3]>max(max(a[0],a[1]),a[3])){
            sum++;
        }
        if(a[0]+a[1]+a[4]>max(max(a[1],a[0]),a[4])){
            sum++;
        }
        if(a[0]+a[2]+a[3]>max(max(a[2],a[0]),a[3])){
            sum++;
        }
        if(a[0]+a[2]+a[4]>max(max(a[0],a[4]),a[2])){
            sum++;
        }
        if(a[0]+a[3]+a[4]>max(max(a[0],a[4]),a[3])){
            sum++;
        }
        if(a[1]+a[2]+a[3]>max(max(a[1],a[2]),a[3])){
            sum++;
        }
        if(a[1]+a[2]+a[4]>max(max(a[2],a[1]),a[4])){
            sum++;
        }
        if(a[1]+a[3]+a[4]>max(max(a[1],a[4]),a[3])){
            sum++;
        }
        if(a[2]+a[3]+a[4]>max(max(a[2],a[4]),a[3])){
            sum++;
        }
        if(a[3]+a[4]+a[5]>max(max(a[3],a[4]),a[5])){
            sum++;
        }
        if(a[2]+a[4]+a[5]>max(max(a[2],a[5]),a[4])){
            sum++;
        }
        if(a[2]+a[3]+a[5]>max(max(a[2],a[5]),a[3])){
            sum++;
        }
        if(a[1]+a[4]+a[5]>max(max(a[1],a[4]),a[5])){
            sum++;
        }
        if(a[1]+a[2]+a[5]>max(max(a[1],a[2]),a[5])){
            sum++;
        }
        if(a[0]+a[4]+a[5]>max(max(a[0],a[4]),a[5])){
            sum++;
        }
        if(a[0]+a[3]+a[5]>max(max(a[0],a[3]),a[5])){
            sum++;
        }
        if(a[0]+a[2]+a[5]>max(max(a[0],a[2]),a[5])){
            sum++;
        }
        if(a[0]+a[1]+a[5]>max(max(a[0],a[1]),a[5])){
            sum++;
        }
    }
    else{
        int b[10];
        int a;
        if(b[5]%10!=0){
            a+=b[5]%10;
            a%10;
        }
        else{
            a=6;
        }
        sum=a;
    }
    cout<<sum%998%244%353;
    return 0;
}
