#include <bits/stdc++.h>
//#defin a q;
using namespace std;
//priority_queue<int,vector<int>,less<int> >q;
long long T,n;
struct qw{
	int x,y,z,id;
}a[1000000];
bool cmp(qw x,qw y){
	return max(max(abs(x.x-x.y),abs(x.y-x.z)),abs(x.z-x.x))>max(max(abs(y.x-y.y),abs(y.y-y.z)),abs(y.z-y.x));
}
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>T;
	while(T--){
		cin>>n;
		long long ans=0;
		for(int i=1;i<=n;i++){
			cin>>a[i].x>>a[i].y>>a[i].z;
			a[i].id=i;
		}
		sort(a+1,a+1+n,cmp);
		long long xt=0,yt=0,zt=0;
		for(int i=1;i<=n;i++){
			if(abs(a[i].x-a[i].y)>=abs(a[i].x-a[i].z)&&abs(a[i].x-a[i].y)>=abs(a[i].y-a[i].z)){
				if(a[i].x>a[i].y){
					if(xt<n/2){
						xt++;
						ans+=a[i].x;
						continue;
					}
					else{
						if(a[i].y>a[i].z){
							if(yt<n/2){
								yt++;
								ans+=a[i].y;
								continue;
							}
							else{
								zt++;
								ans+=a[i].z;
								continue;
							}
						}
						else{
							if(zt<n/2){
								zt++;
								ans+=a[i].z;
								continue;
							}
							else{
								yt++;
								ans+=a[i].y;
								continue;
							}
						}
					}
				}
				else{
					if(yt<n/2){
						yt++;
						ans+=a[i].y;
						continue;
					}
					else{
						if(a[i].x>a[i].z){
							if(xt<n/2){
								xt++;
								ans+=a[i].x;
								continue;
							}
							else{
								zt++;
								ans+=a[i].z;
								continue;
							}
						}
						else{
							if(zt<n/2){
								zt++;
								ans+=a[i].z;
								continue;
							}
							else{
								xt++;
								ans+=a[i].x;
								continue;
							}
						}
					}
				}
			}
			if(abs(a[i].y-a[i].z)>=abs(a[i].x-a[i].z)&&abs(a[i].y-a[i].z)>=abs(a[i].y-a[i].x)){
				if(a[i].y>a[i].z){
					if(yt<n/2){
						yt++;
						ans+=a[i].y;
						continue;
					}
					else{
						if(a[i].x>a[i].z){
							if(xt<n/2){
								xt++;
								ans+=a[i].x;
								continue;
							}
							else{
								zt++;
								ans+=a[i].z;
								continue;
							}
						}
						else{
							if(zt<n/2){
								zt++;
								ans+=a[i].z;
								continue;
							}
							else{
								xt++;
								ans+=a[i].x;
								continue;
							}
						}
					}
				}
				else{
					if(zt<n/2){
						zt++;
						ans+=a[i].z;
						continue;
					}
					else{
						if(a[i].x>a[i].y){
							if(xt<n/2){
								xt++;
								ans+=a[i].x;
								continue;
							}
							else{
								yt++;
								ans+=a[i].y;
								continue;
							}
						}
						else{
							if(yt<n/2){
								yt++;
								ans+=a[i].y;
								continue;
							}
							else{
								xt++;
								ans+=a[i].x;
								continue;
							}
						}
					}
				}
			}
			if(abs(a[i].x-a[i].z)>=abs(a[i].y-a[i].z)&&abs(a[i].x-a[i].z)>=abs(a[i].y-a[i].x)){
				if(a[i].x>a[i].z){
					if(xt<n/2){
						xt++;
						ans+=a[i].x;
						continue;
					}
					else{
						if(a[i].y>a[i].z){
							if(yt<n/2){
								yt++;
								ans+=a[i].y;
								continue;
							}
							else{
								zt++;
								ans+=a[i].z;
								continue;
							}
						}
						else{
							if(zt<n/2){
								zt++;
								ans+=a[i].z;
								continue;
							}
							else{
								yt++;
								ans+=a[i].y;
								continue;
							}
						}
					}
				}
				else{
					if(zt<n/2){
						zt++;
						ans+=a[i].z;
						continue;
					}
					else{
						if(a[i].z>a[i].y){
							if(zt<n/2){
								zt++;
								ans+=a[i].z;
								continue;
							}
							else{
								yt++;
								ans+=a[i].y;
								continue;
							}
						}
						else{
							if(yt<n/2){
								yt++;
								ans+=a[i].y;
								continue;
							}
							else{
								zt++;
								ans+=a[i].z;
								continue;
							}
						}
					}
				}
			}
		}
		cout<<ans<<endl;
	}
	return 0;
}
