#include<bits/stdc++.h>
using namespace std;
int lastmax=-1,maxx,t,n,a[100005],b[100005],c[100005],bz1[20005],bz2[20005],bz3[20005],cnt1,cnt2,cnt3;
bool cmp(int x,int y)
{
	return x<y;
}
int main()
{
	scanf("%d",&t);
	while(t--)
	{
		scanf("%d",&n);
		maxx=0;
		memset(bz1,0,sizeof(bz1));
		memset(bz2,0,sizeof(bz2));
		memset(bz3,0,sizeof(bz3));
		cnt1=cnt2=cnt3=0;
		for(int i=1;i<=n;i++)
		{
			scanf("%d%d%d",&a[i],&b[i],&c[i]);
			if(a[i]>b[i]&&a[i]>c[i])
			{
				if(lastmax==1&&a[i]+max(b[i-1],c[i-1])>a[i-1])
				{
					maxx-=a[i-1];
					maxx+=a[i]+max(b[i-1],c[i-1]);
					if(b[i-1]>c[i-1])
					{
						cnt2++;
						if(cnt2>n/2)
						{
							sort(b+1,b+i+1,cmp);
							if(!bz2[i])
							{
								maxx-=b[1];
								bz2[i]=1;
							}
							else
							{
								for(int j=2;j<=i;j++)
								{
									if(!bz2[j])
									{
										maxx-=b[j];
									}
								}
							}
							cnt2=n/2;
						}
					}
					else
					{
						cnt3++;
						if(cnt3>n/2)
						{
							sort(c+1,c+i+1,cmp);
							if(!bz3[i])
							{
								maxx-=c[1];
								bz3[i]=1;
							}
							else
							{
								for(int j=2;j<=i;j++)
								{
									if(!bz3[j])
									{
										maxx-=c[j];
									}
								}
							}
							cnt3=n/2;
						}
					}
				}
				else
				{
					lastmax=1;
					maxx+=a[i];
					cnt1++;
					if(cnt1>n/2)
					{
						sort(a+1,a+i+1,cmp);
						if(!bz1[i])
						{
							maxx-=a[1];
							bz1[i]=1;
						}
						else
						{
							for(int j=2;j<=i;j++)
							{
								if(!bz1[j])
								{
									maxx-=a[j];
								}
							}
						}
						cnt1=n/2;
					}
				}
			}
			
			
			
			if(b[i]>a[i]&&b[i]>c[i])
			{
				if(lastmax==2&&b[i]+max(a[i-1],c[i-1])>b[i-1])
				{
					maxx-=b[i-1];
					maxx+=b[i]+max(a[i-1],c[i-1]);
					if(a[i-1]>c[i-1])
					{
						cnt1++;
						if(cnt1>n/2)
						{
							sort(a+1,a+i+1,cmp);
							if(!bz1[i])
							{
								maxx-=a[1];
								bz1[i]=1;
							}
							else
							{
								for(int j=2;j<=i;j++)
								{
									if(!bz1[j])
									{
										maxx-=a[j];
									}
								}
							}
							cnt1=n/2;
						}
					}
					else
					{
						cnt3++;
						if(cnt3>n/2)
						{
							sort(c+1,c+i+1,cmp);
							if(!bz3[i])
							{
								maxx-=c[1];
								bz3[i]=1;
							}
							else
							{
								for(int j=2;j<=i;j++)
								{
									if(!bz3[j])
									{
										maxx-=c[j];
									}
								}
							}
							cnt3=n/2;
						}
					}
				}
				else{
				lastmax=2;
				maxx+=b[i];
				cnt2++;
				if(cnt2>n/2)
				{
					sort(b+1,b+i+1,cmp);
					if(!bz2[i])
					{
						maxx-=b[1];
						bz2[i]=1;
					}
					else
					{
						for(int j=2;j<=i;j++)
						{
							if(!bz2[j])
							{
								maxx-=b[j];
							}
						}
					}
					cnt2=n/2;
				}
				}
			}
			
			
			
			if(c[i]>a[i]&&c[i]>b[i])
			{
				if(lastmax==3&&c[i]+max(a[i-1],b[i-1])>c[i-1])
				{
					maxx-=c[i-1];
					maxx+=c[i]+max(a[i-1],b[i-1]);
					if(a[i-1]>b[i-1])
					{
						cnt1++;
						if(cnt1>n/2)
						{
							sort(a+1,a+i+1,cmp);
							if(!bz1[i])
							{
								maxx-=a[1];
								bz1[i]=1;
							}
							else
							{
								for(int j=2;j<=i;j++)
								{
									if(!bz1[j])
									{
										maxx-=a[j];
									}
								}
							}
							cnt1=n/2;
						}
					}
					else
					{
						cnt2++;
						if(cnt2>n/2)
						{
							sort(b+1,b+i+1,cmp);
							if(!bz2[i])
							{
								maxx-=b[1];
								bz2[i]=1;
							}
							else
							{
								for(int j=2;j<=i;j++)
								{
									if(!bz2[j])
									{
										maxx-=b[j];
									}
								}
							}
							cnt2=n/2;
						}
					}
				}
				else
				{
				lastmax=3;
				maxx+=c[i];
				cnt3++;
				if(cnt3>n/2)
				{
					sort(c+1,c+i+1,cmp);
					if(!bz3[i])
					{
						maxx-=c[1];
						bz3[i]=1;
					}
					else
					{
						for(int j=2;j<=i;j++)
						{
							if(!bz3[j])
							{
								maxx-=c[j];
							}
						}
					}
					cnt3=n/2;
				}
				}
			}
		}
		printf("%d\n",maxx);
	}
	return 0;
}
