#include<bits/stdc++.h>
#define int long long
using namespace std;

signed main(){
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
//	freopen("employ.in","r",stdin);
//	freopen("employ.out","w",stdout);
	freopen("employ.in","r",stdin);
	freopen("employ.out","w",stdout);
	ios::sync_with_stdio(0);
	cin.tie(0);cout.tie(0);
	int n,m,k;
	cin>>n>>m>>k;
	cout<<n*m*k%998244353;
	return 0;
}

