#include <bits/stdc++.h>
using namespace std;
int t;
int main()
{
    freopen("club.in","r",stdin);
    freopen("club.out","w",stdout);
    cin>>t;
    int n,a1=0,a2=0,a3=0,a4=0,a5=0,a6=0,max1=0;
    cin>>n;
    for(int i=1;i<=t;i++)
    {
        if(n==2)
        {
            cin>>a1>>a2>>a3>>a4>>a5>>a6;
            if(a1>a2&&a1>a3)
            {
                if(a4>a1&&a4>a5&&a4>a6)
                {
                    max1+=a4;
                    if(a2>a3)
                    {
                        max1+=a2;
                    }
                    else
                    {
                        max1+=a3;
                    }
                }
                if(a1>a4)
                {
                    max1+=a1;
                    if(a5>a6)
                    {
                        max1+=a5;
                    }
                    else
                    {
                        max1+=a6;
                    }
                }
            }
            if(a2>a1&&a2>a3)
            {
                if(a5>a2&&a5>a4&&a5>a6)
                {
                    max1+=a5;
                    if(a1>a3)
                    {
                        max1+=a1;
                    }
                    else
                    {
                        max1+=a3;
                    }
                }
                if(a2>a5)
                {
                    max1+=a2;
                    if(a4>a6)
                    {
                        max1+=a4;
                    }
                    else
                    {
                        max1+=a6;
                    }
                }
            }
            if(a3>a1&&a3>a2)
            {
                if(a6>a3&&a6>a4&&a6>a5)
                {
                    max1+=a6;
                    if(a1>a2)
                    {
                        max1+=a1;
                    }
                    else
                    {
                        max1+=a2;
                    }
                }
                if(a3>a6)
                {
                    max1+=a3;
                    if(a4>a5)
                    {
                        max1+=a4;
                    }
                    else
                    {
                        max1+=a5;
                    }
                }
            }

        }
        cout<<max1;
    }
    return 0;
}
