#include<bits/stdc++.h>
using namespace std;
long long t;
int main(){
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>t;
	while(t--){
		long long n,a,b,c,sum=0,e[50005]={0},f[50005]={0},g[50005]={0},ei=1,fi=1,gi=1,q=0,w=0,r=0,za=0,zb=0,zc=0;
		cin>>n;
		if(n==2){
			long long o,p,q;
			cin>>a>>b>>c>>o>>p>>q;
			long long y[10]={a+p,a+q,b+o,b+q,c+o,c+p};
			sort(y,y+6,greater<int>());
			cout<<y[0]<<"\n";
			continue;
		}
		for(int i=1;i<=n;i++){
			cin>>a>>b>>c;
			if(max({a,b,c})==a){
				if(q+1<=n/2){
					sum+=a;
					e[ei]=a;
					ei++;
					q++;
					sort(e+1,e+ei);
					if(a==e[1]){
						if(b>c){
							za=b;
						}else{
							za=c;
						}
					}
				}else{
					sort(e+1,e+ei);
					if(a>e[1]){
						sum-=e[1];
						sum+=za;
						sum+=a;
						e[1]=a;
					}else if(b>c){
						if(w+1<=n/2){
							sum+=b;
							f[fi]=b;
							fi++;
							w++;
							sort(f+1,f+fi);
							if(b==f[1]){
								if(a>c){
									zb=a;
								}else{
									zb=c;
								}
							}
						}else{
							sort(f+1,f+fi);
							if(b>f[1]){
								f[1]=b;
								sum-=f[1];
								sum+=zb;
								sum+=b;
							}else{
								if(r+1<=n/2){
									sum+=c;
									g[gi]=c;
									gi++;
									r++;
									sort(g+1,g+gi);
									if(c==g[1]){
										if(a>b){
											zc=a;
										}else{
											zc=b; 
										}
									}
								}else{
									sort(g+1,g+gi);
									if(c>g[1]){
										sum-=g[1];
										sum+=zc;
										sum+=c;
										g[1]=c;
									}
								}
							}
						}
					}
				}
			}else if(max({a,b,c})==b){
				if(w+1<=n/2){
					sum+=b;
					f[fi]=b;
					fi++;
					w++;
					sort(f+1,f+fi);
					if(b==f[1]){
						if(a>c){
							zb=a;
						}else{
							zb=c;
						}
					}
				}else{
					sort(f+1,f+fi);
					if(b>f[1]){
						sum-=f[1];
						sum+=zb;
						sum+=b;
						f[1]=b;
					}else if(a>c){
						if(q+1<=n/2){
							sum+=a;
							e[ei]=a;
							ei++;
							q++;
							sort(e+1,e+ei);
							if(a==e[1]){
								if(b>c){
									za=b;
								}else{
									za=c;
								}
							}
						}else{
							sort(e+1,e+ei);
							if(a>e[1]){
								sum-=e[1];
								sum+=za;
								sum+=a;
								e[1]=a;
							}else{
								if(r+1<=n/2){
									sum+=c;
									g[gi]=c;
									gi++;
									r++;
									sort(g+1,g+gi);
									if(c==g[1]){
										if(a>b){
											zc=a;
										}else{
											zc=b; 
										}
									}
								}else{
									sort(g+1,g+gi);
									if(c>g[1]){
										sum-=g[1];
										sum+=zc;
										sum+=c;
										g[1]=c;
									}
								}
							}
						}
					}
				}
			}else{
				if(r+1<=n/2){
					sum+=c;
					g[gi]=c;
					gi++;
					r++;
					sort(g+1,g+gi);
					if(c==g[1]){
						if(a>b){
							zc=a;
						}else{
							zc=b; 
						}
					}
				}else{
					sort(g+1,g+gi);
					if(c>g[1]){
						sum-=g[1];
						sum+=zc;
						sum+=c;
						g[1]=c;
					}else if(b>a){
						if(w+1<=n/2){
							sum+=b;
							f[fi]=b;
							fi++;
							w++;
							sort(f+1,f+fi);
							if(b==f[1]){
								if(a>c){
									zb=a;
								}else{
									zb=c;
								}
							}
						}else{
							sort(f+1,f+fi);
							if(b>f[1]){
								sum-=f[1];
								sum+=zb;
								sum+=b;
								f[1]=b;
							}else{
								if(q+1<=n/2){
									sum+=a;
									e[ei]=a;
									ei++;
									q++;
									sort(e+1,e+ei);
									if(a==e[1]){
										if(b>c){
											za=b;
										}else{
											za=c;
										}
									}
								}else{
									sort(e+1,e+ei);
									if(a>e[1]){
										sum-=e[1];
										sum+=za;
										sum+=a;
										e[1]=a;
									}
								}
							}
						}
					}
				}
			}
		}
		cout<<sum<<"\n";
	}
	return 0;
}
