#include <bits/stdc++.h>
using namespace std;
int main(){
    freopen("number.in","r",stdin);
    freopen("number.out","w",stdout);
    int s,a,b,c,d,e,f,g,aa,bb,cc,dd,ee,ff,gg;
    cin>>s;
    if(s<=9){
        cout<<s;
    }
    else if(s<=99){
            a=s%10;
            b=s/10;
            if(a==0&&b==0)cout<<0;
            else if(a==0)cout<<b<<0;
            else if(b==0)cout<<b<<0;
            else if(a>=b)cout<<a<<b;
            else cout<<b<<a;
    }
    else if(s<=999){
        a=s%10;
        s/=10;
        b=s%10;
        c=s/10;
        aa=a;
        bb=b;
        if(a<b){
            a=b;
            b=aa;
        }
        if(a<c){
            a=c;
            c=aa;
        }
        if(b<c){
            b=c;
            c=bb;
        }
        if(a==0&&b==0&&c==0)cout<<0;
        else cout<<a<<b<<c;
    }
    else if(s<=9999){
        a=s%10;
        s/=10;
        b=s%10;
        s/=10;
        c=s%10;
        d=s/10;
        aa=a;
        bb=b;
        cc=c;
        if(a<b){
            a=b;
            b=aa;
        }
        if(a<c){
            a=c;
            c=aa;
        }
        if(a<d){
            a=d;
            d=aa;
        }
        if(b<c){
            b=c;
            c=bb;
        }
        if(b<d){
            b=d;
            d=bb;
        }
        if(c<d){
            c=d;
            d=cc;
        }
        if(a==0&&b==0&&c==0&&d==0)cout<<0;
        else cout<<a<<b<<c<<d;
    }
    else if(s<=99999){
        a=s%10;
        s/=10;
        b=s%10;
        s/=10;
        c=s%10;
        s/=10;
        d=s%10;
        e=s/10;
        aa=a;
        bb=b;
        cc=c;
        dd=d;
        if(a<b){
            a=b;
            b=aa;
        }
        if(a<c){
            a=c;
            c=aa;
        }
        if(a<d){
            a=d;
            d=aa;
        }
        if(a<e){
            a=e;
            e=aa;
        }
        if(b<c){
            b=c;
            c=bb;
        }
        if(b<d){
            b=d;
            d=bb;
        }
        if(b<e){
            b=e;
            e=bb;
        }
        if(c<d){
            c=d;
            d=cc;
        }
        if(c<e){
            c=e;
            e=cc;
        }
        if(d<e){
            d=e;
            e=dd;
        }
        if(a==0&&b==0&&c==0&&d==0&&e==0)cout<<0;
        else cout<<a<<b<<c<<d<<e;
    }
    else if(s<=999999){
        a=s%10;
        s/=10;
        b=s%10;
        s/=10;
        c=s%10;
        s/=10;
        d=s%10;
        s/=10;
        e=s%10;
        f=s/10;
        aa=a;
        bb=b;
        cc=c;
        dd=d;
        ee=e;
        if(a<b){
            a=b;
            b=aa;
        }
        if(a<c){
            a=c;
            c=aa;
        }
        if(a<d){
            a=d;
            d=aa;
        }
        if(a<e){
            a=e;
            e=aa;
        }
        if(a<f){
            a=f;
            f=aa;
        }
        if(b<c){
            b=c;
            c=bb;
        }
        if(b<d){
            b=d;
            d=bb;
        }
        if(b<e){
            b=e;
            e=bb;
        }
        if(b<f){
            b=f;
            f=bb;
        }
        if(c<d){
            c=d;
            d=cc;
        }
        if(c<e){
            c=e;
            e=cc;
        }
        if(c<f){
            c=f;
            f=cc;
        }
        if(d<e){
            d=e;
            e=dd;
        }
        if(d<f){
            d=f;
            f=dd;
        }
        if(e<f){
            e=f;
            f=ee;
        }
        if(a==0&&b==0&&c==0&&d==0&&e==0&&f==0)cout<<0;
        else cout<<a<<b<<c<<d<<e<<f;
    }
    else if(s<=9999999){
        a=s%10;
        s/=10;
        b=s%10;
        s/=10;
        c=s%10;
        s/=10;
        d=s%10;
        s/=10;
        e=s%10;
        s/=10;
        f=s%10;
        g=s/10;
        aa=a;
        bb=b;
        cc=c;
        dd=d;
        ee=e;
        ff=f;
        if(a<b){
            a=b;
            b=aa;
        }
        if(a<c){
            a=c;
            c=aa;
        }
        if(a<d){
            a=d;
            d=aa;
        }
        if(a<e){
            a=e;
            e=aa;
        }
        if(a<f){
            a=f;
            f=aa;
        }
        if(a<g){
            a=g;
            g=aa;
        }
        if(b<c){
            b=c;
            c=bb;
        }
        if(b<d){
            b=d;
            d=bb;
        }
        if(b<e){
            b=e;
            e=bb;
        }
        if(b<f){
            b=f;
            f=bb;
        }
        if(b<g){
            b=g;
            g=bb;
        }
        if(c<d){
            c=d;
            d=cc;
        }
        if(c<e){
            c=e;
            e=cc;
        }
        if(c<f){
            c=f;
            f=cc;
        }
        if(c<g){
            c=g;
            g=cc;
        }
        if(d<e){
            d=e;
            e=dd;
        }
        if(d<f){
            d=f;
            f=dd;
        }
        if(d<g){
            d=g;
            g=dd;
        }
        if(e<f){
            e=f;
            f=ee;
        }
        if(e<g){
            e=g;
            g=ee;
        }
        if(f<g){
            f=g;
            g=ff;
        }
        if(a==0&&b==0&&c==0&&d==0&&e==0&&f==0&&g==0)cout<<0;
        else cout<<a<<b<<c<<d<<e<<f<<g;
    }
    return 0;
}
