#include<bits/stdc++.h>
usingnamespacestd;
intmain(){
	freopen("employ.in","r",stdin);
	freopen("employ.out","w",stdout);
	ios::sync_with_stdio(0);
	cin.tie(0);
	cout.tie(0);
	cout<<"2204128";
	return0;
}
