#include<bits/stdc++.h>
using namespace std;
int i,j,k,m,n,t,x,y,z,d,e;
int a[100005][5],b[100005][5],c[100005],f[100005][5];
int main()
{
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>t;
	for(i=1;i<=t;i++)
	{
		c[1]=0;
		d=1;
		x=0;
		y=0;
		z=0;
		cin>>n;
		for(j=1;j<=n;j++)
		{
			for(k=1;k<=3;k++)
			{
				b[j][k]=-1;
			}
		}
		m=n/2;
		for(j=1;j<=n;j++)
		{
			cin>>a[j][1]>>a[j][2]>>a[j][3];
		}
		for(j=1;j<=m;j++)
		{
			if(a[j][1]>=a[j][2]&&a[j][1]>=a[j][3])
			{
				x++;
				b[x+y+z][1]=a[j][1];
				c[1]=c[1]+a[j][1];
			}
			else if(a[j][2]>=a[j][1]&&a[j][2]>=a[j][3])
			{
				y++;
				b[x+y+z][2]=a[j][2];
				c[1]=c[1]+a[j][2];
			}
			else
			{
				z++;
				b[x+y+z][3]=a[j][3];
				c[1]=c[1]+a[j][3];
			}
		}
		for(j=m+1;j<=n;j++)
		{
			if(x>=m&&a[j][1]>=a[j][2]&&a[j][1]>=a[j][3])
			{
				for(k=1;k<=j-1;k++)
				{
					if(b[k][1]!=-1)
					{
						if(a[j][1]+a[k][2]>a[k][1]||a[j][1]+a[k][3]>a[k][1])
						{
							if(a[j][1]+a[k][2]>a[j][1]+a[k][3])
							{
								d++;
								f[d][1]=k;
								c[d]=c[1];
								c[d]=c[d]-b[k][1]+a[k][2]+a[j][1];
							}
							else
							{
								d++;
								f[d][1]=k;
								c[d]=c[1];
								c[d]=c[d]-b[k][1]+a[k][3]+a[j][1];
							}
						}
					}
				}
			}
			else if(y>=m&&a[j][2]>=a[j][1]&&a[j][2]>=a[j][3])
			{
				for(k=1;k<=j-1;k++)
				{
					if(b[k][2]!=-1)
					{
						if(a[j][2]+a[k][1]>a[k][2]||a[j][2]+a[k][3]>a[k][2])
						{
							if(a[j][2]+a[k][1]>a[j][2]+a[k][3])
							{
								d++;
								f[d][2]=k;
								c[d]=c[1];
								c[d]=c[d]-b[k][2]+a[k][1]+a[j][2];
							}
							else
							{
								d++;
								f[d][2]=k;
								c[d]=c[1];
								c[d]=c[d]-b[k][2]+a[k][3]+a[j][2];
							}
						}
					}
				}
			}
			else if(z>=m&&a[j][3]>=a[j][2]&&a[j][3]>=a[j][1])
			{
				for(k=1;k<=j-1;k++)
				{
					if(b[k][3]!=-1)
					{
						if(a[j][3]+a[k][1]>a[k][3]||a[j][3]+a[k][2]>a[k][3])
						{
							if(a[j][3]+a[k][1]>a[j][3]+a[k][2])
							{
								d++;
								f[d][3]=k;
								c[d]=c[1];
								c[d]=c[d]-b[k][3]+a[k][1]+a[j][3];
							}
							else
							{
								d++;
								f[d][3]=k;
								c[d]=c[1];
								c[d]=c[d]-b[k][3]+a[k][2]+a[j][3];
							}
						}
					}
				}
			}
			else if(a[j][1]>=a[j][2]&&a[j][1]>=a[j][3])
			{
				x++;
				b[x+y+z][1]=a[j][1];
				c[1]=c[1]+a[j][1];
			}
			else if(a[j][2]>=a[j][1]&&a[j][2]>=a[j][3])
			{
				y++;
				b[x+y+z][2]=a[j][2];
				c[1]=c[1]+a[j][2];
			}
			else
			{
				z++;
				b[x+y+z][3]=a[j][3];
				c[1]=c[1]+a[j][3];
			}
			if(d!=1)
			{
				for(k=2;k<=d;k++)
				{
					c[1]=max(c[1],c[k]);
					if(c[1]==c[k])
					{
						e=k;
					}
				}
				if(f[2][1]!=0)
				{
					k=f[e][1];
					if(a[j][1]+a[k][2]>a[j][1]+a[k][3])
					{
						b[k][1]=-1;
						b[k][2]=a[k][2];
						b[j][1]=a[j][1];
					}
					else
					{
						b[k][1]=-1;	
						b[k][3]=a[k][3];
						b[j][1]=a[j][1];
					}
					for(k=1;k<=d;k++)
					{
						f[k][1]=0;
					}
				}
				if(f[2][2]!=0)
				{
					k=f[e][2];
					if(a[j][2]+a[k][1]>a[j][2]+a[k][3])
					{
						b[k][2]=-1;
						b[k][1]=a[k][1];
						b[j][2]=a[j][2];
					}
					else
					{
						b[k][2]=-1;	
						b[k][3]=a[k][3];
						b[j][2]=a[j][2];
					}
					for(k=1;k<=d;k++)
					{
						f[k][2]=0;
					}
				}
				if(f[2][3]!=0)
				{
					k=f[e][3];
					if(a[j][3]+a[k][1]>a[j][3]+a[k][2])
					{
						b[k][3]=-1;
						b[k][1]=a[k][1];
						b[j][3]=a[j][3];
					}
					else
					{
						b[k][3]=-1;	
						b[k][2]=a[k][2];
						b[j][3]=a[j][3];
					}
					for(k=1;k<=d;k++)
					{
						f[k][3]=0;
					}
				}
				d=1;
			}
		}
		cout<<c[1]<<endl;
	}
	return 0;
}
