#include<bits/stdc++.h>
using namespace std;
int n,q;
string s[200001][2],st1,st2;
int main(){
	freopen("replace.in","r",stdin);
	freopen("replace.out","w",stdout);
	cin>>n>>q;
	for (int i=1;i<=n;i++) cin>>s[i][0]>>s[i][1];
	while (q--){
		cin>>st1>>st2;
		cout<<0<<endl;
	}
	fclose(stdin);
	fclose(stdout);
	return 0;
}
/*
I cant read the T3
bro use the Mar's language
see dont know simida~~~
what the T3 use the alien's language
IDK what does it says
aaa si1 he si2 shi shen me aaaaaaa
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*[brain crash]
*/
