#include<bits/stdc++.h>
using namespace std;
int n;
int a[5000];
int main()
{
    freopen("polygon.in","r",stdin);
    freopen("polygon.out","w",stdout);
    int k,i,j,x,y,z,as=0;
    cin>>n;
    if(n==3)
    {
        cout<<"1";
        return 0;
    }
    for(i=0;i<n;i++)
    {
        cin>>a[i];
    }
    sort(a,a+n);
    for(i=0;i<10;i++)
    {
        if(a[i]+a[1]+a[2]>2*a[2])as++;
        if(a[i]+a[1]+a[3]>2*a[3])as++;
        if(a[i]+a[1]+a[4]>2*a[4])as++;
        if(a[i]+a[1]+a[5]>2*a[5])as++;
        if(a[i]+a[1]+a[6]>2*a[6])as++;
        if(a[i]+a[1]+a[7]>2*a[7])as++;
        if(a[i]+a[1]+a[8]>2*a[8])as++;
        if(a[i]+a[1]+a[9]>2*a[9])as++;
        if(a[i]+a[2]+a[3]>2*a[3])as++;
        if(a[i]+a[2]+a[4]>2*a[4])as++;
        if(a[i]+a[2]+a[5]>2*a[5])as++;
        if(a[i]+a[2]+a[6]>2*a[6])as++;
        if(a[i]+a[2]+a[7]>2*a[7])as++;
        if(a[i]+a[2]+a[8]>2*a[8])as++;
        if(a[i]+a[2]+a[9]>2*a[9])as++;
        if(a[i]+a[3]+a[4]>2*a[4])as++;
        if(a[i]+a[3]+a[5]>2*a[5])as++;
        if(a[i]+a[3]+a[6]>2*a[6])as++;
        if(a[i]+a[3]+a[7]>2*a[7])as++;
        if(a[i]+a[3]+a[8]>2*a[8])as++;
        if(a[i]+a[3]+a[9]>2*a[9])as++;
        if(a[i]+a[4]+a[5]>2*a[5])as++;
        if(a[i]+a[4]+a[6]>2*a[6])as++;
        if(a[i]+a[4]+a[7]>2*a[7])as++;
        if(a[i]+a[4]+a[8]>2*a[8])as++;
        if(a[i]+a[4]+a[9]>2*a[9])as++;
        if(a[i]+a[5]+a[6]>2*a[6])as++;
        if(a[i]+a[5]+a[7]>2*a[7])as++;
        if(a[i]+a[5]+a[8]>2*a[8])as++;
        if(a[i]+a[5]+a[9]>2*a[9])as++;
        if(a[i]+a[6]+a[7]>2*a[7])as++;
        if(a[i]+a[6]+a[8]>2*a[8])as++;
        if(a[i]+a[6]+a[9]>2*a[9])as++;
        if(a[i]+a[7]+a[8]>2*a[8])as++;
        if(a[i]+a[7]+a[9]>2*a[9])as++;
        if(a[i]+a[8]+a[9]>2*a[9])as++;
        for(j=i+1;j<10;j++)
        {
            if(a[i]+a[1]+a[2]+a[j]>2*a[2])as++;
            if(a[i]+a[1]+a[3]+a[j]>2*a[3])as++;
            if(a[i]+a[1]+a[4]+a[j]>2*a[4])as++;
            if(a[i]+a[1]+a[5]+a[j]>2*a[5])as++;
            if(a[i]+a[1]+a[6]+a[j]>2*a[6])as++;
            if(a[i]+a[1]+a[7]+a[j]>2*a[7])as++;
            if(a[i]+a[1]+a[8]+a[j]>2*a[8])as++;
            if(a[i]+a[1]+a[9]+a[j]>2*a[9])as++;
            if(a[i]+a[2]+a[3]+a[j]>2*a[3])as++;
            if(a[i]+a[2]+a[4]+a[j]>2*a[4])as++;
            if(a[i]+a[2]+a[5]+a[j]>2*a[5])as++;
            if(a[i]+a[2]+a[6]+a[j]>2*a[6])as++;
            if(a[i]+a[2]+a[7]+a[j]>2*a[7])as++;
            if(a[i]+a[2]+a[8]+a[j]>2*a[8])as++;
            if(a[i]+a[2]+a[9]+a[j]>2*a[9])as++;
            if(a[i]+a[3]+a[4]+a[j]>2*a[4])as++;
            if(a[i]+a[3]+a[5]+a[j]>2*a[5])as++;
            if(a[i]+a[3]+a[6]+a[j]>2*a[6])as++;
            if(a[i]+a[3]+a[7]+a[j]>2*a[7])as++;
            if(a[i]+a[3]+a[8]+a[j]>2*a[8])as++;
            if(a[i]+a[3]+a[9]+a[j]>2*a[9])as++;
            if(a[i]+a[4]+a[5]+a[j]>2*a[5])as++;
            if(a[i]+a[4]+a[6]+a[j]>2*a[6])as++;
            if(a[i]+a[4]+a[7]+a[j]>2*a[7])as++;
            if(a[i]+a[4]+a[8]+a[j]>2*a[8])as++;
            if(a[i]+a[4]+a[9]+a[j]>2*a[9])as++;
            if(a[i]+a[5]+a[6]+a[j]>2*a[6])as++;
            if(a[i]+a[5]+a[7]+a[j]>2*a[7])as++;
            if(a[i]+a[5]+a[8]+a[j]>2*a[8])as++;
            if(a[i]+a[5]+a[9]+a[j]>2*a[9])as++;
            if(a[i]+a[6]+a[7]+a[j]>2*a[7])as++;
            if(a[i]+a[6]+a[8]+a[j]>2*a[8])as++;
            if(a[i]+a[6]+a[9]+a[j]>2*a[9])as++;
            if(a[i]+a[7]+a[8]+a[j]>2*a[8])as++;
            if(a[i]+a[7]+a[9]+a[j]>2*a[9])as++;
            if(a[i]+a[8]+a[9]+a[j]>2*a[9])as++;
            for(k=j+1;k<10;k++)
            {
            if(a[i]+a[1]+a[2]+a[j]+a[k]>2*a[2])as++;
            if(a[i]+a[1]+a[3]+a[j]+a[k]>2*a[3])as++;
            if(a[i]+a[1]+a[4]+a[j]+a[k]>2*a[4])as++;
            if(a[i]+a[1]+a[5]+a[j]+a[k]>2*a[5])as++;
            if(a[i]+a[1]+a[6]+a[j]+a[k]>2*a[6])as++;
            if(a[i]+a[1]+a[7]+a[j]+a[k]>2*a[7])as++;
            if(a[i]+a[1]+a[8]+a[j]+a[k]>2*a[8])as++;
            if(a[i]+a[1]+a[9]+a[j]+a[k]>2*a[9])as++;
            if(a[i]+a[2]+a[3]+a[j]+a[k]>2*a[3])as++;
            if(a[i]+a[2]+a[4]+a[j]+a[k]>2*a[4])as++;
            if(a[i]+a[2]+a[5]+a[j]+a[k]>2*a[5])as++;
            if(a[i]+a[2]+a[6]+a[j]+a[k]>2*a[6])as++;
            if(a[i]+a[2]+a[7]+a[j]+a[k]>2*a[7])as++;
            if(a[i]+a[2]+a[8]+a[j]+a[k]>2*a[8])as++;
            if(a[i]+a[2]+a[9]+a[j]+a[k]>2*a[4])as++;
            if(a[i]+a[3]+a[5]+a[j]+a[k]>2*a[5])as++;
            if(a[i]+a[3]+a[6]+a[j]+a[k]>2*a[6])as++;
            if(a[i]+a[3]+a[7]+a[j]+a[k]>2*a[7])as++;
            if(a[i]+a[3]+a[8]+a[j]+a[k]>2*a[8])as++;
            if(a[i]+a[3]+a[9]+a[j]+a[k]>2*a[9])as++;
            if(a[i]+a[4]+a[5]+a[j]+a[k]>2*a[5])as++;
            if(a[i]+a[4]+a[6]+a[j]+a[k]>2*a[6])as++;
            if(a[i]+a[4]+a[7]+a[j]+a[k]>2*a[7])as++;
            if(a[i]+a[4]+a[8]+a[j]+a[k]>2*a[8])as++;
            if(a[i]+a[4]+a[9]+a[j]+a[k]>2*a[9])as++;
            if(a[i]+a[5]+a[6]+a[j]+a[k]>2*a[6])as++;
            if(a[i]+a[5]+a[7]+a[j]+a[k]>2*a[7])as++;
            if(a[i]+a[5]+a[8]+a[j]+a[k]>2*a[8])as++;
            if(a[i]+a[5]+a[9]+a[j]+a[k]>2*a[9])as++;
            if(a[i]+a[6]+a[7]+a[j]+a[k]>2*a[7])as++;
            if(a[i]+a[6]+a[8]+a[j]+a[k]>2*a[8])as++;
            if(a[i]+a[6]+a[9]+a[j]+a[k]>2*a[9])as++;
            if(a[i]+a[7]+a[8]+a[j]+a[k]>2*a[8])as++;
            if(a[i]+a[7]+a[9]+a[j]+a[k]>2*a[9])as++;
            if(a[i]+a[8]+a[9]+a[j]+a[k]>2*a[9])as++;
            for(x=k+1;x<10;x++)
            {
            if(a[i]+a[1]+a[2]+a[j]+a[k]+a[x]>2*a[2])as++;
            if(a[i]+a[1]+a[3]+a[j]+a[k]+a[x]>2*a[3])as++;
            if(a[i]+a[1]+a[4]+a[j]+a[k]+a[x]>2*a[4])as++;
            if(a[i]+a[1]+a[5]+a[j]+a[k]+a[x]>2*a[5])as++;
            if(a[i]+a[1]+a[6]+a[j]+a[k]+a[x]>2*a[6])as++;
            if(a[i]+a[1]+a[7]+a[j]+a[k]+a[x]>2*a[7])as++;
            if(a[i]+a[1]+a[8]+a[j]+a[k]+a[x]>2*a[8])as++;
            if(a[i]+a[1]+a[9]+a[j]+a[k]+a[x]>2*a[9])as++;
            if(a[i]+a[2]+a[3]+a[j]+a[k]+a[x]>2*a[3])as++;
            if(a[i]+a[2]+a[4]+a[j]+a[k]+a[x]>2*a[4])as++;
            if(a[i]+a[2]+a[5]+a[j]+a[k]+a[x]>2*a[5])as++;
            if(a[i]+a[2]+a[6]+a[j]+a[k]+a[x]>2*a[6])as++;
            if(a[i]+a[2]+a[7]+a[j]+a[k]+a[x]>2*a[7])as++;
            if(a[i]+a[2]+a[8]+a[j]+a[k]+a[x]>2*a[8])as++;
            if(a[i]+a[2]+a[9]+a[j]+a[k]+a[x]>2*a[4])as++;
            if(a[i]+a[3]+a[5]+a[j]+a[k]+a[x]>2*a[5])as++;
            if(a[i]+a[3]+a[6]+a[j]+a[k]+a[x]>2*a[6])as++;
            if(a[i]+a[3]+a[7]+a[j]+a[k]+a[x]>2*a[7])as++;
            if(a[i]+a[3]+a[8]+a[j]+a[k]+a[x]>2*a[8])as++;
            if(a[i]+a[3]+a[9]+a[j]+a[k]+a[x]>2*a[9])as++;
            if(a[i]+a[4]+a[5]+a[j]+a[k]+a[x]>2*a[5])as++;
            if(a[i]+a[4]+a[6]+a[j]+a[k]+a[x]>2*a[6])as++;
            if(a[i]+a[4]+a[7]+a[j]+a[k]+a[x]>2*a[7])as++;
            if(a[i]+a[4]+a[8]+a[j]+a[k]+a[x]>2*a[8])as++;
            if(a[i]+a[4]+a[9]+a[j]+a[k]+a[x]>2*a[9])as++;
            if(a[i]+a[5]+a[6]+a[j]+a[k]+a[x]>2*a[6])as++;
            if(a[i]+a[5]+a[7]+a[j]+a[k]+a[x]>2*a[7])as++;
            if(a[i]+a[5]+a[8]+a[j]+a[k]+a[x]>2*a[8])as++;
            if(a[i]+a[5]+a[9]+a[j]+a[k]+a[x]>2*a[9])as++;
            if(a[i]+a[6]+a[7]+a[j]+a[k]+a[x]>2*a[7])as++;
            if(a[i]+a[6]+a[8]+a[j]+a[k]+a[x]>2*a[8])as++;
            if(a[i]+a[6]+a[9]+a[j]+a[k]+a[x]>2*a[9])as++;
            if(a[i]+a[7]+a[8]+a[j]+a[k]+a[x]>2*a[8])as++;
            if(a[i]+a[7]+a[9]+a[j]+a[k]+a[x]>2*a[9])as++;
            if(a[i]+a[8]+a[9]+a[j]+a[k]+a[x]>2*a[9])as++;
            for(y=k+1;y<10;y++)
            {
            if(a[i]+a[1]+a[2]+a[j]+a[k]+a[x]+a[y]>2*a[2])as++;
            if(a[i]+a[1]+a[3]+a[j]+a[k]+a[x]+a[y]>2*a[3])as++;
            if(a[i]+a[1]+a[4]+a[j]+a[k]+a[x]+a[y]>2*a[4])as++;
            if(a[i]+a[1]+a[5]+a[j]+a[k]+a[x]+a[y]>2*a[5])as++;
            if(a[i]+a[1]+a[6]+a[j]+a[k]+a[x]+a[y]>2*a[6])as++;
            if(a[i]+a[1]+a[7]+a[j]+a[k]+a[x]+a[y]>2*a[7])as++;
            if(a[i]+a[1]+a[8]+a[j]+a[k]+a[x]+a[y]>2*a[8])as++;
            if(a[i]+a[1]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[9])as++;
            if(a[i]+a[2]+a[3]+a[j]+a[k]+a[x]+a[y]>2*a[3])as++;
            if(a[i]+a[2]+a[4]+a[j]+a[k]+a[x]+a[y]>2*a[4])as++;
            if(a[i]+a[2]+a[5]+a[j]+a[k]+a[x]+a[y]>2*a[5])as++;
            if(a[i]+a[2]+a[6]+a[j]+a[k]+a[x]+a[y]>2*a[6])as++;
            if(a[i]+a[2]+a[7]+a[j]+a[k]+a[x]+a[y]>2*a[7])as++;
            if(a[i]+a[2]+a[8]+a[j]+a[k]+a[x]+a[y]>2*a[8])as++;
            if(a[i]+a[2]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[4])as++;
            if(a[i]+a[3]+a[5]+a[j]+a[k]+a[x]+a[y]>2*a[5])as++;
            if(a[i]+a[3]+a[6]+a[j]+a[k]+a[x]+a[y]>2*a[6])as++;
            if(a[i]+a[3]+a[7]+a[j]+a[k]+a[x]+a[y]>2*a[7])as++;
            if(a[i]+a[3]+a[8]+a[j]+a[k]+a[x]+a[y]>2*a[8])as++;
            if(a[i]+a[3]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[9])as++;
            if(a[i]+a[4]+a[5]+a[j]+a[k]+a[x]+a[y]>2*a[5])as++;
            if(a[i]+a[4]+a[6]+a[j]+a[k]+a[x]+a[y]>2*a[6])as++;
            if(a[i]+a[4]+a[7]+a[j]+a[k]+a[x]+a[y]>2*a[7])as++;
            if(a[i]+a[4]+a[8]+a[j]+a[k]+a[x]+a[y]>2*a[8])as++;
            if(a[i]+a[4]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[9])as++;
            if(a[i]+a[5]+a[6]+a[j]+a[k]+a[x]+a[y]>2*a[6])as++;
            if(a[i]+a[5]+a[7]+a[j]+a[k]+a[x]+a[y]>2*a[7])as++;
            if(a[i]+a[5]+a[8]+a[j]+a[k]+a[x]+a[y]>2*a[8])as++;
            if(a[i]+a[5]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[9])as++;
            if(a[i]+a[6]+a[7]+a[j]+a[k]+a[x]+a[y]>2*a[7])as++;
            if(a[i]+a[6]+a[8]+a[j]+a[k]+a[x]+a[y]>2*a[8])as++;
            if(a[i]+a[6]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[9])as++;
            if(a[i]+a[7]+a[8]+a[j]+a[k]+a[x]+a[y]>2*a[8])as++;
            if(a[i]+a[7]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[9])as++;
            if(a[i]+a[8]+a[9]+a[j]+a[k]+a[x]+a[y]>2*a[9])as++;
        }
        }
    }
    cout<<as;
    return 0;
}
