#include<bits/stdc++.h>
using namespace std;
int t,n,ai=0,bi=0,ci=0;
int a[100010][4];
long long myd=0;
int tzheng(int m)
{
    //cout<<m<<endl;
    int tk=30000,ts,ti,abc,cba;
    for(int i=1;i<=n;i++)
        if(a[i][0]==m)
        {
            if(m==1)
            {
                if(bi<n/2&&ci<n/2)
                {
                    abc=a[i][1]-a[i][2];
                    cba=a[i][1]-a[i][3];
                    //cout<<abc<<" "<<cba<<endl;
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=2;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=3;
                        ti=i;
                    }
                }
                else
                if(bi>=n/2&&ci<n/2)
                {
                    abc=a[i][1]-a[i][2]+tzheng(2);
                    cba=a[i][1]-a[i][3];
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=2;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=3;
                        ti=i;
                    }
                }
                else
                if(bi<n/2&&ci>=n/2)
                {
                    abc=a[i][1]-a[i][2];
                    cba=a[i][1]-a[i][3]+tzheng(3);
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=2;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=3;
                        ti=i;
                    }
                }
            }
            if(m==2)
            {
                if(ai<n/2&&ci<n/2)
                {
                    abc=a[i][2]-a[i][1];
                    cba=a[i][2]-a[i][3];
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=1;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=3;
                        ti=i;
                    }
                }
                else
                if(ai>=n/2&&ci<n/2)
                {
                    abc=a[i][2]-a[i][1]+tzheng(1);
                    cba=a[i][2]-a[i][3];
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=1;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=3;
                        ti=i;
                    }
                }
                else
                if(ai<n/2&&ci>=n/2)
                {
                    abc=a[i][2]-a[i][1];
                    cba=a[i][2]-a[i][3]+tzheng(3);
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=1;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=3;
                        ti=i;
                    }
                }
            }
            if(m==3)
            {
                if(bi<n/2&&ai<n/2)
                {
                    abc=a[i][3]-a[i][2];
                    cba=a[i][3]-a[i][1];
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=2;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=1;
                        ti=i;
                    }
                }
                else
                if(bi>=n/2&&ai<n/2)
                {
                    abc=a[i][3]-a[i][2]+tzheng(2);
                    cba=a[i][3]-a[i][1];
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=2;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=1;
                        ti=i;
                    }
                }
                else
                if(bi<n/2&&ai>=n/2)
                {
                    abc=a[i][3]-a[i][2];
                    cba=a[i][3]-a[i][1]+tzheng(1);
                    tk=min(min(abc,cba),tk);
                    if(tk==abc)
                    {
                        ts=2;
                        ti=i;
                    }
                    if(tk==cba)
                    {
                        ts=1;
                        ti=i;
                    }
                }
            }
        }
    if(m==1)
        ai--;
    if(m==2)
        bi--;
    if(m==3)
        ci--;
    if(ts==1)
        ai++;
    if(ts==2)
        bi++;
    if(ts==3)
        ci++;
    a[ti][0]=ts;
    //cout<<ts<<" "<<tk<<endl;
    return tk;
}
int main()
{
    freopen("club.in","r",stdin);
    freopen("club.out","w",stdout);
    cin>>t;
    for(int j=1;j<=t;j++)
    {
        myd=0;ai=0;bi=0;ci=0;
        cin>>n;
        for(int i=1;i<=n;i++)
        {
            cin>>a[i][1]>>a[i][2]>>a[i][3];
            int p=max(max(a[i][1],a[i][2]),a[i][3]);
            if(p==a[i][1])
            {
                a[i][0]=1;
                ai++;
                myd+=a[i][1];
            }
            if(p==a[i][2])
            {
                a[i][0]=2;
                bi++;
                myd+=a[i][2];
            }
            if(p==a[i][3])
            {
                a[i][0]=3;
                ci++;
                myd+=a[i][3];
            }
        }
        while(ai>n/2||bi>n/2||ci>n/2)
        {
            if(ai>n/2)
                myd-=tzheng(1);
            if(bi>n/2)
                myd-=tzheng(2);
            if(ci>n/2)
                myd-=tzheng(3);
        }
        cout<<myd<<endl;
    }
    return 0;
}
