#include<bits/stdc++.h>
using namespace std;
#define ll long long
ll ans;
ll s[4],t,n,i,j;
int main()
{
	
	freopen("club.in","r",stdin);
	freopen("club.out","w",stdout);
	cin>>t;
	while(t--){
		priority_queue<ll>q[4][4];
		cin>>n;
		ans=0;
		s[1]=s[2]=s[3]=0;
		for(i=1;i<=n;i++){
			int x,y,z;
			cin>>x>>y>>z;
			if(x>=y&&x>=z){
				ans+=x;
				q[1][2].push(y-x);
				q[1][3].push(z-x);
				s[1]++;
			}
			
			else
			if(y>=z&&y>=x){
				ans+=y;
				q[2][1].push(x-y);
				q[2][3].push(z-y);
				s[2]++;
			}
			else
			if(z>=x&&z>=y){
				ans+=z;
				q[3][1].push(x-z);
				q[3][2].push(y-z);
				s[3]++;
			}
		}
		if(s[1]>n/2){
			while(s[1]>n/2&&s[2]<n/2&&s[3]<n/2){
				int x=-INT_MAX,y=-INT_MAX;
				s[1]--;
				if(!q[1][2].empty())
				{
					x=q[1][2].top();
				}
				if(!q[1][3].empty())
				{
					y=q[1][3].top();
				}
				if(x>y){
					s[2]++;
					ans+=x;
					q[1][2].pop();
				}
				else{
					s[3]++;
					ans+=y;
					q[1][3].pop();
				}
			}
			if(s[2]==n/2){
				while(s[1]>n/2){
					s[1]--;
					s[3]++;
					q[1][3].pop();
				}
			}
			if(s[3]==n/2){
				while(s[1]>n/2&&!q[1][2].empty()){
					s[1]--;
					s[2]++;
					q[1][2].pop();
				}
			}
		}
		if(s[2]>n/2){
			while(s[2]>n/2&&s[1]<n/2&&s[3]<n/2){
				int x=-INT_MAX,y=-INT_MAX;
				s[2]--;
				if(!q[2][1].empty())
				{
					x=q[2][1].top();
				}
				if(!q[2][3].empty())
				{
					y=q[2][3].top();
				}
				if(x>y){
					s[1]++;
					ans+=x;
					q[2][1].pop();
				}
				else{
					s[3]++;
					ans+=y;
					q[2][3].pop();
				}
			}
			if(s[1]==n/2){
				while(s[2]>n/2){
					s[2]--;
					s[3]++;
					q[2][3].pop();
				}
			}
			if(s[3]>=n/2){
				while(s[2]>n/2){
					s[2]--;
					s[1]++;
					q[2][1].pop();
				}
			}
		}
		if(s[3]>n/2){
			while(s[3]>n/2&&s[1]<n/2&&s[2]<n/2){
				int x=-INT_MAX,y=-INT_MAX;
				s[3]--;
				if(!q[3][1].empty())
				{
					x=q[3][1].top();
				}
				if(!q[3][2].empty())
				{
					y=q[3][2].top();
				}
				if(x>y){
					s[1]++;
					ans+=x;
					q[3][1].pop();
				}
				else{
					s[2]++;
					ans+=y;
					q[3][2].pop();
				}
			}
			if(s[1]==n/2){
				while(s[3]>n/2){
					s[3]--;
					s[2]++;
					q[3][2].pop();
				}
			}
			if(s[2]==n/2){
				while(s[3]>n/2){
					s[3]--;
					s[1]++;
					q[3][1].pop();
				}
			}
		}
//		cout<<s[1]+s[2]+s[3]; 
		cout<<ans<<endl;
	}
	return 0;
}


